alisw/AliRoot

EVE/CMakeLists.txt

(Note for self: has undefined list of approvers.)

Test +1/+test

---

ANALYSIS/ANALYSIS/AliAnalysisManager.cxx

Revert "non compiling commit"

---

STEER/STEERBase/AliDataFile.cxx
STEER/STEERBase/AliDataFile.h
STEER/STEERBase/CMakeLists.txt
STEER/STEERBase/STEERBaseLinkDef.h
TPC/CMakeLists.txt

Also fixes a TPC installation problem (#49)

Add AliDataFile interface

---

STEER/STEERBase/AliDataFile.h

call Open method from TFile and not from AliDataFile which would add the OADB path again.

fix the bug in AliDataFile.h to add the OADB path twice

---

ITS/macrosSDD/ITSQArecoparam.C

This is a test to verify the workflow with github

Test of commit in github: comment added into macro

---

MUON/MUONmapping/AliMpTriggerPadIterator.cxx
MUON/MUONmapping/AliMpTriggerPadIterator.h
MUON/MUONmapping/AliMpTriggerSegmentation.cxx
MUON/MUONmapping/AliMpTriggerSegmentation.h
MUON/MUONmapping/CMakeLists.txt
MUON/MUONmapping/MUONmappingLinkDef.h

New pad iterator for MTR (for consistency with muon MCH)

Add pad iterator for muon trigger

---

ITSMFT/MFT/MFTbase/AliMFTSupport.cxx

Strong modifications of the support:
- duplication of the first support for the 3 first chambers
- modifications of the PCB to avoid overlap with the peak part of the support
- modifications of the support to avoid overlap with the MFT (heat exchanger, ladders)

Modifications of the support

---

STAT/STATLinkDef.h

Needed for time dependent calibration

Add: class std::map<UInt_t,THn*>

---

HLT/global/AliFlatESDTrack.h
STEER/AOD/AliAODRecoDecay.h
STEER/AOD/AliAODTrack.h
STEER/STEERBase/AliVTrack.h

Revert "All tracks will inherit from abstract AliVTrack::GetSign()"

---

EVGEN/AliGenMUONLMR.cxx

Update of the function Generate and Decay2Body for correction of the kinematics of rho meson

Update of AliGenMUONLMR class

---

ANALYSIS/ANALYSIS/AliAnalysisManager.cxx
HLT/EMCAL/AliHLTEMCALCaloCells.h
ITS/ITSbase/AliITSClusterFinder.cxx
STEER/AOD/AliAODCaloCells.h
STEER/ESD/AliESDCaloCells.h
STEER/ESD/AliESDEvent.cxx
STEER/ESD/AliESDEvent.h
STEER/ESD/AliESDtrack.h
STEER/STEERBase/AliMCEvent.cxx
STEER/STEERBase/AliMCEvent.h
STEER/STEERBase/AliMCEventHandler.cxx
STEER/STEERBase/AliMCEventHandler.h
STEER/STEERBase/AliVCaloCells.h
STEER/STEERBase/AliVEvent.h

1) Make sure the labels of mothers/daughters correctly remapped for embedded event
2) Make sure all sub-events are preread in BeginEvent, to build correct offsets table
3) Relable ESD MC lables in case of embedded MC

Fixes needed for proper analysis of MC-to-MC embedded simulation

---

HLT/ITS/AliHLTITSClusterFinderComponent.cxx
ITS/ITSbase/AliITSClusterFinderSDDfast.cxx

HLT will impose ITS recoparam only if it is not set + fix for mem.leak

---

STAT/AliTMinuitToolkit.cxx
STAT/AliTMinuitToolkit.h
TPC/TPCcalib/AliTPCDistortionFit.cxx
TPC/TPCcalib/AliTPCDistortionFit.h

* Physical models fit (line charge as presented in TB https://indico.cern.ch/event/605126/
* AliTMinitToolkit  - Add dump function per point - used for visualization and function debugging

Add: class AliTPCDeistortionFit as a macro

---

AD/ADrec/AliADQADataMakerRec.cxx
AD/ADrec/AliADReconstructor.cxx
AD/ADsim/AliAD.cxx
AD/ADsim/AliADTriggerSimulator.cxx
STARLIGHT/AliStarLight/AliSLEventHeader.cxx
STARLIGHT/AliStarLight/AliSLEventHeader.h
STARLIGHT/AliStarLight/AliStarLightLinkDef.h
STARLIGHT/starlight/TStarLight/TStarLight.cxx
STARLIGHT/starlight/TStarLight/TStarLight.h
STARLIGHT/starlight/include/gammaavm.h
STARLIGHT/starlight/include/upcevent.h
STARLIGHT/starlight/src/gammaavm.cpp
STARLIGHT/starlight/src/upcevent.cpp

example:
```
AliSLEventHeader *h = ...;
h->GetEventInfo<Double_t>("b-slope");
h->GetEventInfo<Double_t>("t");
h->GetEventInfo<Double_t>("Egam");
h->GetEventInfo<Double_t>("Epom");
h->GetEventInfo<TVector2>("ptGam");
h->GetEventInfo<TVector2>("ptPom");
```

added more parameters to AliSLEventHeader

---

AD/ADbase/AliADRawStream.cxx
AD/ADbase/AliADRawStream.h
AD/ADsim/AliAD.cxx
AD/CMakeLists.txt

Pease comment with "+test" to make sure everything still compiles.

added -Wno-error=strict-overflow

---

EVGEN/AliGenReaderLHE.cxx

advance to next event record corrected

AliGenReaderLHE correction

---

AD/ADrec/AliADQAChecker.cxx
AD/ADrec/AliADQAChecker.h

Couple of changes to prevent periodical recreation of pads, histograms and legends every cycle

Create pads etc only once

---

AD/ADrec/AliADQAChecker.cxx
AD/ADrec/AliADQAChecker.h

This is just one more iteration. There are still remaining issues in the code

more memory leaks fixed (intermediate)

---

EVGEN/AliGenReaderLHE.cxx

see [ALIROOT-7239](https://alice.its.cern.ch/jira/browse/ALIROOT-7239)

FORTRAN->C counting convention

---

EVGEN/AliGenReaderLHE.cxx
EVGEN/AliGenReaderLHE.h

follow-up to [AliRoot/pull/168](https://github.com/alisw/AliRoot/pull/168)

made FORTRAN->C counting convention user settable

---

AD/ADrec/AliADQAChecker.cxx
AD/ADrec/AliADQAChecker.h

Hi @mbroz84,
I could not resist and rewrote AliADQAChecker.
If you want please test it at P2 with AliRoot master. I hope I have not broken anything.
Feel also free to not accept/revert these commits.
Cheers
Christoph

AliADQAChecker rewritten: shortened by ~350 (=25%) LOC

---

STAT/AliTreePlayer.cxx
STAT/TStatToolkit.cxx

*  initialize fit parameters but also errors
##	ATO-402, ATO-372 - be more precise in error message
* full description of error provide in case of invalid histogram syntax 
* dimension, ranges ....

PWGPP-312, PWGPP-314 - FPE fix in the distortion map fits

---

AD/ADrec/AliADQAChecker.cxx
AD/ADrec/AliADQAChecker.h
STAT/AliTreePlayer.cxx
STAT/TStatToolkit.cxx
STEER/STEERBase/AliStack.cxx

- memory leak in GetQABox fixed
- removed unneeded SetRangeUser helper function
- replaced DrawClone -> Draw whenever applicable
For some reason, other commits show up in this PR, I hope this is not a problem.

one more memory leak in AliADQAchecker fixed

---

TPC/TPCcalib/AliTPCDistortionFit.cxx

* Small modifications towards multi line fit after hadsnon session 3 week ago
* mutli line fit not yet fully functional ....

ATO-405,ATO-336: Update after hands-on with Ernst

---

ITS/ITSbase/AliITSDetTypeRec.cxx

In SPDVertex DA the RecoParam is not supplied, need protection for its absence

Protection against absence of recoparam in DigitsToRecPoints

---

MUON/MUONcalign/AliMUONAlignment.cxx
MUON/MUONcalign/AliMUONAlignment.h
MUON/MUONcalign/AliMUONAlignmentTask.cxx
MUON/MUONcalign/AliMUONAlignmentTask.h
MUON/MUONcalign/MUONcalignLinkDef.h

Long due update to the muon alignment code.
Changes are included in the commit logs

Master muon alignment

---

TPC/TPCbase/AliTPCcalibDB.cxx

In the implemented logic we relied on one point at SOR and one at EOR
At some point the preprocessor was changed in a way that deletes points
outside a certain dead band, which also most of the time deletes the
point at EOR.
The logic needed to be update to be able to deal with this

fix channel masking, increase verbosoty

---

EMCAL/EMCALUtils/AliEMCALGeometry.cxx
EMCAL/EMCALUtils/AliEMCALGeometry.h

This bug was introduced by commit 88429ce92e7c55c8cadb223ade4d6628104f871b

Bug fix: EMCal misal matrices were not properly load.

---

ALIGN/AliAlgSensTOF.cxx

Data reconstructed after Sept.2015 has Z in the TOF alignment data fixed, no need to correct for old bug when processing TOF

Test for Z-fix when processing TOF points

---

T0/DA/T00Physda.cxx

T00PhysDA : CFD vs timestamp histogram's range set to 20hours

DA : CFD vs timestamp histogram's range set to 20hours

---

EVGEN/AliDecayerPolarized.cxx
EVGEN/AliDecayerPolarized.h
THerwig/THerwig6.cxx

Solution for
https://alice.its.cern.ch/jira/browse/ALIROOT-7324

change min lifetime for partice to be considered stable

---

cmake/FindROOT.cmake

Required by alisw/AliRoot#248 for producing the DAs

Add ROOT net/http object files to static builds

---

MUON/MUONmpgraphics/AliMpRowSegmentPainter.cxx
MUON/mapping/macros/README.md
MUON/mapping/macros/testDE.C
MUON/mapping/macros/testGraphicsSlat.C
MUON/mapping/macros/testSt12AllIndices.C
MUON/mapping/macros/testSt12AnyPadIterators.C
MUON/mapping/macros/testSt12ExistingPads.C
MUON/mapping/macros/testSt12ExistingPads2.C
MUON/mapping/macros/testSt12Graphics.C
MUON/mapping/macros/testSt12IndicesLimits.C
MUON/mapping/macros/testSt12MotifTypeIterators.C
MUON/mapping/macros/testSt12PadDimensions.C
MUON/mapping/macros/testSt12PrintLimits.C
MUON/mapping/macros/testSt12ReadMotifType.C
MUON/mapping/macros/testSt12ReadSector.C
MUON/mapping/macros/testSt12SectorAreaIterator.C
MUON/mapping/macros/testSt12SectorFind.C
MUON/mapping/macros/testSt12SectorPadIterators.C
MUON/mapping/macros/testSt345Pads.C
MUON/mapping/macros/testSt345ReadMotifType.C
MUON/mapping/macros/testSt345ReadPCB.C
MUON/mapping/macros/testSt345ReadSlat.C
MUON/mapping/macros/testUpdateGlobalIndices.C
MUON/mapping/macros/test_suite.sh
MUON/mapping/macros/timeMapping.C

Reviving (i.e. make them compile again...) the macros to test the mapping graphics

Muon mapping test macros

---

EMCAL/macros/OADB/CreateEMCAL_OADB_RunByRunTimeCalib.C
EMCAL/macros/OADB/UpdateEMCAL_OADB_RunByRunTimeCalib.C
EMCAL/macros/OADB/UpdateEMCAL_OADB_TimeCalib.C

1. Macro to create OADB root object with L1 phases for EMCal.
2. Macro to update OADB root object with L1 phases for EMCal.
3. Macro to update OADB root object with time calibration for EMCal.

Macros to create and update OADB with L1 phases and time calibration

---

test/vmctest/gun/finalcheck.sh

* Allow for final ESD check or not

Modifying a check script that verifies a correct vmctest/gun run

---

AD/ADsim/AliADDigitizer.cxx
STARLIGHT/AliStarLight/AliGenStarLight.h
STARLIGHT/starlight/TStarLight/TStarLight.h
STARLIGHT/starlight/include/incoherentVMCrossSection.h
STARLIGHT/starlight/include/inputParameters.h
STARLIGHT/starlight/include/narrowResonanceCrossSection.h
STARLIGHT/starlight/include/photonNucleusCrossSection.h
STARLIGHT/starlight/include/wideResonanceCrossSection.h
STARLIGHT/starlight/src/incoherentVMCrossSection.cpp
STARLIGHT/starlight/src/inputParameters.cpp
STARLIGHT/starlight/src/narrowResonanceCrossSection.cpp
STARLIGHT/starlight/src/photonNucleusCrossSection.cpp
STARLIGHT/starlight/src/wideResonanceCrossSection.cpp

- AD: initialization of TClonesArray TTree branches fixed: a similar problem has been found before but one instance of TClonesArray initialization was not corrected then.
- STARLIGHT: update to the latest svn revision from hepforge: this improves the printout for the cross section calculation and should not change the generation of particles

STARLIGHT+AD update

---

EVGEN/AliGenReaderHepMC.cxx

This should solve the problem with the production time in EPOS productions.
https://alice.its.cern.ch/jira/browse/PWGMM-21

Conversion from cm/c to s for production time.

---

ANALYSIS/ANALYSISalice/AliAnalysisTaskPIDqa.cxx

Change TH2 to TProfile, otherwise there will be problems when merging
the output.

Fix PID in tracking plot

---

AD/ADsim/AliADDigitizer.cxx

AD/Calib/Saturation contains a `TTree` with `TClonesArray` branches where the `TClonesArray`s contain `TF1`s:
- When `TClonesArray::Delete() `is not called after `TTree::GetEntry()`, in the next call of `TTree::GetEntry()` `TF1`s with new names are added to the global list of functions **which always have the same address**
- If this happens more than once, the global list of functions contains several entries with the same address which leads to problems when the global list of functions is deleted.

TClonesArray::Delete must be always called

---

STAT/AliExternalInfo.cxx

* curl replaced  TFile::Cp in case of http files
* using -z option of curl
* Request a file that has been modified later than the given time and date .e.g
```
curl -Lk -z /home/miranov/AliExternalInfoCache//data/2015/LHC15o/pass1/TRD_trending.root
```
* curl interface tested using limited versions of curl changing cache modification date

ATO-421, ATO-46 - caching of http root files using curl

---

MUON/MUONmapping/AliMpMotif.cxx
MUON/MUONmapping/AliMpMotif.h
MUON/MUONmapping/AliMpMotifSpecial.cxx
MUON/MUONmapping/AliMpMotifSpecial.h
MUON/MUONmapping/AliMpMotifType.cxx

Adding Clone method to some motif classes to be able to properly copy them when developing O2 mapping.

Adding proper Clone

---

STEER/Utilities/CMakeLists.txt
STEER/Utilities/alilog4bash.sh
STEER/Utilities/utilities.sh

* alilog4bash.sh and utilities.sh - needed for CTests of aliroot
*  to avoid circular dependency - move for AliPhysics to AliRoot
*  Agreed already some time ago
* first step: add the code into AliRoot
* next step: removing from AliPhysics once AliRoot release with changes available

ATO-426: MOVE alilog4bash.sh and utilities.sh AliPhysics->AliRoot

---

STEER/STEERBase/AliStack.cxx
STEER/STEERBase/AliStack.h

Reverts alisw/AliRoot#271
After some investigations it seems that this pull request does not behave according to the expectations and creates problems with EPOS, pythia, etc. Following a request from the physics coordination I am reverting it temporarily.

Revert "Changes to do with primary particle definition as implemented"

---

STEER/Utilities/CMakeLists.txt
STEER/Utilities/alihadd.sh
STEER/Utilities/test/alihadd.test.sh

* function testFileList()
* check root files
* test read/write/delete
* test only for selected key - array of regulr expression e.g
* -checkKeys highPt - check highPt keys
* -checkKeys . - check all keys
* function makeFilteredList()
* to prepare lists of good and bad files
* function alihaddsh
* to merge root files
* using internaly alihadd
* optional switch to checkKyes
```
alihaddsh -k -s 200000000   -checkKeys highPt -prefetch 1 -v 1 -timeOut 30 test.root @input.list
```
* test/alihadd.test.sh
* test of alihadd.sh
* some modification needed (input list) before integrating into ctest
* most probably data from EOS/http to be used for test

PWGPP-350 - ADD alihadd.sh and alihadd.test.sh

---

AD/ADsim/AliADv1.cxx

- ion pump below warm module added (C-side)
- valve vertical offset adjusted (C-side)
- support removed, now implemented by ZDC code (A-side)

AD geometry updates: Pump added in C-Side, A-Side support removed

---

AD/ADsim/AliADv1.cxx

Warm module support between compensator magnet and ZEM. x-position corrected.

Correct position of warm module support (A-Side)

---

test/genkine/simG4/Config.C
test/vmctest/gun/g4Config.C
test/vmctest/ppbench/g4Config.C

Use the default Geant4 stepper in the tests: NystromRK4 has problems as discussed in 
https://alice.its.cern.ch/jira/browse/ALIROOT-7333

ALIROOT-7333 Do not use NystromRK4 stepper, it is not working correctly

---

doxygen/Doxyfile.in
doxygen/mainpage.md

* Add aliBuild references
* Ignore `ClassDef` and `ClassImp` (thanks @cholmcc)
Supersedes #270.

Improve Doxygen documentation

---

STEER/AOD/AliNanoAODHeader.cxx
STEER/AOD/AliNanoAODHeader.h
STEER/AOD/AliNanoAODTrackMapping.cxx
STEER/AOD/AliNanoAODTrackMapping.h

Implement some missing variables for NanoAODs

implement new variables for NanoAOD

---

ANALYSIS/ANALYSIS/AliAnalysisTaskCfg.cxx

define __R_ADDTASK__ if first use is in a scoped block of the task configuration

bugfix in the task configuration of the analysis manager

---

STEER/Utilities/CMakeLists.txt
STEER/Utilities/test/CMakeLists.txt
STEER/Utilities/test/utilities.test.sh

I apologize.  I previous request I forgot to move  also the test.
Now the transition should be full.
Related to previous pull requests:
https://github.com/alisw/AliRoot/pull/325
https://github.com/alisw/AliPhysics/pull/2444

ATO-426 - Move test of alilog4bash and utilities AliPhysics->AliRoot

---

EVGEN/AliDecayer.h
EVGEN/AliGenMC.cxx
PYTHIA6/AliPythia6/AliDecayerPythia.cxx
PYTHIA6/AliPythia6/AliDecayerPythia.h
PYTHIA8/AliPythia8/AliDecayerPythia8.cxx
PYTHIA8/AliPythia8/AliDecayerPythia8.h

Adds options to AliDecayerPythia to allow forcing of Lc->pKpi or Lc->pK0S for dedicated MC productions (Jira ticket ALIROOT-7487)

ALIROOT-7487: Add options to force Lc decay channel in AliPythia

---

STEER/STEERBase/AliStack.cxx
TFluka/input/coreFlukaVmc.inp
TFluka/scripts/runflukageo.sh

needed for new version fluk2011_2c

changes in the fluka vmc scipts to write the error output from lun 15 into fluka.err

---

STEER/STEERBase/AliTriggerScalers.cxx

This is minor comment change. I use it to test github pull request procedure.

Comment updated

---

TOF/TOFbase/AliTOFGeometry.cxx
TOF/TOFbase/AliTOFGeometry.h
TOF/TOFsim/AliTOFTrigger.cxx
TOF/TOFsim/AliTOFTrigger.h

- LTM indexing moved fro AliTOFTrigger to AliTOFGeomety (TOFbase dir)
- fixing for LTM indexing in raw data (reconstruction)

TOF trigger map in raw data: fixed LTM indexing

---

TOF/TOFsim/AliTOFTrigger.cxx
TOF/TOFsim/AliTOFTrigger.h
TOF/TOFsim/checkMCmap.C

- refinement of TOF  Maxipad indexing in MC
- add macro to draw the indexes on the supermodule

refinement on MC maxipad mapping

---

HLT/global/AliHLTGlobalLinkDef.h

error on macos sierra, reported by Jeremi

Fix preprocessor directive syntax

---

STARLIGHT/AliGenFlat2Trk/AliGenFlat2Trk.cxx
STARLIGHT/AliGenFlat2Trk/AliGenFlat2Trk.h

now it can be used for simulating gamma gamma->gamma gamma

allow decays into pair of neutral particles

---

MUON/MUONgraphics/AliMUONVPainter.cxx

A small fix to avoid a crash when mchview is compiled against Root6.

Fix for Root6

---

HLT/BASE/CMakeLists.txt

Revert "Add Cint dependency to libAliHLTUtil.so"

---

ITS/DA/SDDBASda.cxx
ITS/DA/SDDGAINda.cxx

This commit contains 2 updates in the SDD DAs:
1) return error if not enough events
2) preserve output of previous calibration

New features in SDD DAs

---

TPC/TPCrec/AliTPCtracker.cxx
TPC/TPCsim/AliTPCDigitizer.cxx

* AliTPCDigitizer.cxx
* add check ion tail graph ranges
* AliTPCtracker.cxx
* different ion tail factor for MC/data
* to distinguish between MC/real data use presence of the TPC digit file
```
if (gSystem->AccessPathName("TPC.SDigits.root",kFileExists)==kFALSE){ // Is MC data?
```

ALIROOT-7077, ATO-304 0 Ion tail and common mode in MC

---

DRGEN/AliGenDRgen.cxx
DRGEN/AliGenDRgen.h
DRGEN/CMakeLists.txt

A possibility to produce central system in specified mass, pt and rapidity ranges is added. These cuts were requested by Evgeny Kryshen.

Kinematic cuts for DRgen  

---

STEER/STEER/AliMC.cxx
STEER/STEERBase/AliPDG.cxx

Changes for the Lnn mass for MC sim

---

EVE/CMakeLists.txt
EVE/converters/ConverterJSON/AliConverterCalorimetersEngine.cxx
EVE/converters/ConverterJSON/AliConverterPolylinesEngine.cxx
EVE/executables/CMakeLists.txt

Updates in ConverterJSON

---

STAT/AliTreeTrending.cxx
STAT/TStatToolkit.cxx

TStatToolkit.cxx, AliTreeTrending.cxx
* ATO-83:  Protection against invalid tree queries
* ATO-433: Protection against of failure in case not cut specified

ATO-83, ATO-433: More verbose tree queries in case of failures

---

STEER/STEERBase/AliTRDPIDParams.h

Increased ClassDef of Threshold from 2 to 3

---

EVGEN/AliGenCocktail.cxx
EVGEN/AliGenCocktail.h

Hi @amorsch ,
I added the modification to AliGenCocktail that we discussed yesterday.
The default behaviour does not change. The modifications are minimal but the fix of formatting makes them not very visible. Please check the diff without white spaces changes [here](https://github.com/alisw/AliRoot/compare/master...mpuccio:master?w=1) (or adding ?w=1 to the url of this page).
Cheers,
Max

New single injection per event mode

---

STAT/AliTreePlayer.cxx
STAT/Macros/AliExternalInfo.cfg

ATO-46          - Add index name for the Monalisa production table
PWGPP-205  - Check tree query buffer pointer

ATO-46, PWGPP-205- Bug fix

---

STAT/AliTMinuitToolkit.cxx
STAT/AliTMinuitToolkit.h

* Huber and pseudo huber cost function
* HuberLogLike
* PseudoHuberLogLike
*  RegisterPlaneFitter(Int_t nPlanes, Int_t logLikeType)
* function to add fitter to list of known fitters

ATO-430: Add robust hyperplane fitter (as in TLinearFitter)

---

DRGEN/AliGenDRgen.cxx
EVGEN/AliDecayerExodus.cxx

- needed for T0 digitization task

Adding Event header name

---

STAT/AliTMinuitToolkit.cxx
STAT/AliTMinuitToolkit.h
STAT/Macros/aliExternalInfo.C
STAT/test/AliExternalInfoTest.C
STAT/test/AliTMinuitToolkitTest.C

* STAT/test/AliTMinuitToolkitTest.C
* adding doxygen documentation
* compare differnt minimization strategies
* problems indicated for misac minimization
* TODO - check reset parameters after each iteration
* AliTMinuitToolkit.h, AliTMinuitToolkit.cxx
* adding assymetric gauss to list of predefined function
STAT/Macros/aliExternalInfo.C, STAT/test/AliExternalInfoTest.C
ATO-46, ATO-83 - small fixes in macros

ATO-410, ATO-418: Add doxygen documentation for non linear fits

---

HLT/TRD/tracking/AliHLTTRDTrack.h
HLT/TRD/tracking/AliHLTTRDTracker.cxx
HLT/TRD/tracking/AliHLTTRDTracker.h

- no more x-shift necessary
- parameter for max track eta
- more verbose debug output
- some simplifications

Code revision for HLT TRD tracking

---

STEER/AOD/AliNanoAODHeader.h
STEER/AOD/AliNanoAODStorage.cxx

added the BunchCrossNumber, OrbitNumber and PeriodNumber

implement additional variables in the NanoAODs 

---

STEER/ESD/AliESDFIT.cxx
STEER/ESD/AliESDFIT.h

This is an update for FIT, does not affect run2 stuff

write number of photons to ESD

---

TOF/TOFrec/AliTOFT0v1.cxx
TOF/TOFrec/AliTOFT0v1.h

add the possibility to run T0-TOF alghoritm in two independent samples of tracks (calibration mode)

add the possibility to run T0-TOF alghoritm in two independent samples

---

ZDC/ZDCbase/AliZDCEnCalib.cxx
ZDC/ZDCsim/AliGenZDC.cxx
ZDC/ZDCsim/AliZDCv4.cxx

Remove useless prints leftover in the version previously committed in ZDC repository + correcting units in printing calibration object

Commenting leftover prints

---

STEER/STEER/AliHelix.cxx

+ protection against R*Phi to DCA > 400*2pi

Limit helix DCA phase*r search to 100cm,

---

TOF/TOFrec/AliTOFT0v1.cxx

fix in TOF exp sigma value for T0-TOF

fix in TOF exp sigma value for T0-TOF

---

EMCAL/macros/OADB/RemovePeriodEMCAL_OADB_TimeCalib.C

Macro to remove time calibration constants from OADB for one period.

Macro to remove time calibration constants from OADB for one period

---

ANALYSIS/ANALYSISalice/AliAnalysisTaskPIDResponse.cxx
STEER/STEERBase/AliProdInfo.cxx
STEER/STEERBase/AliProdInfo.h

* Read missing pass name or overwrite if it exists from OADB
* Check for multiple pass names for one production and check if this is
handled by the OADB
* Force pass name from AliProdInfo if it exists

Automatise setting of pass name for MC

---

TRD/TRDbase/AliTRDcluster.h
TRD/TRDbase/AliTRDclusterizer.cxx
TRD/TRDbase/AliTRDdEdxReconUtils.cxx

Bugfix for truncated mean

---

ANALYSIS/ANALYSISalice/AliAnalysisTaskPIDqa.cxx

- Fix after code breaking runtime
- Log to be provided if needed

Added safety for the existance of the MC track

---

TOF/TOFrec/AliTOFT0v1.h
TOF/TOFrec/AliTOFT0v2.cxx
TOF/TOFrec/AliTOFT0v2.h
TOF/TOFrec/CMakeLists.txt
TOF/TOFrec/TOFrecLinkDef.h

a new version of AliTOFT0 is added. It will be used for pilup studies

add TOF t0v2 prototype to study pilup using timing with TOF tracks

---

ALIROOT/alivdtwrapper.cxx

vdt sin,cos, sincos require argument within MAX_INT*pi/4 range

vdt sincos with arg>1.6e9 mapped to libm sin,cos

---

STAT/TStatToolkit.cxx
STEER/ESD/AliKFParticle.h
TPC/TPCcalib/AliTPCcalibAlign.cxx
TPC/TPCcalib/AliTPCcalibBase.cxx

The fitting in ROOT6 needs some initializations that are not necessary with ROOT5. This fix was done together with @shahor2.

Fixes for ROOT6 

---

STEER/STEERBase/AliOADBContainer.cxx
STEER/STEERBase/AliOADBContainer.h
STEER/STEERBase/STEERBaseLinkDef.h

Small updates following comments in #615 from @mfasDa 
If ok would request to merge and to port to the next aliroot tag.

Preparation for proper ownership, disabled for now.

---

STEER/STEERBase/AliMagF.cxx
STEER/STEERBase/AliMagFast.cxx
STEER/STEERBase/AliMagFast.h
STEER/STEERBase/AliMagFastDip2k/AliMagFastDip2k.cxx
STEER/STEERBase/AliMagFastDip2k/CMakeLists.txt
STEER/STEERBase/AliMagFastDip5k/AliMagFastDip5k.cxx
STEER/STEERBase/AliMagFastDip5k/CMakeLists.txt
STEER/STEERBase/CMakeLists.txt

@shahor02 Could you check the code? The dipole part should return exactly same results against AliMagF's.

Introduce fast Dipole field parametrizations

---

TPC/TPCsim/AliTPCv0.cxx
TPC/TPCsim/AliTPCv2.cxx
TPC/TPCsim/AliTPCv4.cxx

Geometry corrections

---

EMCAL/macros/OADB/testContainerOrig.C
STEER/STEERBase/AliOADBContainer.cxx
STEER/STEERBase/AliOADBContainer.h

Implemented proper ownership handling and added test macro.

add def owner and test macro

---

EVGEN/AliDecayerExodus.cxx
EVGEN/AliDecayerExodus.h

Update LMee cocktail with the rho spectral function from NA60 (Physics Letters B 757 (2016) 437–444)

Update LMee cocktail with the rho spectral function from NA60 (Physics Letters B 757 (2016) 437–444)

---

ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx
EMCAL/EMCALUtils/AliEMCALRecoUtils.cxx
EMCAL/EMCALUtils/AliEMCALRecoUtils.h
EMCAL/EMCALUtils/AliEMCALRecoUtilsBase.cxx
EMCAL/EMCALUtils/AliEMCALRecoUtilsBase.h
EMCAL/EMCALUtils/CMakeLists.txt
EMCAL/EMCALUtils/EMCALUtilsLinkDef.h
EMCAL/EMCALrec/AliEMCALReconstructor.cxx
EMCAL/EMCALrec/AliEMCALTracker.cxx

First step before moving AliEMCALRecoUtils to AliPhysics

 split AliEMCALRecoUtils into AliEMCALRecoUtils and AliEMCALRecoUtilsBase

---

STEER/STEER/AliSimulation.cxx
STEER/STEERBase/AliTRDPIDParams.cxx
STEER/STEERBase/AliTRDPIDParams.h
TPC/TPCbase/AliTPCcalibDB.cxx

@wiechula Please note that this fix modifies TPC DB initilaliation, the problem is described here: https://alice.its.cern.ch/jira/browse/ALIROOT-7690?focusedCommentId=212005&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-212005

Fixes to run simulation in runs w/o TPC in GRP

---

EMCAL/EMCALbase/AliEMCALTriggerDCSConfig.cxx
EMCAL/EMCALbase/AliEMCALTriggerDCSConfig.h

Implement check of the TRU status based on the status in
the STU region.

[EMCAL-39, ALIROOT-7708] Check for active TRU

---

AD/ADsim/AliAD.cxx

This fix issue with fluka. See: https://alice.its.cern.ch/jira/browse/ALIROOT-7723?focusedCommentId=211901&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-211901

Fix for Fluka

---

HLT/createGRP/lib/CMakeLists.txt

Complements #667 and fixes a problem found with DA RPM builds

Add missing STAT in various include_directories

---

STAT/AliExternalInfo.cxx
STAT/AliMathBase.cxx
STAT/AliMathBase.h
STAT/AliNDLocalRegression.cxx
STAT/AliTMinuitToolkit.cxx
STAT/AliTreePlayer.cxx
STAT/AliTreeTrending.cxx
STAT/CMakeLists.txt
STAT/TStatToolkit.cxx
STAT/TStatToolkit.h
TPC/TPCbase/AliTPCParam.cxx
TPC/TPCrec/AliTPCseed.cxx
TPC/TPCsim/AliTPCv2.cxx
TPC/TPCsim/AliTPCv4.cxx

Please do not merge this pull request, it has to be reviewed by @miranov25 .

STAT becomes independent of STEERBase

---

ITSMFT/ITS/ITSUpgradeRec/AliITSUCATracker.cxx
ITSMFT/ITS/ITSUpgradeRec/AliITSUTrackerGlo.cxx

Hi @shahor02,
this should fix the issue we encounter with the upgrade production.
It was due to the change of ordering in the cluster and the change of frame.
This should address both the issues.
Cheers,
Max

Fix CA-Glo interplay (ALIROOT-7743)

---

CMakeLists.txt

Ciao @dberzano ,
this is on the same line of what you did for o2. It does need a scrutiny before merging.
Cheers,
Max

Improve install speed on macOS (see O2)

---

CMakeLists.txt

Generation of DA RPMs is broken because of #684, this one fixes it

Speed up installation only outside Online Mode

---

HLT/ITS/trackingSAP/AliITSSAPTracker.cxx
HLT/ITS/trackingSAP/AliITSSAPTracker.h
HLT/ITS/trackingSAP/Process.C
HLT/TOF/AliHLTTOFRawCluster.h
ITS/ITSsim/AliITS.cxx
ITS/ITSsim/AliITS.h
ITSMFT/ITS/ITSUpgradeRec/AliITSUTrackerGlo.cxx
ITSMFT/ITS/ITSUpgradeRec/AliITSUTrackerGlo.h
STEER/ESD/AliKalmanTrack.cxx
STEER/STEER/AliCluster.cxx
STEER/STEERBase/AliMCEvent.cxx
STEER/STEERBase/AliMiscConstants.h
STEER/STEERBase/AliStack.cxx
STEER/STEERBase/CMakeLists.txt
TPC/TPCsim/AliTPC.cxx

Label 3141593 is defined as a dummy label. AliMCEvent and AliStackIn will return 0 on query of the
particle with such a label

Introduce common dummy particle label

---

EMCAL/EMCALbase/AliCaloCalibSignal.cxx

https://alice.its.cern.ch/jira/browse/EMCAL-213

Fix for AliCaloCalibSignal for EMCAL-213

---

STEER/STEER/AliLHCData.cxx
STEER/STEER/AliLHCData.h

Store new records in LHCData:
ALI_Lumi_Source_Name
LHC_BetaStar_TargetOptic
LHC_BetaStar_Active

Store new Beta* leveling records in LHCData

---

MUON/macros/MUONStatusMap.C

Also tamed the yellow of the period range quite a bit. Gentler for the eyes of the viewer...

Updates for (end of)2016 -> 2018 period ranges. 

---

STEER/STEER/AliLumiTools.cxx
STEER/STEER/AliLumiTools.h

Will extract from the LHCData inst. lumi with high frequency sampling

Added method AliLumiTools::GetLumiFromDIPInst

---

STAT/Macros/AliNDFunctionInterface.cxx
STAT/Macros/AliNDFunctionInterface.h
STAT/Macros/QAtrendingFitExample.C

* adding support for vectors of MVA regression
* extended Doxygen documentation
* adding global verbosity flag
* ADD:
* map of registered method array
* LoadMVAArrayReader - to load MVA method arrays
* EvalMVAStatArray - to evaluate statistic on top of regression array

ATO-445 - Bootstrap emulation + regression error estimates

---

STAT/AliTreePlayer.cxx
STAT/AliTreePlayer.h
STAT/Macros/AliNDFunctionInterface.cxx

* add number of entries and first entry as an optional parameter
* adding TKey - compilation problem for some version of ROOT6 macros did not comile

 ATO-382 - AliTreePlayer::MakeCacheTree update

---

ANALYSIS/ANALYSIS/AliAnalysisManager.cxx
ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx

This should address the issue with the change of default compression algorithm in ROOT v6-14-00.
Do not merge until someone else besides me test it :)

Use the old ROOT default compression algorithm/level

---

T0/T0base/AliT0Digitizer.cxx

In case of multiple inputs T0 was skipping all inputs but last one (background),
creating digits in the AliT0 copy associated with its loader and then using for
TreeD the empty digit container of the AliT0 loaded from the 1st input. Now all
inputs are incrementally processed and digits are registered in the AliT0 of the
1st input

Fix for T0 MC-embedding

---

TFluka/input/coreFlukaVmc.inp

Fix magfield params in TFluka (ALIROOT-7723)

---

STEER/ESD/AliFMDFloatMap.cxx
STEER/ESD/AliFMDFloatMap.h

Move AliFMDFloatMap operators from .h to .cxx

---

MUON/MUONshuttle/AliMUONConfigSubprocessor.cxx

instead of just the current run.

[ALIROOT-8002] Make the Config object valid up to infinity

---

EMCAL/EMCALrec/AliEMCALUnfolding.cxx
EMCAL/EMCALrec/AliEMCALUnfolding.h

New variable: range is added to unfolding.

New variable: range is added to unfolding

---

HLT/BASE/util/AliHLTCaloClusterReader.cxx
HLT/BASE/util/AliHLTCaloClusterReader.h
HLT/CALO/AliHLTCaloClusterAnalyser.cxx
HLT/CALO/AliHLTCaloClusterizer.cxx
HLT/CALO/AliHLTCaloClusterizer.h
HLT/CALO/AliHLTCaloClusterizerComponent.cxx
HLT/CALO/AliHLTCaloClusterizerComponent.h
HLT/CALO/AliHLTCaloClusterizerNbyN.cxx
HLT/CALO/AliHLTCaloLinkDef.h
HLT/CALO/AliHLTCaloRecPointDataStruct.h
HLT/EMCAL/AliHLTEMCALClusterMonitor.cxx
HLT/EMCAL/AliHLTEMCALClusterMonitor.h
HLT/EMCAL/AliHLTEMCALClusterMonitorComponent.cxx
HLT/EMCAL/AliHLTEMCALClusterizerComponent.cxx

Implementation of EMCAL clusterizer on HLT.

[EMCAL-33] Added EMCAL clusterizer to HLT

---

ANALYSIS/macros/train/AddMCGenPythia6425.C

Add ROOT6-enabled Add-macro for Pythia 6.4.25

---

STAT/Macros/AliNDFunctionInterface.cxx
STAT/Macros/AliNDFunctionInterface.h
STAT/Macros/QAtrendingFitExample.C

* AliNDFunctionInterface::EvalMVAClasification added
* Change AliNDFunctionInterface::FitMVAClasification
** problem with global directory - trees to be opened before TMVA starts
* QAtrendingFitExample.C
** Fix for the TSring+Int operator (desn not work for some of roots)

PWGPP-465: Add AliNDFunctionInterface::EvalMVAClasification

---

HLT/TPCLib/AliHLTTPCClusterTransformation.cxx

bug fix in test code for HLT TPC transformation

bug fix in test code

---

EVGEN/AliGenParam.h

See https://github.com/alisw/AliRoot/commit/e807473c8bb6804ffb0afc0b7e0b6d7354ff4283#commitcomment-31099066

Increase ClassDef.

---

GRP/MakeLumiRefObject.C

Affected runs: 295671-673-675-676-677-712-713-714-717-718-719-720

Downscale by 0.135 the eff for some PbPb runs

---

EMCAL/EMCALbase/AliEMCALTriggerRawDigitMaker.cxx
EMCAL/EMCALbase/AliEMCALTriggerSTURawStream.cxx
EMCAL/EMCALbase/AliEMCALTriggerSTURawStream.h
STEER/ESD/AliESDCaloTrigger.h

fix rho value and max gamma patch
add the missing GA digits in median mode

EMCAL-408 fix AliEMCALSTURawStream decoder

---

STEER/AOD/AliAODCaloTrigger.cxx
STEER/ESD/AliESDCaloTrigger.cxx

This allows to copy run1 objects.
Closes https://alice.its.cern.ch/jira/browse/ALIROOT-8089

Protection of copy against class version 6

---

EMCAL/EMCALbase/AliEMCALTriggerRawDigitMaker.cxx

fix mismatch V0 id - patch id

---

TPC/TPCbase/AliTPCcalibDB.cxx
TPC/TPCbase/AliTPCcalibDB.h
TPC/TPCrec/AliTPCtracker.cxx

Fix active time in channel masking due to HV information

---

TOF/TOFsim/AliTOFSDigitizer.cxx
TOF/TOFsim/testSDigitezer.C

Fix to correct rare hits with a residual ouside the pad (keep them inside)

fix in TOF SDigitizer for rare problematic hits

---

TPC/TPCcalib/AliTPCDcalibRes.cxx
TPC/TPCcalib/AliTPCDcalibRes.h

The sample macro for the morphing is provided in the $ALIDPG/DataProc/TPCSPCalibration/morphMaps.C. See https://alice.its.cern.ch/jira/browse/ATO-463 for details

Possibility to morph SCD maps according some weight function

---

STEER/AOD/AliAODHandler.cxx
STEER/AOD/AliAODMCParticle.cxx
STEER/AOD/AliAODMCParticle.h
STEER/STEERBase/AliMCEvent.cxx
STEER/STEERBase/AliMCParticle.h
STEER/STEERBase/AliVParticle.h

Do not approve merging, it should be done by @dberzano at the tagging time

Massive renaming of AliVParticle label getters

---

ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx

Code fix to prevent some rare cases in which the AOD filtering for the ZDC was writing wrong timing in AODs. Code checked on data with Francesco Prino.
Thanks, 
chiara

Fixing problem in AOD filtering for ZDC

---

STEER/STEER/AliMC.cxx

* Simulation now writes a text file containing a mapping
of logical volume names to the module that owns them;
This is needed for accounting of MC steps to modules (as done
in the MCStepLogger and related analysis)
* Adding an option to achieve reproducible/deterministic event sequence
when setting a special environment variable. This is a useful and painless way
to achieve same event sequence for G3 and G4 productions, for instance.

AliMC: volume-to-module map; deterministic event seeding

---

STAT/AliTMinuitToolkit.cxx
STAT/AliTreePlayer.cxx

* TODO: should be parameterized 
* make initial matrix for fitting

 PWGPP-485 - using cache read in case of the http

---

ITS/ITSrec/AliITSOnlineCalibrationSPDhandler.cxx
ITS/ITSrec/AliITSOnlineCalibrationSPDhandler.h

Modification by @fcolamar @gtrombet

Add method to task SPD sparse dead channels (from Fabio and Giuseppe)

---

STAT/AliNDLocalRegression.cxx
STAT/AliNDLocalRegression.h
STAT/AliTreePlayer.cxx
STAT/AliTreePlayer.h

* ATO-452: adding static function to create regression
* adding verbosity level

PWGPP-485 modifications for RootInteractive

---

TPC/TPCcalib/AliTPCDcalibRes.cxx
TPC/TPCcalib/AliTPCDcalibRes.h

Arbitrary binning for Z/X in the [0:1] interval and Y/X in [-1:1] interval (will be internally mapped to -Y2Xmax : Y2Xmax at given pad-row) can be provided as: 
````
AliTPCDcalibRes* clbn = new AliTPCDcalibRes(run);
//...
float y2x[]={-1.,-0.933,-0.867,-0.800,-0.733,-0.600,-0.466,-0.333,-0.200,-0.067,+0.067,+0.200,+0.33,+0.467,+0.600,+0.733, 0.800, +0.867,0.933, +1.000};
float z2x[]={0., 0.1, 0.2, 0.3,  0.4,0.6,0.8,1.};
int nz = sizeof(z2x)/sizeof(float)-1;
int ny = sizeof(y2x)/sizeof(float)-1;
clbn->SetY2XBinning(ny,y2x);
clbn->SetZ2XBinning(nz,z2x);
//...
clb->Init();
````

Possibility of variable Z/X and Y/X binning

---

EVGEN/AliDecayerExodus.cxx
EVGEN/AliDecayerExodus.h

Histos created in root file TDirectory are deleted at its closing

---

EMCAL/EMCALbase/AliEMCALDigit.h
EMCAL/EMCALbase/AliEMCALDigitizer.cxx

in order to avoid future confusions again reading the code.

Attempt to improve comments in code relative to MC-to-Data embedding 

---

EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx

Corrects the ADC mapping for the TRU objects created here.
This fixes the mapping error observed through trigger patches.
See Ticket [EMCAL-509 ](https://alice.its.cern.ch/jira/browse/EMCAL-509)

Corrects TRU ADC mapping, Fixing Missing Patch issue in Simulation

---

EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx

Fixes an index error in a check for disabled TRUs.

TRU index error Fix

---

STAT/AliTreePlayer.cxx

after losing of the AliRoot at GSI node, and fresh reinstall code sopped to work
some commits were nut pushed to central repository
--> 
C-test to be added to test AliTreePlayer in future

PWGPP-485- bug fix in make histograms

---

ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx

Fix submitting collections for user analysis when creating collections for multiple runs.

Fix a bug in the analysis plugin

---

EVGEN/AliDecayer.h
PYTHIA6/AliPythia6/AliDecayerPythia.cxx
PYTHIA6/AliPythia6/AliDecayerPythia.h
PYTHIA6/AliPythia6/AliGenPythia.cxx
PYTHIA6/AliPythia6/openDecayTable.F

See also:
* https://alice.its.cern.ch/jira/browse/ALIROOT-8313
* https://alice.its.cern.ch/jira/browse/ALIROOT-8322
* https://alice.its.cern.ch/jira/browse/ALIROOT-8301

Prepare v5-09-38d release

---

EVGEN/AliDecayer.h
PYTHIA6/AliPythia6/AliDecayerPythia.cxx
PYTHIA6/AliPythia6/AliDecayerPythia.h
PYTHIA6/AliPythia6/AliGenPythia.cxx
PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx
PYTHIA6/AliPythia6/AliGenPythiaPlus.h
PYTHIA6/AliPythia6/openDecayTable.F

See also
* https://alice.its.cern.ch/jira/browse/ALIROOT-8301 
* https://alice.its.cern.ch/jira/browse/ALIROOT-8313
* https://alice.its.cern.ch/jira/browse/ALIROOT-8322 
* https://alice.its.cern.ch/jira/browse/ALIROOT-8325

Preparation for v5-09-20g

---

EVGEN/AliDecayer.h
PYTHIA6/AliPythia6/AliDecayerPythia.cxx
PYTHIA6/AliPythia6/AliDecayerPythia.h
PYTHIA6/AliPythia6/AliGenPythia.cxx
PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx
PYTHIA6/AliPythia6/AliGenPythiaPlus.h
PYTHIA6/AliPythia6/openDecayTable.F

* https://alice.its.cern.ch/jira/browse/ALIROOT-8313
* https://alice.its.cern.ch/jira/browse/ALIROOT-8322
* https://alice.its.cern.ch/jira/browse/ALIROOT-8325
* https://alice.its.cern.ch/jira/browse/ALIROOT-8301

Preparation for v5-09-24a

---

EVGEN/AliDecayer.h
EVGEN/AliGenMC.cxx
PYTHIA6/AliPythia6/AliDecayerPythia.cxx
PYTHIA6/AliPythia6/AliDecayerPythia.h
PYTHIA6/AliPythia6/AliGenPythia.cxx
PYTHIA6/AliPythia6/openDecayTable.F
PYTHIA8/AliPythia8/AliDecayerPythia8.cxx
PYTHIA8/AliPythia8/AliDecayerPythia8.h

See also:
* https://alice.its.cern.ch/jira/browse/ALIROOT-8301
* https://alice.its.cern.ch/jira/browse/ALIROOT-8313
* https://alice.its.cern.ch/jira/browse/ALIROOT-8322
* https://alice.its.cern.ch/jira/browse/ALIROOT-8325

Preparation for v5-09-02a

---

EVGEN/AliGenParam.cxx
STEER/STEERBase/AliMCEvent.cxx

see https://alice.its.cern.ch/jira/browse/ALIROOT-8334, https://alice.its.cern.ch/jira/browse/ALIROOT-8333

PR to create v5-09-46f

---

EMCAL/EMCALbase/AliEMCALRecParam.cxx
EMCAL/EMCALbase/AliEMCALRecParam.h
EMCAL/EMCALrec/AliEMCALReconstructor.cxx
EMCAL/EMCALrec/AliEMCALReconstructor.h
EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx
EMCAL/EMCALsim/AliEMCALTriggerSTU.cxx
EMCAL/EMCALsim/AliEMCALTriggerSTU.h
EMCAL/EMCALsim/AliEMCALTriggerTRU.cxx
EMCAL/EMCALsim/AliEMCALTriggerTRU.h

see https://alice.its.cern.ch/jira/browse/ALIROOT-8332

PR to create v5-09-24b

---

STAT/AliNDLocalRegression.cxx
STAT/AliNDLocalRegression.h
STAT/AliTreePlayer.cxx
STAT/AliTreePlayer.h

PWGPP-538 = possibility to remove QA informatio to have lighter object
PWGPP-485- adding metaData table to to AliTreePlayer
PWGPP-485- bug fix in make histograms
Modified files:
AliTreePlayer.h, AliTreePlayer.cxx, AliNDLocalRegression.h, AliNDLocalRegression.cxx

 PWGPP-538 -  possibility to remove QA information to have lighter function represrntation

---

STEER/STEER/AliMC.cxx
STEER/STEERBase/AliPDG.cxx

Hi,
I have added the charmed "hyper"nuclei we are discussing in the MC preparation of the ITS3 studies to AliPDG and AliMC.
Cheers,
Benjamin

 Added charmed "hyper"nuclei currently discussed in the ITS3 upgrade

---

STEER/ESD/AliESDpid.cxx
STEER/ESD/AliESDpid.h
STEER/STEER/AliReconstruction.cxx
STEER/STEER/AliReconstruction.h

Hi @shahor02
this is the PR that we were mentioning before with @akalweit. This should be coupled with a PR to AliDPG to be used in production.
Do you think this is good enough?
Thanks!
Cheers,
Max

Support Z=2 nuclei optimised PID for tracking

---

TPC/TPCsim/AliTPCv2.cxx

Alu guard rings added for IFC and OFC

Added Alu guard rings

---

EVGEN/AliGenReadersEMD.cxx

As specified in the subject.
ch.

Updated reader for RELDIS generator fixing a bug reported by Igor

---

EVGEN/AliGenCosmicsParam.cxx
EVGEN/AliGenCosmicsParam.h

I added data members and setters to activate acceptance cut for ITS2 simulations

Update acceptance cuts for ITS2 layers

---

TPC/TPCsim/AliTPCv2.cxx

Corrections in guard rings

---

data/galice.cuts

Switching on delta-ray production inside V0 scintillators.

Update galice.cuts (ALIROOT-8358)

---

data/galice.cuts

Switching on delta-ray production inside V0 scintillators.

[ALIROOT-8358]: Update galice.cuts

---

STAT/AliTreePlayer.cxx
STAT/STATLinkDef.h

+ adding std map for Float_t and Double_t to be able to use in root prompt

PWGPP-565 - remove  \t in the string export in case csv format used

---

EMCAL/EMCALUtils/AliCaloConstants.h
EMCAL/EMCALraw/AliCaloRawAnalyzerFactory.cxx
EMCAL/EMCALraw/AliCaloRawAnalyzerGamma2.cxx
EMCAL/EMCALraw/AliCaloRawAnalyzerGamma2.h
EMCAL/EMCALraw/CMakeLists.txt
EMCAL/EMCALraw/EMCALrawLinkDef.h

EMCAL raw data fitter

---

STEER/STEERBase/AliExternalTrackParam.cxx

@fprino : In fact, there was a room for extra optimization, apart from removing duplicated cs calculation.

Optimization in PropagateToDCA

---

TPC/TPCsim/AliTPCv2.cxx

2. Added the central drum heating strips

1. Joints between the central drum sections revised

---

EVGEN/AliGenReadersEMD.cxx
EVGEN/AliGenReadersEMD.h

@coppedis : this was the reason of the wrong kinematics

Fix: float precision was leading to wrong kinematics

---

STAT/AliNDLocalRegression.cxx
STAT/AliTMinuitToolkit.cxx
STAT/AliTMinuitToolkit.h
STEER/ESD/AliESDUtils.cxx
TPC/TPCbase/AliTPCRecoParam.cxx
TPC/TPCbase/AliTPCRecoParam.h
TPC/TPCbase/AliTPCcalibDB.cxx
TPC/TPCbase/AliTPCclusterMI.cxx
TPC/TPCbase/AliTPCclusterMI.h
TPC/TPCrec/AliTPCReconstructor.cxx
TPC/TPCrec/AliTPCReconstructor.h
TPC/TPCrec/AliTPCseed.cxx
TPC/TPCrec/AliTPCtracker.cxx
TPC/TPCrec/AliTPCtracker.h
TPC/TPCsim/AliTPCDigitizer.cxx
test/configuration/configGSI.sh

Merging ion tail branch into master (after rebase by Ruben https://github.com/shahor02/AliRoot/tree/mi_IT,)
* ion tail _ common mode changes related modification in November-March
* Debug streaming - down-sampling of cluster  - used for tuning of the cluster error parameterization
https://alice.its.cern.ch/jira/browse/PWGPP-570?focusedCommentId=239113&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-239113
* Ion tail - integral scaling 
https://alice.its.cern.ch/jira/browse/PWGPP-570?focusedCommentId=239114&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-239114 
* Write local baseline shift due ion tail and common mode to the clusters:
* https://alice.its.cern.ch/jira/browse/PWGPP-570?focusedCommentId=239115&page=com.atlassian.jira …

PWGPP-570-Merging of the ion tail branch into master 

---

STEER/STEERBase/AliMCEvent.cxx

should fix this: https://alice.its.cern.ch/jira/browse/ALIROOT-8237?focusedCommentId=240932&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-240932

fix: account in GetGenerator for suppressed generators

---

TPC/TPCsim/AliTPCv2.cxx

The first segment is also rotated by 4.6 deg. Hetaing strips re-checked

Corrected central drum geometry 

---

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx

This PR fixes a behaviour that was observed with Pythia8, namley that about 50% of the charm and beauty hadrons did not have a charm (beauty) quark as parent, see https://alice.its.cern.ch/jira/browse/ALIROOT-8371.
This was traced back to the fact that in the tree of particles produced with Pythia8, the hadrons have a first and a second mother, and in 50% of the cases the quark having the same flavour (charm or beauty) of the hadron was the second mother, which is not propagated to the Kine Tree.
With the modification of this PR, a piece of code is added in AliGenPythiaPlus to swap the first and second mother in order to have as first mother the one having the same flavour of the hadron. When this is not possible (very rare cases) the first mother is chosen as the one with higher pdg …

Order by flavour the partons that are first and second mother of a hadron

---

STEER/ESD/AliTrackerBase.cxx
STEER/ESD/AliTrackerBase.h
STEER/STEER/AliReconstruction.cxx
TPC/TPCbase/AliTPCTransform.cxx
TPC/TPCbase/AliTPCTransform.h
TPC/TPCcalib/AliTPCcalibAlignInterpolation.cxx
TPC/TPCcalib/AliTPCcalibBase.cxx
TPC/TPCcalib/AliTPCcalibBase.h
TPC/TPCcalib/AliTPCcalibCalib.cxx
TPC/TPCcalib/AliTPCcalibGainMult.cxx
TPC/TPCcalib/AliTPCcalibTimeGain.cxx
TPC/TPCrec/AliTPCclusterer.cxx
TPC/TPCrec/AliTPCtracker.cxx

See discussion at https://alice.its.cern.ch/jira/browse/ALIROOT-8260?focusedCommentId=242160&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-242160
for details.
Pinging @shahor02 , @miranov25 , @fprino , @catalinristea

Account for BC dependent ALTRO/LHC clocks shift (#1099)

---

EMCAL/EMCALbase/AliEMCAL.cxx
EMCAL/EMCALbase/AliEMCALTriggerData.cxx
EMCAL/EMCALbase/AliEMCALTriggerData.h
EMCAL/EMCALbase/AliEMCALTriggerRawDigitMaker.cxx
EMCAL/EMCALrec/AliEMCALReconstructor.cxx
EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx

Previous interface was written in a completely cryptic
way and ununderstanable for non-experts. Single-letter
variable names were meaningless and do not explain their
purpose. Also from the function names do not expose
their purpose. Allthough the logics is correct this makes
the class hard to use for non-experts
In the new version parameter names were changed. Wherever
the value space corresponds to certain states enumeration
values are used. The new interfaces clearly explain their
purpose.
In addition doxygen comments were added for each function
where the purpose could be extracted easily. With the
new interfaces and the doxygen comments the class should
be self-explaining also for non-expert users.

Human-readable version of the AliEMCALTriggerData

---

EMCAL/EMCALbase/AliEMCALRawDigit.cxx
EMCAL/EMCALbase/AliEMCALRawDigit.h
EMCAL/EMCALbase/AliEMCALTriggerData.h
EMCAL/EMCALbase/AliEMCALTriggerRawDigit.cxx
EMCAL/EMCALbase/AliEMCALTriggerRawDigit.h

In addition improved documentation that actually hints
the meaning of the functions.

Add streaming operators for EMCAL raw digits

---

TFluka/macro/FlukaConfig.C
TFluka/macro/sim.C
TFluka/scripts/runflukageo.sh

updates for fluka2011-3.0 the first CERN release of FLUKA

updates for fluka2011-3.0

---

STRUCT/AliPIPEv3.cxx
STRUCT/AliSHILv3.cxx

Avoid double defined sections in Pcon. 
Created warnings during geometry creation.

Avoid double defined sections in Pcon.

---

TPC/TPCsim/AliTPCv2.cxx

Corrected radii of the IFC guard rings.

Corrected radii of the IFC guard rings (they were erronously swapped)

---

TPC/TPCbase/AliTPCChebCorr.h

Fix for the problem discussed in https://alice.its.cern.ch/jira/browse/ALIROOT-8418?focusedCommentId=245179&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-245179

Protection agains Distortion RMS paramet. < 0

---

ITS/ITSsim/AliITSv11GeometrySDD.cxx
ITS/ITSsim/AliITSv11GeometrySDD.h
ITS/ITSsim/AliITSv11GeometrySPD.cxx
ITS/ITSsim/AliITSv11GeometrySupport.cxx

See https://alice.its.cern.ch/jira/browse/ALIROOT-8260?focusedCommentId=246123&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-246123

Changes for ITS geometry and material by M. Sitta

---

STEER/STEERBase/AliStack.cxx

Needed for ALIROOT-8423, ALIROOT-8425

PushTrack(..., Float* pmom ...): calculate energy in double precision

---

STAT/AliTreePlayer.h
STEER/CDB/AliOCDBtoolkit.cxx
STEER/CDB/AliOCDBtoolkit.h
STEER/STEERBase/AliTPCPIDResponse.cxx
STEER/STEERBase/AliTPCPIDResponse.h

https://alice.its.cern.ch/jira/browse/ALIROOT-8420?focusedCommentId=248871&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-248871

PWGPP-592 - AliOCDBtoolkit::DumpOCDB - TGrid::Connect if alien:// file requested

---

EMCAL/EMCALbase/AliEMCALTriggerSTUDCSConfig.cxx
EMCAL/EMCALbase/AliEMCALTriggerSTUDCSConfig.h
EMCAL/EMCALbase/AliEMCALTriggerTRUDCSConfig.cxx
EMCAL/EMCALbase/AliEMCALTriggerTRUDCSConfig.h

Provide specification consisting of parameter explanation,
use case, and supported value range to getter / setter
functions.

Provide clear specification for function parameters

---

TPC/TPCrec/AliTPCtracker.cxx

* preparation for the PbPb LHC15o 
* should reduce dEdx problem in pPb LHC16xxx

ALIROOT-8439 - adding systematic error only after rescalling

---

EVGEN/AliGenExtFile.cxx
EVGEN/AliGenExtFile.h
PYTHIA6/AliPythia6/AliGenPythia.cxx
STEER/STEER/AliGenerator.cxx
STEER/STEER/AliGenerator.h

Implementation of a trigger function to select generated events. The method can be set directly by the user from the lego train interface and it can be used with external generators (e.g. JEWEL) or with AliRoot internal generators (e.g. PYTHIA).

User trigger implementation to select generated events 

---

STEER/macros/GetStartAndEndOfRunTimestamp.C

- This is useful for O2 analysis scheme of CCDB object retrieval
@jgrosseo

Add macro to get start and end timestamps of runs

---

EVGEN/AliGenPileup.cxx

This modification is needed for the separate simulation of trigger event

Fix in initialization of last particle in the stack

---

STAT/AliTreePlayer.cxx
STEER/ESD/AliESDTOFMatch.h
STEER/STEERBase/AliITSPIDResponse.cxx
STEER/STEERBase/AliITSPIDResponse.h
STEER/STEERBase/AliPIDResponse.cxx
STEER/STEERBase/AliPIDResponse.h
TOF/TOFrec/AliTOFtracker.cxx
TOF/TOFrec/AliTOFtracker.h
TRD/TRDbase/AliTRDReconstructor.h
TRD/TRDbase/AliTRDtrackerV1.cxx
TRD/TRDbase/AliTRDtrackerV1.h

This is a  pull request  for TRD/TOF tracking information for ML based cleaning.
After discussion with Ruben we agreed to make pull request, so he can make code review.
There are 2 aspects missing and 2 wish list.
- TOF hit compression of non associated hits to be disabled
- ITS interpolateMomentum should be used as a flag
- TRD High voltage flags
- drift,gain
- TRD interpolated Kalman in+out  to be used for the material budget and position estimation

PWGPP-426  - TRD/TOF tracking information for ML based cleaning

---

THijing/AliGenHijing.cxx
THijing/AliGenHijing.h

Added a function in AliGenHijing to (optionally) change Pz sign.

Added function in AliGenHijing to change Pz sign

---

EVGEN/AliGenExtFile.cxx
STEER/STEER/AliGenerator.cxx

Pinging @fprino , @gconesab , @catalinristea, @lucamicheletti93 , for information.

Fix for use of offline trigger

---

EVGEN/AliGenExtFile.h
PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx
STEER/STEER/AliGenerator.cxx
STEER/STEER/AliGenerator.h

User trigger added to AliGenPythiaPlus.cxx and fix of the function streaming issue

User trigger implementation for PYTHIA8

---

PYTHIA8/pythia8243/src/Ropewalk.cc

See discussion in JIRA
https://alice.its.cern.ch/jira/browse/ALIROOT-8488
needed for
https://alice.its.cern.ch/jira/browse/ALIROOT-8533

Patch for floating point exception in Ropewalk.cc (by C.Bierlich)

---

FIT/FITsim/AliFITv8.cxx

Fix overlap between FT0 radiators and FV0 support

fixed overlap

---

T0/T0base/AliT0Digitizer.cxx

use hits only from given interval

---

STAT/TStatToolkit.cxx

* using reasonable for fit ranges
* set initial range of the fit fuction to histogram range
* adding NDF of the  to the output stream
* Bug fix - Normalization of the chi2 to NDF

ATO-520 - BUG fixex + make default setting working

---

STEER/AOD/AliAODCaloTrigger.cxx
STEER/AOD/AliAODCaloTrigger.h
STEER/ESD/AliESDCaloTrigger.cxx
STEER/ESD/AliESDCaloTrigger.h
STEER/STEERBase/AliVCaloTrigger.cxx
STEER/STEERBase/AliVCaloTrigger.h

- Add documentation about the definition of the
median array - this is crucial for user to understand
which median value to use in the background
subtraction for either of the two subdetectors
- Fix indentation to 2 spaces

[doxygen] Add documentation and fix formatting

---

STEER/STEERBase/AliTPCPIDResponse.cxx

To allow for forward and backward compatibility between root 5 and root 6, the sigma parametrization function is initialized now from a string for the function definition and a TVectorD for the fit parameters.
Function and parameters are set via an input file to the
MakeTPCPIDResponseOADB macro.

Modifications to initialize TF1 from string and TVectorD

---

EMCAL/EMCALbase/AliEMCALSimParam.cxx
EMCAL/EMCALbase/AliEMCALSimParam.h
EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx
EMCAL/EMCALsim/AliEMCALTriggerElectronics.h
EMCAL/EMCALsim/CMakeLists.txt

Updates SimParams, adding L1ADCNoise param
Adds noise to L1 trigger timesums based on param in SimParam OCDB

Adds noise to EMCal L1 Trigger set via SimParams

---

TPC/TPCbase/AliTPCCalROC.h
TPC/TPCsim/AliTPC.cxx

Fix for https://alice.its.cern.ch/jira/browse/ALIROOT-8641?focusedCommentId=262413&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-262413

Protect AliTPCCalROC::GetValue by IsNaN, suppress similar protection in AliTPC

---

TDPMjet/DPMcommon.h
TDPMjet/TDPMjet.cxx

- Corrections in DPMcommon.h
- Correction in TDPMjet.cxx to make it work for A-A and p-A

Fixes from A.Morsch:

---

EVGEN/AliDecayer.h
PYTHIA8/AliPythia8/AliDecayerPythia8.cxx
PYTHIA8/AliPythia8/AliDecayerPythia8.h

Add option to force Omegac0 -> Omega+e+nu_e decay, which is needed for D2H MC production

Add option for semileptonic decay of Omegac0

---

PYTHIA8/AliPythia8/AliTPythia8.cxx

Fix Omega_c lifetime in PYTHIA8 according to PDG2020

Fix Omega_c lifetime in PYTHIA8 according to PDG2020

---

ANALYSIS/ANALYSISalice/AliAnalysisTaskPIDResponse.cxx
ANALYSIS/ANALYSISalice/AliAnalysisTaskPIDResponse.h
STEER/STEERBase/AliPIDResponse.cxx
STEER/STEERBase/AliPIDResponse.h

Create possibility in AliPIDResponse and AliAnalysisTaskPIDResponse to force a given OADB path instead getting it form AliDataFile::GetFileNameOADB.

Add small AliPIDResponse functionality

---

STEER/AOD/AliAODv0.cxx

@fprino , @noferini .
This is the tag for MC anchored to 18q/r pass3.

Fix memory leak in AliAODv0 constructor

---

ITS/ITSsim/AliITSv11.cxx
ITS/ITSsim/AliITSv11.h
ITS/ITSsim/AliITSv11GeometrySDD.cxx
ITS/ITSsim/AliITSv11GeometrySPD.cxx
ITS/ITSsim/AliITSv11GeometrySSD.cxx
macros/Config_ITSdens.C

Same as https://github.com/alisw/AliRoot/pull/1406, for v5-09-54, used for MC anchored to 18q/r pass3.
@noferini , @mario6829

Scale mat density v5 09 54

---

ITS/ITSsim/AliITSv11.cxx
ITS/ITSsim/AliITSv11.h
ITS/ITSsim/AliITSv11GeometrySDD.cxx
ITS/ITSsim/AliITSv11GeometrySPD.cxx
ITS/ITSsim/AliITSv11GeometrySSD.cxx
macros/Config_ITSdens.C

Same as https://github.com/alisw/AliRoot/pull/1406, for v5-09-55, used for MC anchored to 15o pass2.
@noferini , @mario6829

Scale mat density v5 09 55

---

ITS/ITSsim/AliITSv11.cxx
ITS/ITSsim/AliITSv11.h
ITS/ITSsim/AliITSv11GeometrySDD.cxx
ITS/ITSsim/AliITSv11GeometrySPD.cxx
ITS/ITSsim/AliITSv11GeometrySSD.cxx
macros/Config_ITSdens.C

@mario6829 , @noferini 
If you agree, I would merge. This is the tag for pp.

Scale mat density

---

ITS/ITSsim/AliITSv11.cxx
ITS/ITSsim/AliITSv11.h
ITS/ITSsim/AliITSv11GeometrySDD.cxx
ITS/ITSsim/AliITSv11GeometrySPD.cxx
ITS/ITSsim/AliITSv11GeometrySSD.cxx
STEER/AOD/AliAODv0.cxx
macros/Config_ITSdens.C

@catalinristea @noferini  @gconesab

[ALIROOT-8790] mat budget changes + fix in AOD for v5-09-02-patches

---

ITS/ITSsim/AliITSv11.cxx
ITS/ITSsim/AliITSv11.h
ITS/ITSsim/AliITSv11GeometrySDD.cxx
ITS/ITSsim/AliITSv11GeometrySPD.cxx
ITS/ITSsim/AliITSv11GeometrySSD.cxx
STEER/AOD/AliAODv0.cxx
macros/Config_ITSdens.C

@catalinristea @noferini @gconesab

[ALIROOT-8790] mat budget changes + fix in AOD for v5-09-38-patches

---

ITS/ITSsim/AliITSv11.cxx
ITS/ITSsim/AliITSv11.h
ITS/ITSsim/AliITSv11GeometrySDD.cxx
ITS/ITSsim/AliITSv11GeometrySPD.cxx
ITS/ITSsim/AliITSv11GeometrySSD.cxx
STEER/AOD/AliAODv0.cxx
macros/Config_ITSdens.C

@catalinristea @noferini @gconesab

[ALIROOT-8790] mat budget changes + fix in AOD for v5-09-20-patches

---

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx
PYTHIA6/AliPythia6/AliGenPythiaPlus.h

Possibility to select trigger particle in asymmetric eta range

---

EVGEN/AliDecayer.h
MUON/MUONbase/AliMUONDigitStoreV1Iterator.cxx
PYTHIA8/AliPythia8/AliDecayerPythia8.cxx

Port to v5-06-patches "Fix for Fix for Root v6-26"  and "Implementing settings for MC Omegac0"

---

EVGEN/AliDecayer.h
PYTHIA6/AliPythia6/AliDecayerPythia.cxx

- fix for eta prime decays to force eta to decay to gamma gamma
- separate setting for EtaPrime to GammaGamma decay

AliDecayerPythia: re-write of forced EtaPrime decays

---

PYTHIA8/AliPythia8/AliDecayerPythia8.cxx

Add the 4body decay mode for the Xic0 semileptonic simulation

MC option for Xic0 semileptonic mode

---

PYTHIA8/AliPythia8/AliDecayerPythia8.cxx
STEER/STEER/AliMC.cxx
STEER/STEERBase/AliPDG.cxx

Needed for coming MC productions and in particular for ALIROOT-8813

Port from master updates in hyper nuclei, omegaC and Xic and exaquark

---

STEER/STEERBase/AliPDG.cxx

Fixing wrong charges added in commits:
https://github.com/alisw/AliRoot/commit/8ff209d4372162d79b02c86dbfb4c41fc8595177
https://github.com/alisw/AliRoot/commit/d3df3965d473189007440b8a7e4d36f2905c8bc3
partially because of wrong ROOT documentation,
which was fixed later in https://github.com/root-project/root/commit/6a82edd615f1284f2de238bab195a
but not propagated to AliRoot.

Fix PDG charges (after 20 years)

---

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx
PYTHIA6/AliPythia6/AliGenPythiaPlus.h

This PR add possibility to swap D mesons with D meson resonances

Adding D meson to D meson resonance swap option

---

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx
PYTHIA6/AliPythia6/AliGenPythiaPlus.h

Needed by https://alice.its.cern.ch/jira/browse/ALIROOT-8847

Port Adding D meson to D meson resonance swap option  PR #1475 to V5 09 56 patches

---

PYTHIA6/AliPythia6/AliGenPythia.cxx

Adding selection on the child for powheg processes for AliGenPythia

PWG DQ: adding selection on the child for powheg processes for AliGenPythia

---

EVGEN/AliDecayer.h
PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx
PYTHIA8/AliPythia8/AliDecayerPythia8.cxx
PYTHIA8/AliPythia8/AliDecayerPythia8.h

Port Forcing Ds-resonances  hadronic decay; Fixing track transport of D to v5-09-56-patches

---

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx

Add width of Ds resonances

---

EVGEN/AliGenSexaquarkReaction.cxx
EVGEN/AliGenSexaquarkReaction.h
EVGEN/CMakeLists.txt
EVGEN/EVGENLinkDef.h

Injector of the products of AntiSexaquark-Nucleon interactions
- anti-sexaquark kinematics under a flat distribution
- radius of secondary vertex chosen from a flat distribution
- struck nucleon's Fermi momentum assigned with a simple gaussian
Based on [**AliGenBox**](https://github.com/alisw/AliRoot/blob/master/EVGEN/AliGenBox.cxx).

Created AliGenSexaquarkReaction

---

GPU/GPUTracking/TRDTracking/GPUTRDInterfaces.h

Fix unneeded specialization

---

EVGEN/AliGenSexaquarkReaction.cxx

- momentum distributions for Fermi motion are now flat

v5-09-54-patches fis bug fixes: phi range now in correct units, and

---

PYTHIA8/AliPythia8/AliDecayerPythia8.cxx
PYTHIA8/AliPythia8/AliDecayerPythia8.h

This reverts commit fb5bd00240875256f597e7661e03b33604f31ffa.

Revert "Update AliDecayerPythia8.cxx (#1511)"
