.gitignore
It would be good to add .settings in .gitignore. Eclipse users will find it beneficial since it creates this directory automatically.
=> Add .settings in .gitignore

STAT/AliTMinuitToolkit.cxx, STAT/AliTMinuitToolkit.h, STAT/test/AliTMinuitToolkitTestLinear.C
* *Bootstrap*
* *MISAC* (proper name to me foud) method is mixed of approaches
*  M-estimator with user defined log likelihood function
*  RANSAC (Random sample consensus)
*  Hough transform (finding peak in paremteric space)
* More details - https://alice.its.cern.ch/jira/browse/ATO-410
* Example usage for interactive session
```
AliTMinuitToolkit *  AliTMinuitToolkit::Fit(TGraph *graph, const char *fitterName, Option_t* option, Option_t* goption,  Option_t* foption, Double_t xmin, Double_t xmax);
AliTMinuitToolkit*fitter2 = AliTMinuitToolkit::Fit(gr,"pol1","default", "", "funOption(1,3,1)");  // standard minuit
AliTMinuitToolkit*fitter3 = AliTMinuitToolkit::Fit(gr,"pol1R","", "", "funOption(2,3,1)"); // logLike:gaus+cauchy
AliTMinuitToolkit*fitter4 = …
```
=> ATO-410 - ADD: Fitting methods for robust fitting and error estimation

STAT/AliTMinuitToolkit.cxx, STAT/AliTMinuitToolkit.h, STAT/test/AliTMinuitToolkitTestLinear.C
* In the AliTMinuitToolkit I needed n dimensional functional representation. Therefore I used the TFormula (generic ND I patched in ROOT ~ 13 year ago) instead of the TFx
* In user interface of drawing I need however TFx as the TFormula (in ROOT5) can not be drawn.
* In ROOT6 TF1 does not inherit from TFormula - therefore compilation breaks
* Replace TFormula with TF1
* !!!! Fix does not works for multidimension. Proper fix to be done soon
=> ALIROOT-7174, ATO-410-In ROOT6 TF1 does not inherit anymore from TFormula

STEER/STEER/AliMC.cxx
If we have particles with the same name twice, Geant4 produces fatal exception:
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : PART122
issued by : G4ParticleTable::Insert()
The particle Ps_2100  has already been registered in the Particle Table 
*** Fatal Exception *** core dump ***
-------- EEEE -------- G4Exception-END --------- EEEE -------
=> Distinguish particle/anpiparticle names (Geant4)

TPC/TPCbase/AliTPCTransform.cxx, TPC/TPCbase/AliTPCTransform.h
Same threshold for the excess of run-specific distortion dispersion wrt reference one will be used to interpret
it as distortion fluctuation in simulation and reconstruction. Default 300um, can be modified via static setter SetDistDispThreshold.
Used value is reported in the log by UpdateTimeDependentCache
=> use same settable (Def:300um) threshold for dist. fluctuations

ITSMFT/ITS/itsuTestBench/rec.C, ITSMFT/ITS/itsuTestBench/sim.C, ITSMFT/ITS/rawconv/PixConv.h, ITSMFT/ITS/rawconv/digits2raw.C
1) Use $ALICE_ROOT_OCDB as default local OCDB
2) Eliminate ITSUDigit... frome headers, now ITS and MFT use common digits.
=> Fixes to make the ITSU test work after ITS+MFT->ITSMT and migration to github migration

EMCAL/EMCALbase/AliEMCALDigit.cxx, STEER/STEERBase/AliMCEvent.cxx
1) AliMCEvent::GetParticleAndTR was not aware of subsidiary events
2) EMCAL was applying wrong offset for bg.gigit flagging (10M offset was multiplied by another 10M)
=> Additional fixes for MC-to-MC embedding

ANALYSIS/ANALYSISalice/AliESDv0KineCuts.cxx
This is a modification to prevent a crash that was spotted in rare case when running AliAnalysisTaskPIDqa in the QA train.
This crash occurs in the calculation of an arc-cosine inside the method AliESDv0KineCuts::Armenteros: in rare cases the argument of the acos function goes out of the [-1,1] range, due to numerical fluctuations. 
The modified code computes the relevant variables without using acos.
=> Avoid usage of acos in calculation of Armenteros variables

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx
removed since it overwrites the settings of the standard tunes
=> fPythia->SetIntrinsicKt(fPtKick);

ITSMFT/MFT/MFTbase/AliMFTHalfCone.cxx
The half MFT cone is modified to avoid overlap with the MFT disks (some parts of the half cone are reduced in size to fit with the heat exchanger)
=> Solved overlap issues

MUON/mchview/mchview.cxx
The TGrid::Connect was misplaced and was executed whatever the given ocdbPath was...
=> Allow to work completely offline.

AD/ADrec/AliADReconstructor.cxx
The recent fix breaks the compilation with Root6, so I switched off the method Optimize. It is not available in Root6.
=> No method Optimize in Root6

STAT/AliTMinuitToolkit.cxx, STAT/AliTMinuitToolkit.h, STAT/test/AliTMinuitToolkitTest.C, TPC/TPCcalib/AliTPCDistortionFit.cxx, TPC/TPCcalib/AliTPCDistortionFit.h
ATO-405,ATO-336 - Physics model fit TB -https://indico.cern.ch/event/605126/
* Extended intefrace for fitter filling using TTree (doReset)  
* One line fit working version
* used in TB presentation     
* https://indico.cern.ch/event/605126/contributions/2538484/attachments/1441002/2218550/DistortionAnalitycalModelsForTB_06042017_v2.pdf
* Multi line fit implemented but not (yet)  converging ...
* to be finished
* bug fix from previous commit
* forgotten continue
=> ATO-405, ATO-410 - change: related to NDim. fits

STEER/STEERBase/AliMagWrapCheb.h
With #define _USE_FAST_ATAN2_ in the STEER/STEERBase/AliMagWrapCheb.h an approximate and fast atan2 function will be used. For solenoid field this speeds up the query by ~40% on expense of ~10^-4 error (to be compared with a few * 10^-3 precision of our field)
=> Use approx. fast atan2 -> speed-up by 40% in solenoid

HLT/TPCLib/AliHLTTPCHWCFData.h, HLT/TPCLib/HWCFemulator/AliHLTTPCHWCFDataTypes.h, HLT/TPCLib/HWCFemulator/AliHLTTPCHWCFDivisionUnit.cxx, HLT/TPCLib/HWCFemulator/AliHLTTPCHWCFMergerUnit.cxx, HLT/TPCLib/HWCFemulator/AliHLTTPCHWCFPeakFinderUnit.cxx, HLT/TPCLib/HWCFemulator/AliHLTTPCHWCFProcessorUnit.cxx, SHUTTLE/AliShuttleConfig.h, TPC/TPCrec/AliTPCtracker.cxx
Modifications:
- Fix in TPC tracker to use non-zero covariance estimate for tracks whose seed starts with single-pad cluster.
- Implement improved edge correction in HLT HWCF for studying clusterizer performace.
- Minor patches from Heiko to HLT HWCF emulator.
- Fix in privacy of nested shuttle classes to enable compilation with GCC 5 and newer and CINT.
- Fix some code indentation and comments
=> Merge Patches to TPC tracker and to HLT HWCF emulator for next study of HLT clusterizer performance

AD/ADrec/AliADReconstructor.cxx
Adding check of the existence of pointer
We are running ITS/TPC/TRD reconstruction benchmark for the LHC15l period with current master  (one day old) (git describe v5-07-20-2281-g023c8b0)
* Out of 370 jobs, 290 jobs failed (see benchmark stacktrace histogram and csv/tree file attached).
* Out of them 220 jobs failed in the AliADReconstructor.
* Not sure if the problem is because of missing check or some memory overweite - but to be sure I added pointer checks 
```
if (fCorrectForSaturation ) {
f_Int0->Delete(); // TF1 does not implement TObject::Clear()
f_Int1->Delete();
}
```
=> PWGPP-292- Check pointers before deleting

AD/ADrec/AliADReconstructor.cxx
The ADReconstruction was crashing because the TClonesArray was created w/o specifying the class
it is going to handle, delegating this to tree->GetEntry with branch address set to the array.
But for events when the tree was not read the class was not set and TClonesArray::Delete() was trying to
dereference TClonesArray::fClass w/o checking if it is defined.
=> Fix: TClonesArray must know the class it handles

STAT/STATLinkDef.h, TPC/TPCcalib/AliTPCDistortionFit.cxx
* Use field polarity in the fit
* modification for drawings (to enable  macro compilation)
* Used for caching of the MC track references and AliHelix in $AliPhysics_SRC/PWGPP/AliMCTreeTools.cxx
=> Add: Use field polarity in the space charge fit

AD/ADrec/AliADQADataMakerRec.cxx, AD/ADrec/AliADQADataMakerRec.h
I removed all charge and time channel-channel correlation histograms. The was bunch of them, they were used only during the first commissioning.
=> Removing obsolete histograms

EVGEN/CMakeLists.txt
for some reason this was not necessary 
- on OSX: ROOT 5.34/30 (heads/v5-34-00-patches@v5-34-28-57-gec27989, Mar 23
2017, 14:28:00 on macosx64), and
- on lxplus7: ROOT v5-34-30-alice7-2
and only showed up when @ekryshen tested AliGenReaderLHE on CentOS7
=> added missing dependency XMLIO

ITS/ITSbase/AliITSQASDDDataMakerRec.cxx, ITS/ITSbase/AliITSQASDDDataMakerRec.h
This modification is needed to have in the DQM report the plot of the SDD data size.
Two obsolete data members were removed
=> Remove the online flag from data size plot + code cleanup

STEER/STEERBase/AliStack.cxx
To keep track of the number of particles transported by geant
=> Log information on N transported and N kept tracks

STEER/AOD/AliAODMCParticle.h, STEER/STEERBase/AliMCEvent.cxx, STEER/STEERBase/AliMCParticle.cxx, STEER/STEERBase/AliMCParticle.h, STEER/STEERBase/AliVParticle.h
I have added to AliVParticle the common methods defined in AliMCParticle and AliAODMCParticle, plus a few more. In doing so would be able to get access the MC information from an analysis task in the same way for ESDs and AODs just doing
AliVParticle* particle = MCEvent()->GetTrack(label)
and replacing AliMCParticle and AliAODMCParticle in the analysis tasks.
Few minor remarks:
* GetStatus() -> There is a different definition in AliVTrack and Ali*Particle, in one it is an Int and in other a long. I have added MCStatusCode() for the MC information
* GetDaughter() -> There is already a method called like that in AliAODRecoDecay returning non int objects, so I renamed if for the recovery of the MC labels as GetDaughterLabel
* T() -> In AliAODTrack there is a template of something with this …
=> Include common methods to AliAODMCParticle and AliMCParticle in AliVParticle for common access of ESD/AOD MC information

CMakeLists.txt
The ctest runs a series of load-libraries commands that are stored in the root history.
Since there are lots of libraries, the user history basically goes outside the buffer.
The patch disable the root history before loading the libraries.
=> Disable root history when performing ctest

PHOS/DA/PHSPEDda.cxx
This bug sometimes caused a crash in the pedestal runs.
=> Reading from STU DDL abandoned in a loop over data sources.

STEER/ESD/AliESDv0.cxx
* Use AliSysInfo (syswatch.log) to indicate memory usage
* stamp after each histogram creation
* stamp after each chunk processing
* Print Memory usage in stdout
* after each histogram creation and total size
=> PWGPP-312 - Bug fix: Memory leak

STARLIGHT/AliGenFlat2Trk/AliGenFlat2Trk.cxx, STARLIGHT/AliStarLight/AliGenStarLight.cxx, STARLIGHT/starlight/TStarLight/TStarLight.cxx, STARLIGHT/starlight/TStarLight/TStarLight.h, STARLIGHT/starlight/include/gammaavm.h, STARLIGHT/starlight/include/inputParameters.h, STARLIGHT/starlight/src/gammaavm.cpp, STARLIGHT/starlight/src/inputParameters.cpp
- b-slope parameterization is made configurable:
```
BSLOPE_DEFINITION = 0 -> default
BSLOPE_DEFINITION = 1 -> user defined: using BSLOPE_VALUE 
BSLOPE_DEFINITION = 2 -> use the H1 parameterization
BSLOPE_DEFINITION = 3 -> NEW: the H1 parameterization parameters are configurable, e.g.,                                                                                                         
BSLOPE0           = 4.36                                                                                   
BSLOPE_ALPHAPRIME = 0.164
```
- using SafeDelete(X) (code becomes shorter)
=> STARLIGHT b-slope parameterization is made configurable

STAT/AliDrawStyle.cxx, STAT/AliDrawStyle.h, STAT/CMakeLists.txt, STAT/STATLinkDef.h, doxygen/Doxyfile.in
* Several drawing styles can be regeistered and used in the same moment
* Styles are identified using strings as identifiets
* TStyle
* MarkerStyle[]  AliDrawStyle::GetMarkerStyle(const char *style, Int_t index);
* MarkerColors[] AliDrawStyle::GetMarkerColor(const char *style, Int_t index)
* FillColors[]   AliDrawStyle::GetFillColor(const char *style, Int_t index); 
* Default styles are created  AliDrawStyle::SetDefaults()
* default style is based on the fig template -https://twiki.cern.ch/twiki/pub/ALICE/ALICERecommendationsResultPresentationText/figTemplate.C
* users should be able to regiester their oun styles (e.g in macros)
* TCanvas and TPad formatting  styles (functionality similar to AliCanvas)
* performance reports -  with styles as a parameter 
* QA reports
* AliTreePlayer, and …
=> PWGPP-312 - Add: AliDrawStyle class to register drawing styles

EMCAL/EMCALbase/AliEMCALPreprocessor.cxx, EMCAL/EMCALbase/AliEMCALTriggerDCSConfig.cxx, EMCAL/EMCALbase/AliEMCALTriggerSTUDCSConfig.cxx, EMCAL/EMCALbase/AliEMCALTriggerSTUDCSConfig.h
1. EMC pre-processor must look also for {E/D}MC_STU_PATCHSIZE and {E/D}MC_STU_MEDIAN aliases
and then these must be written in AliEMCALTriggerSTUDCSConfig.
2. The array length for STU ERROR counts must be 67 for EMCAL and 55 for DCAL.
3. The format of these aliases must be {E/D}MC_STU_ERROR_COUNT_TRU01,
{E/D}MC_STU_ERROR_COUNT_TRU02,… instead of currently used {E/D}MC_STU_ERROR_COUNT_TRU1,
{E/D}MC_STU_ERROR_COUNT_TRU2,…
4. Increase ClassDef of class AliEMCALTriggerSTUConfig as data members were added.
(Martin)
=> Adapting preprocessor to the changes in the amanda server

STAT/AliDrawStyle.cxx, STAT/AliDrawStyle.h
* small changes in latex labels
* array of marker size adjustable
* part of the style (different markers can have different default size) parameter in style
* Add: TRD inspired figure style figTemplateTRD and figTemplateTRDPair
* I misunderstood original message from Dario to do not approve pull request
* In meantime I implemented extension of AliDrawStyle class
* adding line width and marker size array as part of style
* Merged version - removing all white spaces at the end of lines
=> PWGPP-312- Add: marker size and line width as part of style

TPC/TPCrec/AliTPCtrack.cxx, TPC/TPCrec/AliTPCtrack.h
Matrix used in the very beginning of the Kalman fit can set via pointer
obtained by static AliTPCtrack::GetMatLarge. The last, 16th element of the 
array is optional additive term to q/pt error fC[14]
=> possibility to modify seed initial cov.matrix

ITS/ITSbase/AliITSClusterFinderV2SSD.cxx
This modification was developed and tested with the SSD team.
=> Switch off strips of OCDB/BadChannelsSSD in the cluster finder 

STAT/AliDrawStyle.cxx, STAT/AliTreePlayer.cxx
* title size and labels font size (non linear font size scaling)
* 2x2 pads  - "figTemplate2"
* 3x3 pads- "figTemplate3"
*  use only valin C++ names (letters and numbers)
=> ATO-418 - Add: adopt format for the multi-pad canvas

STAT/AliExternalInfo.cxx, STAT/AliExternalInfo.h
* loop over master production table  ( cvs version of https://alimonitor.cern.ch/production/raw.jsp )
* querying caching information for each productions ()
* new trees:
```
+  TTree*  GetTreeAliVersRD();
+  TTree*  GetTreeAliVersMC();
+  TTree*  GetTreeMCPassGuess();
+  TString GetMCPassGuess(TString MCprodname);
```
* Example usage in https://alice.its.cern.ch/jira/secure/EditComment!default.jspa?id=28255&commentId=196511
* some extension expected -  - indication of faulures of "anchor guess"
* export ot eh Mc table, resp. to Elastc
```
TTree * tree = info.GetTreeMCPassGuess()
tree.GetListOfBranches().ls()
OBJ: TObjArray  TObjArray       An array of objects : 0
OBJ: TBranch   aliroot root/C : 0 at: 0x3211560
OBJ: TBranch   aliphysics      phys/C : 0 at: 0x320dca0
OBJ: TBranch   prodName …
```
=> ATO-46 - Add cache of the MC and raw data production trees 

STAT/AliExternalInfo.cxx, STAT/AliTreePlayer.cxx
Needed for compilation under ROOT6.
=> Add missing using namespace std

MUON/MUONcalib/AliMUONBusPatchEvolution.cxx
Run 0 triggers reading from (most probably non-existing) local OCDB.
Use a large number instead to get the latest run available for the
period at hand (in cvmfs case) or any period (in raw:// case).
=> ALIROOT-7286 Avoid 0 as default run number to access mapping from OCDB.

STEER/AOD/AliAODHandler.cxx, STEER/STEERBase/AliMCEvent.h
+ when reporting wrong TOF label show the AODtrack label for consistency check
=> make GetNPrimaries method const

HIJING/hijing1_36/hijhrd.F, HIJING/hijing1_36/hijing.F, HIJING/hijing1_36/vegas.F, THijing/AliGenHijing.cxx, THijing/AliGenHijing.h
Patch makes possible to disable adhoc energy conservation
and allows the number of misses to be set in hijhrd.f
The settings are propagated via IHPR2(31) and (30) using
the function AliGenHijing::SetEconv(Bool_t ec, Int_t nmiss=50).
The patch also removes annoying print outs to fort.16 and fort.8
=> Hiing econv

STEER/CDB/AliCDBLocal.cxx, STEER/CDB/AliCDBLocal.h, STEER/CDB/AliCDBManager.cxx
This feature is required for accessing the OCDB from CVMFS expecially during the
MC release validation. OCDB is automatically accessed from there, if:
* `AliCDBManager::SetDefaultStorage("raw://")`
* and environment variable `OCDB_PATH` is set to a proper CVMFS path, e.g.
/cvmfs/alice-ocdb.cern.ch
Run mapping to the correct folder is performed the same way as on AliEn, by
using the same XML mapping file. Mapping is not performed in case
`SetDefaultStorage` is set to a specific directory.
Those changes are backwards-compatible: the previous behaviour is unchanged in
case the `OCDB_PATH` variable is not exported. CVMFS OCDB must be enabled
explicitly.
=> Enable optional CVMFS OCDB usage

AD/ADsim/AliAD.cxx, AD/ADsim/AliADv1.cxx, AD/ADsim/AliADv1.h, STRUCT/AliDIPOv2.cxx, STRUCT/AliDIPOv2.h, STRUCT/AliPIPEv3.cxx, STRUCT/AliPIPEv3.h
* Corrected Dipole geometry for ADA (2017)
* Ovalized Beam Pipe (RB242) inside Dipole
* A-Side: Shielding for PM's, I-Beam and other beam-pipe supports, OldAD, BLM's, support for Warm Module
* C-Side: Grid of U-Profiles near the wall that separates CAVERN from LHC tunnel
supercedes #234.
=> Geometry updates for AD

T0/T0base/AliT0CalibTimeEq.cxx
This is to silence annoying ``E-TObjArray::operator[]: index 16 out of bounds...`` errors, the bug itself was malign
=> Do not fill with 0s freshly create TObjArray

T0/T0rec/AliT0CalibSeasonTimeShift.cxx
The non-initialized variable was incremented in loop and used as the size of TGraph, potentially the reason of v5-09-09 failure: https://alice.its.cern.ch/jira/browse/ALIROOT-7321?focusedCommentId=197457&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-197457
=> Fix of non-initialized var. + memory leak

STAT/AliDrawStyle.cxx, STAT/AliDrawStyle.h, STAT/AliElasticSearchRoot.cxx, STAT/AliElasticSearchRoot.h, STAT/CMakeLists.txt, STAT/Macros/AliElasticSearchRootTest.c, STAT/STATLinkDef.h
* AliElasticSearchRoot - C++ interface to the Elastic --> root tree like-   using gSystem->GetFromPipe, Exec, Elastic, painless scripting,  curl,  jq
* Originally planned usage of  higher level C++ interface not possible for a moment
* C++11 or better C++14 and ROOT6 needed (e.g https://github.com/QHedgeTech/cpp-elasticsearch/tree/master/src )
* Using older  C++  and Root 5 to represent hierarchical structure root trees to be used
* Query language similar to TTree::Draw  - suing elastic painless scripting language (see query examples)
```c++
hostName="localhost:9200";            // local elastic
// or remote ElastichostName="https://localhost:9206";    //  connect to remote via tunnel e.g ssh mivanov@lxplus.cern.ch -f -N -L 9206:es-alice.cern.ch:9203
//
AliElasticSearchRoot …
```
=> ATO-402- Add: class AliElasticSearchRoot 

EVE/EveBase/AliEveSaveViews.cxx, EVE/EveBase/AliEveSaveViews.h
Fixes char* -> const char* for string literal in header which otherwise gives plenty of warning messages.  Can you comment @jniedzie ?
=> EVE: char* -> const char* fix in header

STEER/STEERBase/AliMCEvent.cxx, STEER/STEERBase/AliStack.cxx, STEER/STEERBase/AliStack.h
The MCEvent::AddSubsidiaryEvent will also
set the flag AliStack::fMCEmbeddingFlag, it can be checked from Stak::Particle etc. via GetMCEmbeddingFlag.
=> Set special flag in AliStack in case of MC embedding

STAT/AliTreePlayer.cxx, STAT/CMakeLists.txt, STAT/Macros/AliElasticSearchRootTest.c
*  For elastic export \n has to be removed (_bulk export in elastic per line)
```
obuffer = TBufferJSON::ConvertToJSON(*ppobject, isClass[icol]);
if (isElastic) obuffer.ReplaceAll("\n","");
```
* Adding test for the bulk export with nested classes
* **jq filters for listing and elastic->tree for nested classes not yet implemented** 
(first we provide input documents)
*  Exporting nested classes the size of the document can explode
* e.g exporting of full QA.TPC tree is not possible because of too many data members to represent TGraphErrors (metadata with axis description, histogram, list of functions...)
* Light JSON to be parameterized.  Typically array of fY,fX,fEY,fEX should be sufficient. Metadata to be stored separately
=> PWGPP-312 - Add support for nested json using root TBufferJSON

STEER/CDB/AliDCSSensorArray.cxx
On request from Jens Wiechula, the removal of duplicate points (or rather points falling within a tolerance interval) is changed so that the first and last point are always kept. This just required modifications to the loop control statement (and the initial protection test) -- no other change to the logic.
=> Updated RemoveGraphDuplicates so that always first and last points are kept

PYTHIA8/AliPythia8/AliPythia8.cxx, PYTHIA8/AliPythia8/AliPythia8.h
Decays of long-lived particles (K0short, lambda) are currently
disabled in a hard coded way in the AliPythia8 wrapper. While
this is OK for normal MC productions, on the MC_gen lego train
this might not always be the desired behaviour. The patch allows
for an optional switch on of the decayer for long lived particles
(default: off)
=> Make option to switch on long-lived decayse in PYTHIA8

ITS/ITSbase/AliITSCorrMap1DSDD.cxx, ITS/ITSbase/AliITSCorrMap1DSDD.h
@fprino : this is to protect correction maps from the sign flip due to the Short_t (used internally to store the map) overflow, which happens in very rare cases of "nonuniformiry" exceeding ~3.2mm (mostly artifact of modules with only fraction of the drift distance having calibration data)
=> Protection against Short_t overflow when filling correction maps

STEER/STEERBase/AliStack.cxx, STEER/STEERBase/AliStack.h
in `AliStack::IsPhysicalPrimary`
- The code of `AliStack::IsPhysicalPrimary` was changed to conform with
the definition adopted by ALICE in a recent public note:
>    A primary particle is a particle with a mean proper lifetime
>    tau larger than 1cm/c, which is either a) produced directly in the
>    interaction, or b) from decays of particles with tau smaller
>    than 1cm/c, restricted to decay chains leading to the interaction.
See also ALICE-PUBLIC-2017-005 at
https://cds.cern.ch/record/2270008
Please note, that the definition is approved by the *Physics Board*
- The old implementation of `AliStack::IsPhysicalPrimary` is still
available as `AliStack::IsPhysicalPrimaryOld` to allow testing etc.
- Various bugs in the old implementation (now `AliStack::IsPhysicalPrimaryOld`)
and in …
=> Changes to do with primary particle definition as implemented

STRUCT/AliDIPOv2.cxx
Thanks to Ivana Hrivnacova:
"As the module name is 'DIPO', the medium needs to be called 'DIPO_FE_C0' etc."
=> Fix [ALIROOT-7342]; Apply correct names of media

test/vmctest/gun/runtest.sh
* Setting the number to 1 since this test should run as a simple
automatized regression test
=> Just run 1 event by default in vmctest/gun

EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx
* Urgent fix removing a wrong statement
* Reenables the vmctest/gun to run correctly
* The original authors should cross-check and eventually provide the
correct behaviour
=> [ALIROOT-7344]: Removing access to a dereferenced nullptr

ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx
Merging .zip files from non-AliEn paths requires specifying the inner .root file
with an anchor, in the format `arch.zip#file.root`. On AliEn this is not
necessary as the .zip entries are stored in the catalog as part of the current
directory.
It also tells the TFileMerger to access the .zip files not on AliEn directly, as
opposed to copying them locally first, as `TFile::Cp()` does not support .zip
anchors (silently).
=> Fix merge from .zip not from AliEn

STEER/AOD/AliAODEvent.h, STEER/ESD/AliESDEvent.h
This commit modifies the default values for the pileup tagging with SPD changing in particular the minimum contributor cut from 3 to 5.
The reason is that the cut at 3 contributors was seen to introduce a biased at high multiplicity due to positive taggings  (introducing a distortion in the multiplicity distribution).
This change was discussed in AOT-event properties meeting (@ddobrigk) and announced via email some weeks ago. Nobody opposed.
We verified that the selection at 5 contributors is already the one used in the physics selection (@ekryshen can confirm) and that this change will not affect the selections applied in the multiplicity task (@ddobrigk).
Note also that in AliAnalysisUtils (the wrapper class for event selection used for many analyses @mfloris) the cut is set by default …
=> Updated default cut on Ncontributors in IsPileupFromSPD

test/PbPbbench/aod.C, test/PbPbbench/recraw/aod.C, test/QA/rawqa.C, test/generators/TUHKMgen/aod.C, test/generators/herwig/aod.C, test/generators/phojet/aod.C, test/generators/therminator/aod.C, test/genkine/sim/aod.C, test/genkine/simG4/aod.C, test/gun/aod.C, test/gun/recraw/aod.C, test/merge/backgr/aod.C, test/merge/signal/aod.C, test/pileup/aod.C, test/ppbench/aod.C, test/ppbench/recraw/aod.C, test/pploadlibs/aod.C, test/vmctest/ppbench/aod.C
AOD filtering in test directories should use the OCDB described in
http://alisw.github.io/git-advanced/#use-the-reference-ocdb
=> test AOD filtering must use reference OCDB

STAT/Macros/AliExternalInfo.cfg, TPC/TPCcalib/AliTPCDistortionFit.cxx, TPC/TPCcalib/AliTPCDistortionFit.h
ATO-336 - Update - OCDB path as an argument
￼ATO-46, PWGPP-342 - providing index remapping for RCT table
=> ATO-46 - Add: MonALISA.RCT index remapping

PYTHIA6/AliPythia6/AliGenPythia.cxx, PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx
6 - Do not depend on value of min Et jet cut to select the direct photon acceptance
8 - Outgoing partons are in positions 4-5, needed to select direct gamma acceptance
=> Fix PYTHIA6 and PYTHIA8 (ALIROOT-7308)

EVGEN/AliGenPerformance.cxx, STAT/test/AliTreePlayerTest.C
ATO-245 - Bug fix - reset Pythia common block py->SetMINT(51,0); ￼…
* Add AliSysInfo::AddStamp
* Reset common block (see discussion in ATO-245) after each event
* py->SetMINT(51,0);
* Why/What change common using new AliRoot/AliDPG is not clear
* Momenutm conservation (pz)
* Update SetHighWaterMark(nPart) only in case new particle added to stack
To come (after discussion with AliDPG)
* decay products enhancement or branching ratios
* enable pythia configuration  (e.g pi0 decay)
=> ATO-245 - Bug fix - reset variable py->SetMINT(51,0) 

FMD/FMDutil/AliFMDBaseDA.cxx, FMD/FMDutil/AliFMDBaseDA.h, FMD/FMDutil/AliFMDPedestalDA.cxx, FMD/FMDutil/AliFMDPedestalDA.h
- Do not open the ddl-files (the content of which is
uploaded to the front-ends) until we really need
to.
- Also, write to a temporary file name - the
ddl-file name with ".tmp" appended - so
we can postpone the rotation of old files until
we know we have good data.
- Do not rotate the old files until we're sure
all is OK.
- Made the member function AliFMDBaseDA::CloseFiles
which is overloaded in AliFMDPedestalDA.
- Removed some obsolete code
=> Fixes to the FMD pedestal DA

EVGEN/AliGenBox.cxx, EVGEN/AliGenBox.h
By calling AliGenBox::SetRandomOffset(rmin,rmax,zmin,zmax) each generated track will be forced to
have random offset within requested range (radial shift along phi of momentum). Needed for injection
of loopers in the TPC
=> Possibility to add offset in R,Z per particle

EVGEN/AliGenReaderHepMC.cxx
Conversion moved to NextEvent() since NextParticle() can be called several times
for the same particle, which leads to multiple application of the conversion factor.
Related to 
https://alice.its.cern.ch/jira/browse/PWGMM-21
Difference in tracking efficinecy in LHC17a2a (EPOSLHC) and LHC17a2b
=> Conversion moved to NextEvent() since NextParticle() can be called several times

TPC/TPCbase/AliXRDPROOFtoolkit.cxx, TPC/TPCbase/AliXRDPROOFtoolkit.h
* test status of selected keys (array of regular expressions) in file
* read  object
* write object
* delete object
* +CopyTree in case of trees
* prefilter of file lists before merging
* prepare list of corrpted files together with diagnostic
* see  examples in  https://alice.its.cern.ch/jira/browse/PWGPP-350
```
echo 'TGrid::Connect("alien"); AliXRDPROOFtoolkit::TestFile("alien:///alice/cern.ch/user/p/pwg_pp/ESDFilteringWithPlugin/sub1/output/000246153/408/AnalysisResults.root", "highPt")' | aliroot -l 2&> testHighPt.log
```
=> PWGPP-350-Add:AliXRDPROOFtoolkit::TestFile(fileIn,keyList)

STEER/STEERBase/AliMagF.cxx, STEER/STEERBase/AliMagF.h, STEER/STEERBase/AliMagFast.cxx, STEER/STEERBase/AliMagFast.h
By calling AliMagF::AllowFastField() one invokes field query in |z|<260 cm via fast polynomial
parametrization (factor ~10 faster than AliMagWrapCheb calculation)
=> Integrated fast L3 magnet param to AliMagF

TPC/TPCbase/AliXRDPROOFtoolkit.cxx
Use return values of  TTree::GetEntry  (in loop)  instead of TTree::CopyTree to test consistency of TTree.
* Test will finish on first error.  
* Shorter error mesages in case of errors
=> PWGPP-350 TTree test

TPC/TPCrec/AliTPCReconstructor.cxx, TPC/TPCrec/AliTPCReconstructor.h, TPC/TPCrec/AliTPCtracker.cxx, TPC/TPCrec/AliTPCtracker.h, TPC/TPCrec/TPCrecLinkDef.h
With AliTPCReconstructor::SetCountMCTrackClusters(kTRUE) static call
from rec.C a nclTPCperMCtrack.root file will be created with
srd::vector<short> containing number of TPC clusters per MC track. The full
content is:
nclPerMCtrack->Print()
...
*Br    0 :nMCTracks : nMCTracks/I                                            *
*Br    1 :nclTot    : nclTot/I                                               *
*Br    2 :nclOrphan : nclOrphan/I                                            *
*Br    3 :nclPerTrack : vector<short>                                        *
Since the same clusters may mention up to 3 MC tracks, the sum of Ncl per MC
track will normally exceed the total number of clusters.
nclOrphan gives number of clusters not originated by any track (noise)
=> Create on demand extra tree with vector of NTPC clusters per MC track

STAT/AliTreePlayer.cxx, STAT/AliTreePlayer.h, STAT/CMakeLists.txt, STAT/TStatToolkit.cxx, STAT/TStatToolkit.h, STAT/test/AliTMinuitToolkitTestLinear.C, STAT/test/AliTreePlayerTest.C, STAT/test/CMakeLists.txt, STAT/test/statTest.sh, doxygen/Doxyfile.in
*  testAliTreePlayer
```
ctest -R testAliTreePlayer --verbose
95: I-AliTreePlayerTest.testConvertTree: Test OK
95: Processing /u/miranov/alicesw/sw/SOURCES/AliRoot/alicesw/0/STAT/test/AliTreePlayerTest.C+...
95: I-AliTreePlayerTest.testSelectMetadata AND invariant: Test OK: N(Logbook&&(Stat))=N(Logbook&&(Stat&&Base))+N(Logbook&&(Stat&&(!Base)))       7=2+5
95: I-AliTreePlayerTest.testSelectMetadata Negatioation test: Test OK:   N(!(A||B))=N((!A)&&(!B)) 73==73
95: I-AliTreePlayerTest.testselectTreeInfo: Test OK:   N(A))==N(A&&B)&&N(A&&!B)) 46=6+40
95: I-AliTreePlayerTest.testConvertTree: Test OK
95: [2017-07-12 15:26:50 CEST] [lxbk0198] [SUCCESS] statTest.testAliTreePlayer: All OK 
1/1 Test #95: testAliTreePlayer ................   Passed    1.82 sec
The following tests passed: …
```
=> ATO-426 0 Enabling CTest for subset of the STAT classes

STEER/ESD/AliESDcascade.cxx, STEER/ESD/AliESDcascade.h
This commit introduces a way to change the decay position estimate for AliESDcascades, as discussed with the class author, @iouribelikov . 
At the moment, this decay position is calculated in the standard AliESDcascade constructor via a simple 50/50 average of the points of closest approach of bachelor and V0. This is different wrt to what is done in V0s, in which the decay position is estimated using a weighted (with errors) average of the DCA points of negative and positive tracks, and we are currently exploring the possibility of using a similar approach for cascades. In offline checks, such an approach has been shown to result in an improvement in CosPA resolution of up to 15%, and the purpose of having a SetXYZcascade function is for us to be able to cross-check these offline checks …
=> Introduce SetXYZcascade for testing purposes

STRUCT/AliPIPEv3.cxx
AliZDCv4 will be updated with corrected ZEM position.
To avoid overlaps the dimensions and position of voRB24CuTubeA have been changed.
=> Avoid overlap with ZEM in corrected position.

STEER/AOD/AliAODCaloTrigger.cxx, STEER/AOD/AliAODCaloTrigger.h, STEER/ESD/AliESDCaloTrigger.h, STEER/STEERBase/AliVCaloTrigger.cxx, STEER/STEERBase/AliVCaloTrigger.h
Where available information of the scope (per patch, per fastor)
added, plus some basic information about the return types. Not
yet complete, more information to be added.
=> Basic documentation of the interface of the calo trigger object

STEER/STEER/AliSimulation.cxx, STEER/STEER/AliSimulation.h, STEER/STEERBase/AliHeader.h, STEER/STEERBase/AliMCEvent.cxx, STEER/STEERBase/AliMCEvent.h, STEER/STEERBase/AliMCEventHandler.cxx, STEER/STEERBase/AliStack.cxx, STEER/STEERBase/AliStack.h
In the embedding mode the galice.root will store the paths of underlying events during simulation.
When reading via AliMCEventHandler the paths will be automatically connected: no need to set the
subsudiary MCEventHandlers from the user side (if set, the error will happen).
Additional methods in ESD mode:
1) one can use method AliMCEvent::IsFromSubsidiaryEvent(id) to query if the particle id comes
from underlying bg event.
2) once can use AliHeader::GetBgReuseID() to query the get the instance (copy) of the underlying
bg. event used for given event /MCEvent->Header()->GetBgReuseID()/
=> Store/autodetect MC embedding + misc methods

TPC/macros/MakeTPCRecoParam_Run2Dist.C, TPC/macros/MakeTPCRecoParam_Run2DistMC.C
The TPC/Calib/RecoParams of 2017 have setting to use the Lumi info from the SP 
correction map (if available), synced macros producing recoparams to reflect current status
=> Sync. macros whith version used to produce current recoparam

TRD/TRDbase/AliTRDcalibDB.cxx
Dear @qgp ,
This PR resets the cached TRAP config in the AliTRDcalibDB upon a call to Invalidate(). Without this fix, a typical `db->SetRun(); db->GetTRAPConfig();` looks like this
```bash
I-TAlienFile::Open: Accessing image 2 of alien:///alice/data/OCDBFoldervsRunRange.xml?filetype=raw&cachesz=4000000&readaheadsz=2000000&rmpolicy=1 in SE <ALICE::Kosice::SE>
[TFile::Cp] Total 0.00 MB	|====================| 100.00 % [0.1 MB/s]
I-AliCDBHandler::OnStartDocument: Reading XML file for LHCPeriod <-> Run Range correspondence
I-AliCDBManager::GetLHCPeriodAgainstAlienFile:  LHC folder = alien://folder=/alice/data/2016/OCDB
I-AliCDBManager::GetLHCPeriodAgainstAlienFile:  LHC period start run = 247171
I-AliCDBManager::GetLHCPeriodAgainstAlienFile:  LHC period end run = 267257
------------ Run 249533 …
```
=> TRD: AliTRDcalibDB reset TRAP config in Invalidate()

ITSMFT/ITS/itsuTestBench/CreateITSUv2ALP3.C
The length of Outer Barrel Staves was wrongly computed in CreateITSUv2 macro. Fixed to match the actual Module length and so avoid volume extrusions in geometry.
=> Fix OB Stave Length to avoid extrusions

STRUCT/AliPIPEv3.cxx
Avoid overlap of air volume (voRB24CuTubeA) with old ADA
=> Avoid overlap with old ADA

ZDC/ZDCsim/AliZDCv4.cxx
Support plates of ZEM should be centered w.r.t beam pipe in x-direction.
=> Correct x-position of ZEM support

ITS/ITSbase/AliITSClusterFinder.cxx, TPC/TPCrec/AliTPCtracker.cxx, TPC/TPCrec/AliTPCtracker.h
1) when filling nCl-per-track tree check for duplicate labels in the same cluster 
2) fill additional array nclMPerTrack for every MC label, accumulating there total non-negative labels count for clusters contributed by this label. I.e. if all N clusters related to given label were made of this label only, the nclMPerTrack[label] will be equal to N, if all clusters had exactly 2 non-negative labels contributing, it would be 2N etc. Therefore, statistically each nclPerTrack[i] should have a weight float(nclPerTrack[i])/nclMPerTrack[i]<1 to add up to nclTot-nclOrphan
=>  Check for duplicates, fill muliple labels, use all tracks in case of embedding

STEER/ESD/AliESD.h
Removed the superfluous return statement in AliESD::GetDiamondCovXY() which produces a warning with gcc 6.2, see https://github.com/alisw/AliPhysics/issues/2193
warning by @mfasDa 
```c++
/home/markus/alice/sw/ubuntu1404_x86-64/AliRoot/ali-work-1/include/AliESD.h: In member function 'void AliESD::GetDiamondCovXY(Float_t*) const':
/home/markus/alice/sw/ubuntu1404_x86-64/AliRoot/ali-work-1/include/AliESD.h:161:5: error: this 'for' clause does not guard... [-Werror=misleading-indentation]
for(Int_t i=0;i<3;i++) cov[i]=fDiamondCovXY[i]; return;
^~~
/home/markus/alice/sw/ubuntu1404_x86-64/AliRoot/ali-work-1/include/AliESD.h:161:53: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
for(Int_t i=0;i<3;i++) cov[i]=fDiamondCovXY[i]; return;
```
=> Removed superfluous return statement in AliESD.h

STEER/macros/CheckESD.C, STEER/macros/CreateAODfromESD.C, test/PbPbbench/aod.C, test/PbPbbench/recraw/aod.C, test/generators/TUHKMgen/aod.C, test/generators/herwig/aod.C, test/generators/phojet/aod.C, test/generators/therminator/aod.C, test/genkine/sim/aod.C, test/genkine/simG4/aod.C, test/gun/aod.C, test/gun/recraw/aod.C, test/merge/backgr/aod.C, test/merge/signal/aod.C, test/pileup/aod.C, test/ppbench/aod.C, test/ppbench/rec.C, test/ppbench/recraw/aod.C, test/pploadlibs/aod.C, test/vmctest/lego/sim.C, test/vmctest/lego/simG4.C, test/vmctest/ppbench/aod.C
Use ALIROOT_OCDB_ROOT to find the default OCDB. Fix the loading of the magnetic field. Load libpythia to avoid crashes when the header is stored in galice.root.
=> Restore the functionality of some tests

PYTHIA8/AliPythia8/AliPythia8.h, PYTHIA8/AliPythia8/AliTPythia8.h
Following the discussion on the alice-analysis-operations@cern.ch mailing list here is the fix to use Pythia8 in aliroot without having to add the Pythia8 folder to ROOT's include path
=> fixing include path for Pythia8 headers

STEER/STEER/AliMC.cxx
For some reason it is not enough to define only particles, Geant4 needs separate definition of antiparticles. The problem was detected in test/genkine.
=> Anti-particles of heavy vector mesons (Geant4)

STEER/STEERBase/AliVEvent.h
Warning is issued when running local analysis (with root6).
```c++
/Users/hbeck/alice/alibuild/sw/osx_x86-64/AliRoot/0_ROOT6-1/include/AliVEvent.h:264:48: warning: unused
parameter 'mctruth' [-Wunused-parameter]
virtual void AdjustMCLabels(const AliVEvent *mctruth) {return;}
^
1 warning generated.
```
=> Fix unused variable warning AliVEvent.h

ITSMFT/MFT/MFTbase/AliMFTAnalysisTools.cxx
points is created with new[] and thus has to be erased with delete[]
Spotted by compiler.
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliRoot/0_ROOT6/0/ITSMFT/MFT/MFTbase/AliMFTAnalysisTools.cxx:173:5: warning: 'delete' applied to a pointer
that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
delete points;
^
[]
/Users/hbeck/alice/alibuild/sw/SOURCES/AliRoot/0_ROOT6/0/ITSMFT/MFT/MFTbase/AliMFTAnalysisTools.cxx:156:23: note: allocated with 'new[]' here
TVector3 **points = new TVector3*[2];     // points[0] for the muon, points[1] for the direction parallel to the z-axis defined by the given (x,y)
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliRoot/0_ROOT6/0/ITSMFT/MFT/MFTbase/AliMFTAnalysisTools.cxx:192:7: warning: 'delete' applied to a pointer
that was …
```
=> Fix mismatched new[] delete AliMFTAnalysisTools

STEER/STEERBase/AliPIDResponse.cxx
SetTRDCentralityMaps printed a statement about an eta correction while in fact the centrality correction was meant.
Printout is visible when running local analysis
```bash
I-AliESDpid::SetTRDEtaMaps: Request to disable TRD eta correction -> Eta correction has been disabled
I-AliESDpid::SetTRDClusterMaps: Request to disable TRD cluster correction -> Cluster correction has been disabled
I-AliESDpid::SetTRDCentralityMaps: Request to disable TRD eta correction -> Centrality correction has been disabled
```
=> Fix printout statement AliPIDResponse

ITS/macrosSDD/ReadCDHBlckAttrSDD.C
A new macro was created to easily read the content of the SDD CDH Block Attributes in the data (which will contain the firmware version number).
=> New SDD macro to read CDH Block Attributes

ANALYSIS/macros/train/AddMCGenLightNuclei.C
This macro will make possible running the coalescence afterburner coded by @eserradi on MC LEGO trains.
For the records: the results obtained with the coalescence afterburner were presented by @eserradi and @akalweit at the PF on the 25th of August.
=> Enable coalescence afterburner on LEGO trains (@eserradi)

STAT/AliElasticSearchRoot.cxx, STAT/AliElasticSearchRoot.h, STAT/Macros/AliElasticSearchRootTest.C
* Follow up of documentation discussion in request: https://github.com/alisw/AliRoot/pull/243
* Rename the "Unit" test macro
* Add doxygen documentation in the test macro
=> ATO-402 - Updated documentation for AliElasticSearch

ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx, STEER/AOD/AliAODVertex.h
AODvertex will be create with the flag AliAODVertex::kPrimaryInvalid if there was no valid vertex in the ESD event and with AliAODVertex::kPrimaryTPC if the onlt valid vertex was from the TPC
=> Extra flags for Invalid or TPC primary vtx in the AOD

STEER/STEERBase/AliStack.cxx, STEER/STEERBase/AliStack.h
Creating static object involvint gROOT modification may corrupt the memory in case of
static builds for DA. The static TParticle pointer will be initialized on 1st demand
(never in case of DA)
=> Use static pointer rather than the object

STAT/AliExternalInfo.cxx, STAT/AliTreeTrending.cxx, STAT/AliTreeTrending.h, STAT/TStatToolkit.cxx, STAT/TStatToolkit.h
* ATO-46 AliExternalInfo:GetMCPassGuess returns now also the anchor period name
* fixed bug in anchor pass guessing: in case AliRoot, AliPhysics and production name matched, the wrong pass guess was provided
* ATO-83 error handling in case plotting fails
* updated Doxygen documentation
* ATO-83 MC to anchor comparison
* Behaviour of TStatToolkit::MakeMultGraph in case of empty plot for a variable can now be swichted between these options:
* Demand a plot for every variable or otherwise return empty plot with error msg
* Accept missing plots for some variables as long as not all are missing, if all are missing return empty plot with error msg
=> ATO-83 & ATO-46 MC to anchor comparison

STAT/TStatToolkit.cxx, STAT/TStatToolkit.h
* using \namespace instead of \class doxygen directive
* small modification in documentations
* modifying curly brackets in some functions
* once full documntation provided consistent usage of the brackets should be requested
=> AT0-83 - Fix for doxygen documentations for TStatToolkit

STAT/AliDrawStyle.cxx, STAT/AliDrawStyle.h, STAT/AliTreeTrending.cxx, STAT/AliTreeTrending.h, STAT/TStatToolkit.cxx
* check ranges of style array
* handle out of range request. Returning invalid value instead of crash
* interpret separated string as array of attributes
* Updated/improved doxygen documentation
* keeping back compatibility (old - string with arrays of values, of style ID)
* see Doxygen documenation in the  TStatToolkit::MakeMultGraph
* expr to drow and cuts  can be  array
* before only expression could be array
```
TMultiGraph * TStatToolkit::MakeMultGraph(TTree * tree, const char *groupName, const char* expr, const char * cut, const char * markers, const char *colors, Bool_t drawSparse, Float_t msize, Float_t sigmaRange, TLegend * legend, Bool_t comp){
///  \param expr       - string <variablearray>:<tagID>:<variablearrayError>
///                      <variablearray>="var0; ...; varN …
```
=> PWGPP-312, ATO-83, ATO-46: Update  TStatToolkit::MakeMultGraph

STEER/ESD/AliESDcascade.cxx, STEER/ESD/AliESDcascade.h
This change introduces a method in AliESDcascade to improve the precision of the cascade decay position estimate by using an error-weighted average for that estimate, as discussed initially [here](https://indico.cern.ch/event/658280/contributions/2685555/attachments/1505439/2345751/DDChinellato-VertexerImprovements-7.pdf). The final implementation employs a covariance matrix calculation that's analogous to what is already done in the AliESDv0::Refit method and borrows from the same function used there for single track covariance estimates (see "GetWeight"). The ::RefitCascade function, as contained in this pull request, is also extensively commented for clarity of purpose and understandability. 
As a side product, the RefitCascade method will also produce a chi2 value for the cascade …
=> Introduction of AliESDcascade::RefitCascade method

RAW/MDC/AliRawDB.h
The forward declaration of AliRawDataArrayV2 is correct, but the latest cling doesn't accept it. Until we get a fix in Root, I propose to include the header file.
=> Avoid issues with the latest cling

ANALYSIS/ANALYSISalice/AliEventPoolManager.cxx, ANALYSIS/ANALYSISalice/AliEventPoolManager.h
AliEventPool::Clear() shadows TObject::Clear(Option_t *), which causes a large number of warnings for files which include AliEventPoolManager in AliPhysics (which can make the compilation logs more difficult to parse). This pull request contains a minor change to make the AliEventPool::Clear(...) signature align with TObject::Clear(...), but it should have no impact on functionality. 
I think this is quite a trivial change, but comments are welcome, especially in case I've missed something.
An example warning is below:
>In file included from >/alice/sw/SOURCES/AliPhysics/root6/0/PWGCF/EBYE/BalanceFunctions/AliAnalysisTa>skTriggeredBF.cxx:34:
>/alice/sw/osx_x86-64/AliRoot/root6-1/include/AliEventPoolManager.h:161:15: >warning: 'AliEventPool::Clear' hides overloaded virtual function …
=> Fix overloaded virtual function warning

HLT/BASE/CMakeLists.txt, HLT/BASE/HOMER/CMakeLists.txt, HLT/BASE/interface/CMakeLists.txt, HLT/BASE/util/CMakeLists.txt, HLT/EVE/CMakeLists.txt, HLT/FMD/CMakeLists.txt, HLT/ITS/CMakeLists.txt, HLT/MUON/CMakeLists.txt, HLT/PHOS/CMakeLists.txt, HLT/QA/CMakeLists.txt, HLT/RCU/CMakeLists.txt, HLT/SampleLib/CMakeLists.txt, HLT/TPCLib/CMakeLists.txt, HLT/TPCLib/EVE/CMakeLists.txt, HLT/TPCLib/tracking-ca/cagpu/cuda/CMakeLists.txt, HLT/TPCLib/tracking-ca/cagpu/opencl/CMakeLists.txt, HLT/TRD/CMakeLists.txt, HLT/VZERO/CMakeLists.txt, HLT/ZDC/CMakeLists.txt, HLT/comp/CMakeLists.txt, HLT/createGRP/lib/CMakeLists.txt, HLT/global/CMakeLists.txt, HLT/pendolino/CMakeLists.txt, HLT/rec/CMakeLists.txt, HLT/shuttle/CMakeLists.txt, HLT/sim/CMakeLists.txt, HLT/trigger/CMakeLists.txt, STEER/STEER/CMakeLists.txt
This pull request includes all root headers in HLT and in STEER/STEER as -isystem, to avoid fake warnings coming from within the headers during AliRoot Compilation.
I would suggest to apply this to all AliRoot libraries.
I have added STEER, such that this will not be merged automatically.
=> Include ROOT headers as -isystem

STEER/AOD/AliNanoAODHeader.cxx, STEER/AOD/AliNanoAODHeader.h, STEER/AOD/AliNanoAODStorage.cxx, STEER/AOD/AliNanoAODStorage.h
allow NanoAOD header files to also save string variables
remove some compiler warnings from the nano AOD framework
=> introduce string attributes in NanoAODs

HLT/TRD/macros/initGRP.h, ITS/macrosSDD/ITSQArecoparam.C, ITSMFT/MFT/MFTrec/AliMuonForwardTrackFinder.cxx, STEER/ESD/AliESDRun.cxx, STEER/STEER/AliGRPManager.cxx, STEER/STEER/AliReconstruction.cxx, STEER/STEERBase/AliMagF.cxx, STEER/STEERBase/AliMagF.h
Pass A/Z info to field creation to properly rescale rigidity for different ion types
=> Account for beam A/Z in LHC B-field initialization

STEER/STEERBase/AliMagF.cxx, STEER/STEERBase/AliMagF.h
For the bwd compatibility with custom field initializations in detector code of aliphysics.
Not to be used when the LHC magnets field is important (ZDC) and the A-A beam is not PbPb
=> Added legacy constructor for bwd compatibility

HLT/createGRP/lib/AliHLTCreateGRP.cxx, HLT/rec/AliHLTReconstructor.cxx
Also fixes an incompatibility with HLT GRP creation introduced by Ruben's recent change to magnetic field initialization.
=> Make most HLT initialization and running failures a fatal, such that a failure to decompress TPC clusters is not unnoticed

STEER/AOD/AliNanoAODHeader.cxx, STEER/AOD/AliNanoAODHeader.h, STEER/AOD/AliNanoAODStorage.cxx, STEER/AOD/AliNanoAODStorage.h
change the internal storage of the fired trigger particles to a coded int per event instead of full strings. This requires less disk space.
=> make storage of Fired Trigger Particles more efficient in the NanoAODs

STARLIGHT/AliStarLight/AliGenSLEvtGen.cxx, STARLIGHT/AliStarLight/DecayTables/JPSI.EE.DEC, STARLIGHT/AliStarLight/DecayTables/JPSI.MUMU.DEC
Analysis of J/psi yield enhancement in peripheral events wants to use Starlight event in cocktail with Hijing. Therefore we need mother particle and history of decay to identify the UPC electrons. EvtGen decay tables are for J/psi to lepton decays with QED radiative corrections via Photos package. Whole thing is to re-decay Starlight J/psi in EvtGen with radiative corrections and put it to Hijing event.
=>  Store mother particle and decay history in kine tree and two decay tables

HLT/BASE/util/AliHLTZMQhelpers.cxx
reported by Barth: std::runtime_error needs #include (at least on SLC6 with gcc 4.9.1)
=> Add missing include <stdexcept>

test/generators/phojet/sim.C
Corrected list and order of libraries: libDPMJET contains DPMJET, PhoJet and Pythia6115
=> Corrected list and order of libraries

ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx
The merging of grid outputs is broken with ROOT6 due to a bug in an interpreted line of the AliAnalysisAlien.
The bug is fixed with this commit.
=> Fix issue with ROOT6 when merging with the alien plugin

ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx
This reverts commit fbb64a6bab6d73aa1e3397c451b2fc8911cff575.
The fix causes issue with ROOT5: reverting for the time being.
=> Revert "Fix issue with ROOT6 when merging with the alien plugin"

EVGEN/AliGenPerformance.cxx
needed for running AOD filtering without errors
=> [ATO-245] Add generator event header setting

TOF/TOFbase/AliTOFGeometry.cxx
This fix is requested because we found some TRM links swapped.
=> fix for TOF maxipad channels swapped in the TRMs

AD/ADbase/AliADConst.h, AD/ADbase/AliADDataDCS.cxx, AD/ADbase/AliADPreprocessor.cxx, AD/ADrec/AliADDecision.cxx, AD/ADrec/AliADReconstructor.cxx, AD/ADsim/AliADDigitizer.cxx, AD/ADsim/AliADDigitizer.h, AD/ADsim/AliADTriggerSimulator.cxx
- photo-cathode efficiency times light-yield is taken into account in the MC simulation, analogously as for VZERO
- the old behavior can be restored by setting AD/Calib/LightYields entries to 1
- nPhotonsPerMIP was adjusted
- code cleanup
=> using light-yields in AD MC simulation

HLT/BASE/util/CMakeLists.txt
when missing, throw a warning and don't build ZMQhistViewer
this should fix ALIROOT-7555
=> Fix handling missing X11 libraries (on macos)

AD/ADrec/AliADDecision.cxx, AD/ADsim/AliADTriggerSimulator.cxx, AD/ADsim/AliADv1.cxx
nested comments are caught by the intel c++ compiler and treated as an error, it would be great if this (otherwise harmless) pr could be merged
example of compiler error:
/nics/c/home/rbertens/alibuild/sw/SOURCES/AliRoot/0/0/AD/ADrec/AliADDecision.cxx(226): error #9: nested comment is not allowed
compiler used
[rbertens@acf-login2 AliRoot]$ icc --version
icc (ICC) 17.0.2 20170213
Copyright (C) 1985-2017 Intel Corporation.  All rights reserved.
=>  remove nested comments that generate a compiler error using icc

STEER/STEERBase/AliTRDNDFast.cxx
Some compilers seem to have Problems with /* inside of a comment
=> Fix for some compilers; problem with outcommented code: /* deleted

ITSMFT/ITS/ITSUpgradeSim/AliITSUv2.cxx, ITSMFT/ITS/ITSUpgradeSim/AliITSUv2Layer.cxx, ITSMFT/ITS/ITSUpgradeSim/AliITSUv2Layer.h
The IB geometry was updated to the latest data as requested at ITSU plenary session. In particular the metal stack was added to the Si sensor, the FPC aluminum layers are more realistic, and the glue between the chip and the sensor was added.
=> Update IB geometry to latest data

STEER/CDB/AliCDBGrid.cxx, STEER/CDB/AliCDBManager.cxx, STEER/CDB/AliCDBManager.h, STEER/CDB/AliCDBStorage.cxx, STEER/CDB/AliCDBStorage.h
When using, for instance:
AliCDBManager *cdb = AliCDBManager::Instance();
cdb->SetDefaultStorage("raw://");
cdb->SetRun(277015);
cdb->SetMaxDate(TTimeStamp(2017, 7, 1, 0, 0, 0));  // new feature
only OCDB files created no later than the given UTC date will be returned.
This feature ensures perfect reproducibility: by setting a certain date it will
be possible to:
* protect jobs from OCDB updates while they are running
* re-run jobs in the future using the exact same OCDB
=> Add support for AliEn OCDB time machine

HLT/BASE/CMakeLists.txt
Hi,
This commit add Cint dep to AliHLTUtil because AliRoot build fails on macOS 10.13 with the following error. libCint has these missing symbols but it was not directly linked to AliHLTUtil.
```
[64%] Linking CXX shared library libAliHLTUtil.so
Undefined symbols for architecture x86_64:
"_G__Doubleref", referenced from:
G__G__AliHLTUtil_517_0_3(G__value*, char const*, G__param*, int) in G__AliHLTUtil.cxx.o
"_G__Floatref", referenced from:
G__G__AliHLTUtil_930_0_33(G__value*, char const*, G__param*, int) in G__AliHLTUtil.cxx.o
"_G__UShortref", referenced from:
G__G__AliHLTUtil_517_0_3(G__value*, char const*, G__param*, int) in G__AliHLTUtil.cxx.o
"_G__add_setup_func", referenced from:
__GLOBAL__sub_I_G__AliHLTUtil.cxx in G__AliHLTUtil.cxx.o
"_G__call_setup_funcs", referenced from: …
```
=> Add Cint dependency to libAliHLTUtil.so

HLT/BASE/util/CMakeLists.txt
Hi,
This commit should fixes the following warning!
Thank you.
```
DEBUG:AliPhysics:AliRoot:0: CMake Warning (dev) in HLT/BASE/util/CMakeLists.txt:
DEBUG:AliPhysics:AliRoot:0:   A logical block opening on the line
DEBUG:AliPhysics:AliRoot:0:
DEBUG:AliPhysics:AliRoot:0:     ~/alice/sw/SOURCES/AliRoot/0/0/HLT/BASE/util/CMakeLists.txt:110 (if)
DEBUG:AliPhysics:AliRoot:0:
DEBUG:AliPhysics:AliRoot:0:   closes on the line
DEBUG:AliPhysics:AliRoot:0:
DEBUG:AliPhysics:AliRoot:0:     ~/alice/sw/SOURCES/AliRoot/0/0/HLT/BASE/util/CMakeLists.txt:117 (endif)
DEBUG:AliPhysics:AliRoot:0:
DEBUG:AliPhysics:AliRoot:0:   with mis-matching arguments.
DEBUG:AliPhysics:AliRoot:0: This warning is for project developers.  Use -Wno-dev to suppress it.
```
=> Fix CMake warning

EMCAL/EMCALbase/AliEMCALTriggerRawDigitMaker.cxx, EMCAL/EMCALbase/AliEMCALTriggerRawDigitMaker.h
These changes are needed to use this class also to decode the STU data in the DQM framework.
Nothing changes when this class is used for reconstruction using the raw ROOT format.
=> Adapt the trigger raw digit maker to work with raw stream in DATE format

EVGEN/AliGenPerformance.cxx
* Pythia decayer used to decay particles
* Pythia particle array created
* NEW: for particles specified in "geant particles" array special treatment
* particles are treated by GEANT
* daughter particles of geant particles are removed from pythia stack
* Bug fix
* in the previous version of the AliGenPerformance KeepTrack were not called
for fraction of tracks
* in new version all particles pushed to stack were signed to be keept
````
KeepTrack(nPart);
SetHighWaterMark(nPart);
````
* Use external vertex if default vertex distribution not set
* Usage:
* Generator for  the MC validation
* New generator used in the AliDPG/MC/CustomGenerators/
https://github.com/miranov25/AliDPG/blob/master/MC/CustomGenerators/DPG/PerformaceGenerator.C
=> ATO-245 BUGfix in PushTracks-KeepTracks(nPart)

STEER/CDB/AliCDBStorage.cxx
Feature introduced in #465 is missing a member initialization causing an
undetermined and very dangerous behaviour in most cases.
=> Fix missing member initialization

STEER/CDB/AliCDBManager.cxx, STEER/CDB/AliCDBManager.h, STEER/CDB/AliCDBStorage.cxx, STEER/CDB/AliCDBStorage.h
* Exit with `AliFatal` in case `SetMaxDate()` is called after the run was set already
* Support setting the date for individual storages: individual storage settings will override global ones
**Note:** OCDB Time Machine feature introduced in #465, with a bug fix in #477.
=> Improve OCDB Time Machine

STEER/STEER/AliMC.cxx, STEER/STEERBase/AliPDG.cxx
Following a discussion with @amorsch it has been clarified that the Pythia decayer cannot handle the decay of di-baryon resonances like the d*. For this reason I am bringing back the modifications to the AliMC framework.
=> New X* state added

EVGEN/AliGenPerformance.cxx, STAT/AliDrawStyle.cxx, STAT/AliDrawStyle.h, STAT/AliExternalInfo.cxx, STAT/AliExternalInfo.h, STAT/AliPainter.cxx, STAT/AliPainter.h, STAT/AliTMinuitToolkit.cxx, STAT/AliTMinuitToolkit.h, STAT/AliTreePlayer.cxx, STAT/AliTreePlayer.h, STAT/AliTreeTrending.cxx, STAT/AliTreeTrending.h, STAT/CMakeLists.txt, STAT/Macros/aliExternalInfo.C, STAT/Macros/logbookAddMetadata.C, STAT/Macros/qatpcAddMetadata.C, STAT/STATLinkDef.h, STAT/TStatToolkit.cxx, STAT/TStatToolkit.h, STAT/test/AliDrawStyleTest.C, STAT/test/AliTreeTrending.css, STAT/test/CMakeLists.txt, STAT/test/alirootTestStyle.css, STAT/test/statTest.sh, STAT/test/test1.css, STAT/test/test2.css, STAT/test/testDrawArrayHisto.C, doxygen/Doxyfile.in
Contributors: Marian, Boris , Sebastian
* **AliDrawStyle (EXTENDED)**, **AliDrawStyleTest.C(EXTENDED)**  + test **test/*.css files (NEW)**
*  implementing subset of CSS style standard as in html
* see doxygen documentation, resp. usage in the test/AliDrawStyleTest.C
* usage in the AliPhysics_ROOT QA macros
* author: Boris, Marian   
* **AliPainter (NEW)** 
* using CSS style
* for QA and performance plots generation
* implementing object drawing using string formatting see
* Status: Work in progress - more painting functions to be added 
* E.g. ND Histogram draw interface (see doxygen) as serie of functors
````
AliPainter::DrawHistogram("hisK0DMassQPtTgl()(0)()(err)", hisArray);
AliPainter::DrawHistogram("hisK0DMassQPtTgl(-0.02,0.02)(0)(1)(err)", hisArray);
````      
* author: Boris, …
=> Usage of the CSS style  +QA development

RAW/RAWDatarec/AliRawReader.cxx, RAW/RAWDatarec/AliRawReader.h
This commit introduces two new ways to pre-select events to be reconstructed in AliRawReader:
1) events can be selected based on the trigger cluster, which is extracted by parsing the string of the fired trigger cluster. E.g.
rec("raw.root","?Cluster=CENT") -> reconstruct events of the CENT cluster
rec("raw.root","?Cluster=CENT || CALO") -> reconstruct events of the CENT and CALO clusters
rec("raw.root","?ExcludeCluster=CENT") -> rejects events of the CENT cluster
2) events can be selected based on the presence/absence of specific detectors in the list of triggered detectors. E.g.
rec("raw.root","?DetectorsContain=ITSSDD") -> reconstruct events in which the SDD were triggered
rec("raw.root","?DetectorsExcluded=ITSSDD") -> reject events in which the SDD were triggered
These features are …
=> Add new event selection features: by cluster and by triggered detector

STAT/AliExternalInfo.cxx, STAT/AliExternalInfo.h
* Used in case we need to run run over sevral rpooductions
* E.g used to make 2015-2017 QA/calibration sumaries : 
* See e.g summary: https://indico.cern.ch/event/610359/contributions/2808318/attachments/1566741/2469481/TPCNormalizedVolumeAndFlux.pdf
```
void AliExternalInfo::CacheProduction(TPRegexp select, TPRegexp reject, TString sourceList)
```
Input production list - from MonaLisa HTM linterface 
* select - selection mask 
* reject  - rejection mask
* sourceList  - list of detectors to cache
* Cache all  LHC17  production data 
* Chace  tree:
* QA.TPC;QA.EVS;QA.TRD;QA.rawTPC;QA.ITS;Logbook;QA.TOF;Logbook.detector
```       AliExternalInfo::CacheProduction(TPRegexp("LHC17.*"),TPRegexp("cpass0"),"QA.TPC;QA.EVS;QA.TRD;QA.rawTPC;QA.ITS;Logbook;QA.TOF;Logbook.detector");
```
=> ATO-46  ADD: AliExternalInfo::CacheProduction

STEER/STEERBase/AliMCEvent.cxx, STEER/STEERBase/AliMCEvent.h
Within the AliMCEvent all internal calls of GetTrack with global track ID must
go via top MCEvent, since the global indices do not correspond to that in the
subsidiary event stack. In MCtoMC embedding mode this topEvent is the one containing
all subsidiaries, in standard MC topEvent points to itself.
W/o this feature AssignGeneratorIndex was crashing in MC embedding mode if 
injected generator was cocktail.
=> Internal GetTrack calls must go via top event

TEvtGen/TEvtGen/AliGenEvtGen.cxx
Bug fix: nt was uninitialized and no check was done on the result of PushTrack leading to seg fault in KeepTrack when particle was not pushed (e.g. PDG not known)
=> EvtGen: small bug fix

EMCAL/EMCALbase/AliEMCALTriggerDCSConfig.cxx, EMCAL/EMCALbase/AliEMCALTriggerDCSConfig.h, EMCAL/EMCALbase/AliEMCALTriggerSTUDCSConfig.cxx, EMCAL/EMCALbase/AliEMCALTriggerSTUDCSConfig.h, EMCAL/EMCALbase/AliEMCALTriggerTRUDCSConfig.cxx, EMCAL/EMCALbase/AliEMCALTriggerTRUDCSConfig.h, EMCAL/EMCALbase/CMakeLists.txt, EMCAL/EMCALbase/TestsAliEMCALTriggerSTUDCSConfig.cxx, EMCAL/EMCALbase/TestsAliEMCALTriggerTRUDCSConfig.cxx
Add operators << and == to trigger DCS config object to check if two configurations are the same. New operators are covered by unit tests integrated in the ALICE ctest suite.
=> [EMCAL-42] Add operator== and operator<< to DCS Config objects

STAT/AliExternalInfo.cxx, STAT/AliExternalInfo.h, STAT/Macros/AliExternalInfo.cfg
* AliExternalInfo.cfg
* Add index name mapping for production
* Add cache productio information (source description)
*   AliExternalInfo.cxx
*	AliExternalInfo::GetProductionTree(TString period, TString pass)
* 	\param period    - period ID
*	\param pass      - pass ID
* 	\return production tree ()
* Input data source MonALISA
* Production information from MonALISA web interface - querying tags
* PPass - https://alimonitor.cern.ch/prod/?t=1&res_path=mif
* CPass - https://alimonitor.cern.ch/prod/?t=2&res_path=mif
* MC - https://alimonitor.cern.ch/prod/?t=3&res_path=mif
* Tags query not fully reliable as syntax was chenging several times
* Only reliable information - path column in reulting tree (path to the output data)
* Algorithm:
* loop over all possible production (Prod, ProdCPassm, …
=> ATO-46, ATO-434- GetProductionTree using period, pass

STAT/AliExternalInfo.cxx, STAT/TStatToolkit.cxx
not sure which  compiler used my Marco 
Some of the warnings should be default in the future
FIX: STAT/TStatToolkit.cxx
* [-Wlogical-not-parentheses]
* [-Wparentheses]
=>  ATO-434, ATO-83: FIX - warnings as reported by Marco 

EVGEN/AliGenParam.cxx
- if not set, use external decayer from TVirtualMC::GetMC() (as before)
- if no decayer available, return Fatal
- needed for adding Exodus decayer for single AliGenParam sources in cocktail
=> Using decayer in Init, when set

STAT/AliTMinuitToolkit.cxx, STAT/AliTMinuitToolkit.h, STAT/test/AliTMinuitToolkitTestLinear.C
* Goal
* Integrate  AliTMinutiToolkit class with AliPainter
* Extended list of default fitters/loglikelihood/strategies
* AliTMinuitToolkit.h
* Doxygen
* CLion coding style
* mostly variable names convention
* lines auto-intendation
* automatically genearated figures in the ctest (AliTMinuitToolkitTestLinear.C) used for include graphics example
* AliTMinuitToolkit.cxx
* Doxygen
* CLion coding style
* variable names convention
* unused variables
* almost all warnings supressed except of:
* auto statements in initilialization
* root constructs  - missing protection against exception throwing
* test/AliTMinuitToolkitTestLinear.C
* Doxygen
* CLion
* adding figures generated inthe test into Doxygen documentation
* TODO:
* Move figures from the  test directory into doxygen/html directory
* Add …
=> ATO-410, ATO-418: Add Doxygen documentation + CLion coding styles

STEER/STEERBase/AliMCParticle.h
In the old condition, the Log((e+pz)/(e-pz)) is not evaluated when e == pz within float precision, but it is evaluated when pz > E (which is unphysical ,but can happen within float precision). By removing the outer TMath::Abs from the condition, pz > E is also caught, and will return a -999 as rapidity. Anyone who approves, please check if I didn't make a dumb mistake in logic ... thanks, Redmer
=>  avoid floating point error when pz is larger than e

EMCAL/EMCALbase/AliEMCALTriggerDCSConfig.cxx, EMCAL/EMCALbase/AliEMCALTriggerDCSConfig.h, EMCAL/EMCALbase/AliEMCALTriggerSTUDCSConfig.cxx, EMCAL/EMCALbase/AliEMCALTriggerSTUDCSConfig.h, EMCAL/EMCALbase/AliEMCALTriggerTRUDCSConfig.cxx, EMCAL/EMCALbase/AliEMCALTriggerTRUDCSConfig.h
Adding function ToJSON to AliEMCALTrigggerDCSConfig, AliEMCALTriggerSTUDCSConfig and AliEMCALTriggerTRUDCSConfig, creating a JSON-string from the ROOT object (text format). Called with the AliEMCALTriggerDCSConfig object it creates a JSON string with the whole trigger configuration.
=> [EMCAL-45] JSON-serialize ODCB objects

ALIROOT/aliroot.cxx
This circumvents a crash in ROOT 6 cling on some systems.
We have been trying to debug this with @pzhristov but could not find the real cause.
=> fix weird ununderstandable problem with ROOT6 cling clashing in interpreter mode when cout is used in aliroot binary

EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx
Fixes an error in how the L1 Trigger thresholds were checked.
Makes missing L0, L1 trigger thresholds call AliFatal.
=> Make Missing L0/L1 THR cause Fatals. Fixes L1 check error.

STEER/STEERBase/AliMergeableCollection.cxx
The merging of an AliMergeableCollection is extremely slow on ROOT6. This happens because the interpreter was used during merging. The PR uses TMethodCall instead, solving the speed issue.
=> Speed up merge with root6

ANALYSIS/ANALYSISalice/AliAnalysisTaskSE.cxx, ANALYSIS/ANALYSISalice/AliAnalysisTaskSE.h
This fix is needed in order to be able to skim AOD files, without the fix the header info would not be copied.
Note I believe someone has to update the code as not all branches of the AOD are treated (like TZERO, ZDC, and ADA plus more are missing).
This fix is rather urgent.
=> fix copying of aodheader

EVGEN/AliDecayerExodus.cxx, EVGEN/AliDecayerExodus.h, PYTHIA6/AliPythia6/AliDecayerPythia.cxx, PYTHIA6/AliPythia6/AliGenPythia.cxx, PYTHIA6/AliPythia6/AliPythia.cxx
- All changes in the code are affecting exclusively LMee simulations with the Exodus decayer.
- For the Pythia part of the code, still only affecting the Exodus decayer, in particular what is done here is to accommodate the code for handling two new decays added in the decay table to dielectrons (namely eta' -> omega e+ e- and phi -> pi0 e+ e-).
Note: this is an update of the old (closed) pull request: https://github.com/alisw/AliRoot/pull/433)
=> Updated Exodus decayer (to handle new eta-prime and omega decays)

ANALYSIS/ANALYSISalice/AliESDtrackCuts.cxx, ANALYSIS/ANALYSISalice/AliESDtrackCuts.h
Redirection of IsSelected to proper selector function:
- AcceptTrack in case of AliESDtrack
- AcceptVTrack in case of any other object
inheriting from AliVTrack (i.e. AliAODTrack)
Would support direct use for AOD tracks without the need
of a temp copy AliESDtrack.
Proposed patch: In case of AliESDtracks as input the functionality is not changed, in case of AOD tracks it is redirected to the proper functions for AliVTrack. With the patch the integration in frameworks using the AliVCuts interface becomes easier. It is possible to use the virtual IsSelected function for both ESD and AOD tracks without downcasting to the specific class and calling specific functions.
=> Differenciate selectors for proper input type

EMCAL/EMCALbase/AliEMCALTriggerDCSConfig.cxx
There was a typo confusing operator = with ==. Fixing compiler warnings spotted with clang.
=> Fixing small typo in operator==

TRD/TRDbase/AliTRDmcmSim.cxx
This addresses [ALIROOT-7622].
Unprotected access to hits array which triggers out-of-bound
access in case of too many hits.
=> Fix out-of-bounds access to hits array for MC

STEER/STEER/AliHelix.cxx
* Revert "Limit helix DCA phase*r search to 100cm,"
This reverts commit 02d7155cb24af6e758644f0bf031eb22698d8afc.
* Revert "Make sure the helix phase is in -pi:pi range"
This reverts commit e14ba678c79924d16afd8326b393c3aaf863e26f.
See [ALIROOT-7685](https://alice.its.cern.ch/jira/browse/ALIROOT-7685)
=> Revert #558 and #561 following validation results

EVGEN/AliGenReaderEMD.cxx
Despite the large number of lines tagged as changed, in this commit I simply:
1) commented a warning print that was useless (but annoying)
2) most importantly, put a protection in NextParticle() method that forbid not well defined particle to be propagated to the stack for tracking.
I also would like to explain that this external reader generator reads ntuples from RELDIS generator (dedicated to EM dissociation events) and that it is NOT used if not by myself for local productions since the RELDIS ntuples are not widely distributed.
I thank in advance whoever will allow this changes to be ported to the release.
Regards, ch.
=> Commenting prints and putting a protection for undefined pc in NextParticle 

RAW/RAWDatarec/AliRawReader.cxx
This commit allows to select trigger classes using multiple selection of type "contain", which are treated in OR. 
For example one can run the rec.C with the option "?Contain=CCUP || CTRUE" to reconstruct the events of all the trigger classes CTRUE* and CCUP*.
With this feature, in the future, reconstructions of specific triggers should be easier to configure.
For example, the LHC15o reprocessing of ALIROOT-7611, which required 2 separate cycles, can be done in one cycle with the modified code.
=> Possibility to use multiple contain selections on trigger class

EVGEN/AliGenParam.cxx, EVGEN/AliGenParam.h
This PR adds a simple way to configure AliGenParam to inject a particular particle species directly from an interpreted macro.
Due to a limitation of CINT it is not possible to pass an interpreted function to a library function, meaning that any new injection scheme would require adding a piece of code in AliRoot/AliPhysics instead of simply hacking the AliDPG repository.
This makes easier to replace AliGenBox with AliGenParam since now the functionality is the same with this new constructor.
@akalweit
=> Add the possibility of injecting single particle species via macro configuration

ITS/ITSbase/AliITStrackerSA.cxx, STEER/ESD/AliESDEvent.cxx, STEER/ESD/AliESDEvent.h
Between 2015 and 2017 in absence of TPC only ITS pureSA tracks were reconstructed.
This created some problem in filtering/analysis, therefer we reverted this behaviour to reconstruct
only complementarySA in absence of TPC (they will be physically equivalent to pureSA in this case).
For already reconstructed data we redefine the pureSA flag on the fly in the AliESDEvent::ConnectTracks
=> In events w/o TPC we want to get only complementary ITS_SA tracks

STEER/AOD/AliAODTrack.h, STEER/ESD/AliESDtrack.cxx
This commit is aimed at properly setting the TPC chi2 when converting an AOD track into and ESD track using the constructor AliESDtrack(const AliVTrack *track). 
It is a modification in two classes:
1) AliAODTrack to add an helper method to compute the TPC chi2 from the chi2perNDF, by reversing what done in AliAnalysisTaskESDfilter::Chi2perNDF
2) AliESDtrack to set the TPC chi2 in the constructor that creates the track from an AliVTrack
=> TPC chi2 set in AliESDtrack(AliVTrack*) constructor

ANALYSIS/ANALYSISalice/AliESDtrackCuts.h, ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx, ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.h, ITS/ITSbase/AliITStrackerSA.cxx, STEER/ESD/AliESDEvent.cxx, STEER/ESD/AliESDEvent.h
In absence of TPC only ITS pureSA tracks are reconstructed, while the ESD->AOD filtering usually accepts only complementary ITS_SA track. This patch detects such events and redefines all cuts requesting compl. ITS_SA tracks to accept ITS_pureSA track. In the end of the event the cuts are restored.
=> In events w/o TPC filter ITS_pureSA tracks as complementary ITS_SA 

STEER/AOD/AliAODTrack.cxx, STEER/AOD/AliAODTrack.h, STEER/ESD/AliESDtrack.cxx
This commit is aimed at properly setting the track impact parameter when converting an AOD track into and ESD track using the constructor AliESDtrack(const AliVTrack *track).
It is a modification in two classes:
1) AliAODTrack to add the methods to compute the impact parameter and its uncertainty (following advices and suggestions from Ruben)
2) AliESDtrack to call the calculation and to set the impact parameter in case the track passed to the AliESDtrack(const AliVTrack *track) constructor is an AliAODTrack.
=> Set impact parameter in conversion from AOD to ESD tracks

CMakeLists.txt
This fixes the DA RPMs generation and SHUTTLE builds with the native SLC6 compiler while allowing modern C++ on unneeded modules.
No change in the AliRoot recipe is needed.
@chiarazampolli @sy-c @Barthelemy @jniedzie
=> Disable unneeded modules on DARPM/SHUTTLE builds

ITSMFT/ITS/ITSUpgradeSim/AliITSUv2.cxx, ITSMFT/ITS/ITSUpgradeSim/AliITSUv2Layer.cxx, ITSMFT/ITS/ITSUpgradeSim/AliITSUv2Layer.h
Porting from O2 to AliRoot the main updates to the IB geometry: namely
- fix some dimensions (particularly important, the gap between chips)
- update the End Stave connectors (no metal inserts)
- implement the FPC capacitors
Moreover the creation of the support structure is temporary disabled to avoid big overlaps.
=> Backporting from O2 the main updates on IB geometry

ANALYSIS/ANALYSISalice/AliESDtrackCuts.cxx, STEER/ESD/AliESDtrack.cxx
These commits allow to apply the "full" set of cuts of AliESDtrackCuts::AcceptTrack on AOD tracks after converting the to AlIESDtrack.
Two classes are modified:
1. AliESDtrack: to copy the ITS chi2 from the AOD to the ESD track in the constructor AliESDtrack(const AliVTrack *track)
2. AliESDtrackCuts: to do in AcceptVTrack the conversion from AOD to ESD track setting all the variables used in the track selection
NOTES:
* the kink daughter rejection is applied directly on the AOD track  before converting it to ESD track
* the golden chi2 is retrieved from the value stored in the AOD track instead of recomputing it on the fly as for the ESD tracks
* the geometrical length cut is applied using the track parameterization at the vertex because the one at the inner radius of teh TPC is not …
=>  Improved conversion from AOD to ESD track for track selection

TPC/TPCcalib/AliTPCDcalibRes.cxx
- sign(x) is not recognized in ROOT6
- fitting function needs proper initialization (ROOT6 is delicate in fitting)
=> Fixes for ROOT6 - fitting function definition + inizialization of fit

THijing/AliGenHijing.cxx
As stated in the commit message, the UniqueID was not retrieved in the loop where particles are written in the stack, but in the case where the data driven spectator fragmentation is applied, this would imply that all the spectators are written in the stack as coming from the target (the last value of the previous loop being used).
This change is therefore important and need to be pulled asap!
Thanks a lot, 
ch/
=> Bug fix: particle UniqueID was not retrieved before writing stack!

EMCAL/EMCALUtils/AliEMCALRecoUtils.cxx, EMCAL/EMCALUtils/AliEMCALRecoUtils.h
Ownership handling of calibration object was completely
messed up (pointer to array set, outer lifetime ignored).
Now the AliEMCALRecoUtils object takes care of the ownership
of the calibration objects itself and the deletion.
=> [EMCAL-135] Fix messing around with ownership

TPC/TPCcalib/AliTPCcalibAlignInterpolation.cxx, TPC/TPCcalib/AliTPCcalibAlignInterpolation.h
The AliTPCcalibBase::Process(AliESDEvent*) was changed to Process(AliVEvent*) during adaptation of calib framework
to flat containers/HLT, but the derived AliTPCcalibAlignInterpolation::Process was not modified. As a result, the
derived method is not called and the residual trees are not produced.
At the moment fixing just by dynamic_cast from AliVEvent to AliESDEvent, so the task will do nothing on the HLT.
=> Fix: update AliTPCcalibAlignInterpolation::Process argument to AliVEvent

STEER/STEERBase/AliOADBContainer.cxx
Since InitFromFile sets ownership over pass name
container (#622) when setting the target object a
deep copy of the pass name has to be performed in
any case, otherwise the container will crash when
accessing the pass name while retrieving the
corresponding object from the container.
=> [EMCAL-135] Fix deep copy in pass names

STEER/STEERBase/AliTRDPIDParams.cxx, STEER/STEERBase/AliTRDPIDParams.h
A constructor had to be added to AliTRDPIDParams.cxx. Otherwise the 'test' object in the GetThresholdParameters() function is not initialized correctly and thus the function does not return the correct threshold parameters for the PID.
Additionally, an output of the threshold parameters was added to the Print() function, to simplify debugging and analysis.
=> Fix in STEER/STEERBase/AliTRDPIDParams.cxx

EVGEN/AliGenMC.cxx
This PR adds to AliGenMC::Boost() function the boost of the particle production vertex (4-vector).
This comes on top of the already-existing boost of the 4-momentum.
=> Boost also the production vertex of particles

EMCAL/EMCALbase/AliEMCALTriggerSTUDCSConfig.h
Renaming function arguments in getter and setter
of the EMCAL L1 trigger thresholds in order to
indicate the meaning of the parameter (i and j
not meaningful variable names). No functional
change in the code.
=> [Rename] Rename function arguments

STEER/ESD/AliESDEvent.cxx, STEER/ESD/AliESDEvent.h
The trigger time stamp uses 1st scaler record as a reference and assumed that no trigger
may appear before this scaler. This apperars not to be true.
Added extra method AliTimeStamp AliESDEvent::GetAliTimeStamp() to extract precise
timestamp with ms precision
=> fix CTP TimeStamp: triggers may be ahead of 1st scaler

HLT/TRD/tracking/AliHLTTRDTrack.cxx, HLT/TRD/tracking/AliHLTTRDTrack.h, HLT/TRD/tracking/AliHLTTRDTracker.cxx, HLT/TRD/tracking/AliHLTTRDTracker.h, HLT/TRD/tracking/AliHLTTRDTrackerComponent.cxx, HLT/TRD/tracking/AliHLTTRDTrackerDebug.h
Only TPC tracks with ITS hits can be considered for HLT TRD tracking without the usage of std::vector::erase() to make it faster. Small typos for the debug output were fixed.
=> Add possibility to require ITS match for TRD tracking seeds

EMCAL/EMCALbase/AliEMCALTriggerRawDigit.cxx
everything is in the title, should fix the old standing EMCAL-39 ticket.
@mfasDa  should be enough to remove the Fatal (to be turned into an Error?) in the TriggerElectroncis constructor, do you think we should include that in the same PR?
=> fix L0 time array overflow due to null L0 threshold from OCDB EMCAL-39

EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx
As in #651 a protection against the buffer overflow
resulting from 0-thresholds was introduced, the log
severity can be removed from Fatal to Error resulting
that the code will not crash any more in case a 0-
threshold is found.
=> [EMCAL-39] Relax severity from Fatal to Error

TRD/TRDbase/AliTRDcalibDB.cxx
in case of detecting different Kr gain table names
=> Fix: for 285364<=run<285621 produce Error instead of Fatal

EMCAL/EMCALbase/AliEMCALTriggerTRUDCSConfig.cxx
In order to compare to original files the bitwise
representation is not of help as the original values exist
only in decimal represenation. Therefore both decimal
and bitwise representation are displayed.
=> [EMCAL-179] Display dec representation of reg mask

TDPMjet/TDPMjet.cxx, TDPMjet/TDPMjet.h
This should solve the problem with events containing un-decayed pi0 leading to a wrong 
Dalitz mee distribution 
(https://alice.its.cern.ch/jira/browse/ALIROOT-7792)
=> Repeat event generation in case event was rejected.

STEER/STEERBase/AliTRDPIDParams.cxx, STEER/STEERBase/AliTRDPIDResponse.cxx
- add output in AliTRDPIDParams::AliTRDPIDCentrality::GetThresholdParameters() that gives error message when threshold parameters are set to default values  (-999) as necessary for LHC17n
- ensure that return value of AliTRDPIDParams::AliTRDPIDCentrality::GetThresholdParameters() is passed over correctly to AliTRDPIDResponseObject::GetThresholdParameters()
- ensure that AliTRDPIDResponse::IdentifiedAsElectron() only returns default kTRUE if no parameters are available
=> TRD PID Parameters: adapt response of code when threshold parameters not available

ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx, STEER/AOD/AliAODEvent.h, STEER/AOD/AliAODHeader.cxx, STEER/AOD/AliAODHeader.h, STEER/AOD/AliNanoAODHeader.h, STEER/STEERBase/AliVAODHeader.h, STEER/STEERBase/AliVEvent.h
In order to filter for HV dip events in the TPC, the Detector status
flags need to be propagated to AODs.
This also unifies the treatment of the detector flag testing between the
different event types. A virtual function was added in AliVEvnet which
retruns 'true' by default in the detector on check. It is then
overridden by the ESD and AOD implementation
=> Propagate DetectorStatus to AODs

ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx, STEER/AOD/AliAODVertex.cxx, STEER/AOD/AliAODVertex.h
The AODVertex made from primary VertexTracks will get NContributors assigned from the ESDvertex.
Old behaviour of counting stored primary daughters may be enforced using static method
SetUseCountVtxTrackContributors(kTRUE); // off by default
For old AODs, where fNContributors was not stored, GetNContributors will fall back to old way of counting.
=> Treat AliAODVertex::GetNContributors like in ESDVertex

STAT/AliExternalInfo.cxx, STAT/Macros/aliExternalInfo.C, STAT/Macros/aliExternalInfo.sh
* STAT/Macros/aliExternalInfo.C, STAT/Macros/aliExternalInfo.sh
* Use compiled macro instead of normal in extended interface example
* protection against empty data
* agregated  information to be automatically posted on the web page http://aliqamodafs.web.cern.ch/aliqamodafs
````
QA.MCRun.location http://aliqamodafs.web.cern.ch/aliqamodafs
QA.MCPeriod.location http://aliqamodafs.web.cern.ch/aliqamodafs
QA.Run.location http://aliqamodafs.web.cern.ch/aliqamodafs
QA.Period.location http://aliqamodafs.web.cern.ch/aliqamodafs
````
* TODO - run cronjob at afs
* protection against NULL file pointer TFile:Open
* disable loading of metadata in case of "production caching"
* use Info only in case of verbose mode
* Speed up - minimizing calls for the fLogCache->GetEntry
* before call was done in …
=> ATO-83, ATO-46  - AliExternalInfo modifications (MC/Anchor guess)+ more examples

EVGEN/AliGenParam.cxx
affects
v5-08-13zl-cookdedx-1
v5-08-13zk-cookdedx-1
v5-08-13q-p13-01-1 
v5-08-13q-p12-01-1
v5-08-13q-p13-01-cookdedx-1
v5-08-13q-p13-01-cookdedx-1
but can only have an effect on MC production  in case of injected signal production with AliGenParam.
=> bug in determination of fIncFortran corrected

EMCAL/EMCALTriggerBase/AliEMCALTriggerOnlineQAPbPb.cxx
This PR should fix the issue reported in EMCAL-212.
I believe it is caused by events that have no background patches. This should be quite rare in PbPb collisions, which is probably why it was not spotted before.
=> [EMCAL-212] Fix FPE exception

ITSMFT/ITS/ITSUpgradeRec/AliITSUTrackerGlo.cxx
Hi @shahor02,
I introduced a trivial bug with the previous PR, in principle now the cluster sorting will be performed once for both CA and Global Tracker (as it was intended to be in the first PR, but the return was before the sorting of the clusters).
Can you please check if this works for you?
Cheers,
Max
=> Fix trivial bug introduced in #683

ZDC/ZDCsim/AliZDCDigitizer.cxx
The relevant change is a minor one and only takes into account the fact that in the conversion from float to integer we were always rounding to the smaller integer. It would be nice to have it corrected.
ch
=> Adjusting no. of photoel. to ADC ch. conversion (minor)

STAT/AliNDFormulaBrowser.cxx, STAT/Macros/AliExternalInfo.cfg, STAT/Macros/AliNDFunctionInterface.cxx, STAT/Macros/AliNDFunctionInterface.h, STAT/Macros/QAtrendingFitExample.C
ATO-445 - Interface for NDimensional function representation TMVA and THn
static implementation enable usage of EvalMVA in the TFormula and TTreeFormula
* variadic function to create vector and evaluate regression
* Interface for the THn interpolation
* linear interpolation of the THn content
* Interface for the TMVA based regression representation
* FitMVA
* LoadMVAReader
* EvalMVA
Example code using AliNDFunctionInterface for TMVA regression of QA data
* Code is still experimental. User interface can change
* C++11 features are used here. For the moment only compiled macro
* For the moment only root6 TMVA interface supported
* To check if root5 can be also supported
=> ATO-445 - Interface for NDimensional function representation TMVA and THn)

TPC/TPCbase/AliTPCcalibDB.cxx, TPC/TPCbase/AliTPCcalibDB.h
Add possibility to retrieve extended dead channel map information.
This is added for the QA and will only be filled if the QA information
is requested.
It fills separate maps for the different contributions:
* high voltage
* DDL list
* Altro channel map
* space-charge distortions
=> Extended dead channel map information

TPC/TPCsim/AliTPCDigitizer.cxx
Memory leaks in method DigitizeWithTailAndCrossTalk of AliTPCDigitizer were found and fixed.
=> Fix memory leaks in DigitizeWithTailAndCrossTalk

STEER/ESD/AliESDEvent.cxx, STEER/ESD/AliESDEvent.h
The GetAliTimeStamp and GetTimeStampCTPBCCorr (changed to double) will return the time-stamp
precise up to the BC. Note that rarely the 1st CTP scaled is not in sync with the actual CTP start,
in this case the CTP time stamp may be wrong. If it cannot be calculated, the GetTimeStamp (event building time)
will be assigned and the AliTimeStamp (from GetAliTimeStamp) will have GetUniqueID() == 1 (in case of success it is 0)
=> TimeStamp precise up to the BC

ITS/ITSsim/AliITSv11GeometrySSD.cxx
This fixes an issue with deletion order in the SSD geometry: the objects in a TList were deleted before the TList was deleted; this causes a problem because the TList accesses the objects to read a deletion flag when the TList itself is deleted. This was mostly a formal problem, but best to fix it anyways.
=> Fix deletion order issue in SSD geometry

ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx, STEER/AOD/AliAODTrack.h
Details in https://alice.its.cern.ch/jira/browse/ALIROOT-7874?focusedCommentId=217574&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-217574
Also, AliAODTrack methods like GetTPCmomentum() which extract the info from the fDetPid will fall
back to the track momentum in absence of the fDetPid (like it is done in the AliESDtrack)
=> Fix: AODtracks added via ConvertTRD should have fDetPid filled

HLT/BASE/CMakeLists.txt
@dberzano : The file you mention in the mail was indeed missing (a different issue than the include path issue you are solving).
This PR should fix it, no guarantuee that there aren't more files missing.
=> install missing include file

HLT/EMCAL/AliHLTEMCALTriggerMaker.cxx
As discussed in the ticket digits with coordinates out-
of-range will be ignored as they are coming from
corrupted data. Instead an HLTError will be raised.
For the range check the internal boundary check of
function GetAbsCellIdFromCellIndexes is used and its
return value -1 is handled in the function AddDigit.
=> [EMCAL-214] Adding range check for invalid digit coordinate

STAT/AliTreePlayer.cxx, STAT/AliTreePlayer.h
*  Load tree and append friend trees
* functionality used previously in macros  to compare performance map parameterization
````
TTree* AliTreePlayer::LoadTrees(const char *inputDataList, const char *chRegExp, const char *chNotReg, TString inputFileSelection, TString axisAlias, TString axisTitle)
````
*  inputDataList          - command returning input data list - line with #tag:value for the metadata definition
*  chRegExp               - regular expression  - trees to include
*  chNotReg               - regular expression  - trees to exclude
*  inputFileSelection     - : separated input file selection
*  axisAlias              - axis names
*  axisTitle              - axis titles
* return                  - resulting tree
* Load trees with parameterization  projections 0_1_3   - …
=> ATO-382 - AliTreePlayer::LoadTrees

HLT/VZERO/AliHLTVZEROAgent.cxx, HLT/VZERO/AliHLTVZEROLinkDef.h, HLT/VZERO/AliHLTVZEROOnlineCalibComponent.cxx, HLT/VZERO/AliHLTVZEROOnlineCalibComponent.h, HLT/VZERO/CMakeLists.txt, HLT/VZERO/macros/HLTVZeroCalibTest.C, HLT/VZERO/macros/runVZeroCalibTest.sh, HLT/global/AliHLTGlobalPromptRecoQAComponent.cxx
Requested by VZero, so that they have a starting point to develop online calibration to adjust trigger thresholds immediately after the run to compensate for detector aging.
=> Add Skelleton for VZERO online calibration component in the HLT

HLT/TPCLib/AliHLTTPCLog.cxx, HLT/TPCLib/AliHLTTPCLog.h
the legacy class uses a singleton of a singleton which does not clean up correctly, and it cannot be moved to the modern method since it is used in static class members. Just tried to fix it properly for an hour but failed... So we just leak the std::stringstream of the singleton...
=> fix double delete in HLT TPC code

EMCAL/EMCALUtils/AliCaloConstants.h, EMCAL/EMCALraw/AliCaloRawAnalyzerFactory.cxx, EMCAL/EMCALraw/AliCaloRawAnalyzerKStandardFast.cxx, EMCAL/EMCALraw/AliCaloRawAnalyzerKStandardFast.h, EMCAL/EMCALraw/CMakeLists.txt, EMCAL/EMCALraw/EMCALrawLinkDef.h, HLT/CALO/AliHLTCaloRawAnalyzerComponentv3.cxx, HLT/CALO/AliHLTCaloRawAnalyzerComponentv3.h, HLT/EMCAL/AliHLTEMCALAgent.cxx, HLT/EMCAL/AliHLTEMCALDigitsMonitorComponent.cxx, HLT/EMCAL/AliHLTEMCALLinkDef.h, HLT/EMCAL/AliHLTEMCALRawAnalyzerStandardFastComponent.cxx, HLT/EMCAL/AliHLTEMCALRawAnalyzerStandardFastComponent.h, HLT/EMCAL/CMakeLists.txt
Two steps found to speed up the EMCAL raw analyzer / raw fitter
- Replace in-loop dynamic allocations of memory in raw fitter by class member objects 
- Cache ALTRO mapping in raw analyzer component and pass it over to the calo raw stream in order to have the expensive read operation of the ALTRO mapping from disk only once
Now profilers show that the performance of the raw analyzer is dominated by the least square fit.
=> [EMCAL-369] Speedup of raw fitter for HLT

EVGEN/AliDecayer.h, PYTHIA6/AliPythia6/AliDecayerPythia.cxx, PYTHIA6/AliPythia6/AliDecayerPythia.h
Create a new case: kHFYellowReport, for HF upgrade production with new B0  and Lambda_b decay channels forced.
=> New B and Lambda_b decays added for HF upgrade production

TOF/TOFrec/AliTOFtracker.cxx
`operator=()` does not work properly any longer if a null pointer is passed as
value. The intended behaviour is to invoke `Clear()` to the given instance of
`TGeoHMatrix`. This fix in AliRoot makes it work as intended without waiting for
a fix in ROOT.
=> Work around TGeoHMatrix bug in ROOT v6-14-04

HLT/BASE/HOMER/AliHLTHOMERReader.cxx, HLT/BASE/HOMER/AliHLTHOMERReader.h
Move rpc.h to .cxx, since on the GRID we might compile on a
different OS than we run, and ROOT will face compatibiltiy
issues parsing the header otherwise.
=> Fix processing with ROOT6

T0/T0calib/AliT0AnalysisTaskQALegacy.cxx, T0/T0calib/AliT0AnalysisTaskQALegacy.h, T0/T0calib/CMakeLists.txt, T0/T0calib/T0calibLinkDef.h
Task with the same name exists in AliPhysics and creates conflicts, see errors
in alisw/AliPhysics#6635
=> Rename conflicting AliT0AnalysisTaskQA to *Legacy

ANALYSIS/ANALYSIS/AliAnalysisManager.cxx
Since the introduction of automatic library loading and rootmaps, this
functionality should not be needed any longer, see ALIROOT-7936
=> Disable CheckTasks() in ROOT 6

STEER/ESD/AliESDEvent.cxx, STEER/ESD/AliESDtrack.cxx
Modification needs for transfer of ESDtrack from one event to another during
filtering of the event from MC embedding
=> Allow skipping TOF match update when copy to new ESDEvent

HLT/BASE/HOMER/AliHLTHOMERReader.cxx, HLT/BASE/HOMER/AliHLTHOMERReader.h
The previous fix alisw/AliRoot#757 was incomplete, as the other headers pull in rpc.h by themselved
=> Fix ROOT6 processing, interpreter cannot process these headers

HLT/EMCAL/AliHLTEMCALRawAnalyzerComponentTRU.cxx, HLT/EMCAL/AliHLTEMCALRawAnalyzerComponentTRU.h
The ALTRO raw stream is constructed for every event and
therefore always reads the same ALTRO mapping from a text
file from disk. As the altro mapping doesn't change it is
can be cached in memory and passed to the raw analyzer
from cache, which is a significantly faster operation than
reading it from disk.
=> [EMCAL-402] Cache ALTRO mapping in the TRU raw analyzer

STEER/STEERBase/AliMCEvent.cxx, STEER/STEERBase/AliMCEvent.h, STEER/STEERBase/AliStack.cxx, STEER/STEERBase/AliStack.h
If the ESD is obtained by filtering embedded signal from the MC-2-MC production
it may contain some labels belonging to the underlaying event tracks (i.e. offsetted
by 10M). The result of the query of AliMCEvent::GetTrack(label) on such a label depends on:
1) if the galice.root of the embedding production was also distilled (the reference on the
bg. event path is removed), then a dummy AliMCParticle will be returned, made from
TParticle dummy(21,999,-1,-1,-1,-1,1,1,999,999,0,0,0,0).
Also, calls to IsPhysicalPrimary, IsSecondaryFromWeakDecay, IsSecondaryFromMaterial will return FALSE,
while IsFromBGEvent will return TRUE.
The call to GetGenerator will return TString("suppressed")
2) the galice.root refers to valid directory with the underlying event: proper MCParticle is retrieved
=> Return dummy track for query of ebm.bd. label in absence of subsidiary event

ANALYSIS/ANALYSIS/AliAnalysisManager.cxx
Simpler version instead of alisw/AliRoot#768
@dberzano : How about this check, which is actually much simpler (but slower as it does string compares).
=> Workaround avoiding gROOT->ProcessLine() in a simpler way

HLT/VZERO/AliHLTVZEROOnlineCalibComponent.cxx
Histograms created in some directory is destroyed when the directory is deleted. To avoid
invalid pointers the histos should be placed in the top ROOT dir.
=> Place member TH1 to top root directory

STAT/Macros/AliNDFunctionInterface.cxx, STAT/Macros/AliNDFunctionInterface.h, STAT/Macros/QAtrendingFitExample.C
* modifying user interface for TMVA regression
* adding output filte/directory specification
* grouping variables and weights
* iteration coding removed (used e.g for bootstrapping) can be done
modifying output name
* Updated doxygen documentation
* Updated test (QAtrendigFitExample.C) for modified interface
* Fix "errors" reported by CLIon
* camel convention of variable names
dab2acd
* Add new interface 
* https://github.com/alisw/AliRoot/commit/f0d207536ec401d5350835d5c2bb8d3223125105
* Test old/new interface (the same results)   
* https://github.com/alisw/AliRoot/commit/426dda37554b2d82ab94f4903329c5d5d91f4d63
* Removed old interface 
* https://github.com/alisw/AliRoot/commit/dab2acdaf0cd6147649426d697a51273f6ac8709
=> ATO-445-TMVA regression (NON BACK COMP. CHANGE) + classification (ADD)

EVGEN/AliGenMC.cxx, EVGEN/AliGenMC.h, PYTHIA6/AliPythia6/AliGenPythia.cxx, PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx, TAmpt/TAmpt/AliGenAmpt.cxx, TDPMjet/AliGenDPMjet.cxx, THijing/AliGenHijing.cxx
AliGenMC::Boost() method assumes m/s for length/time units. In case the generator
uses other units it must set the AliGenMC::SetGeneratorUnitsForMeterSecond(lgtC, timeC)
with lgtC and timeC being the coefficients translating generator's units to m/s.
=> Generators will tell its length/time units to AliGenMC for Boost method

ALIROOT/CMakeLists.txt, ALIROOT/aliroot.cxx
The `aliroot` executable produced with ROOT 6 now depends solely on `STEERBase`
because of the `AliLog` class: initialization of `gAlice` is now performed
through the ROOT interpreter at runtime.
This works around a problem seeing `aliroot` stuck in an infinite mutex loop
on SLC6. The problem is likely due to a bug in an old glibc. See ALIROOT-7993.
=> Remove most libdeps from the aliroot executable

HLT/BASE/util/ZMQROOTmerger.cxx
+change of logic to allow the user to shoot himself in the foot when
directly merging collections - this is SLOOW and leaks due to ROOT's
(lack of) ownership model.
=> Unpack collections by default in the merger

HLT/ITS/tracking/AliHLTITSTrack.cxx, HLT/ITS/tracking/AliHLTITSTrack.h, HLT/MUON/AliHLTMUONCountedList.h, HLT/MUON/AliHLTMUONList.h, HLT/trigger/AliHLTTriggerCounterComponent.cxx, HLT/trigger/AliHLTTriggerCounterComponent.h, TTherminator/Therminator/ReadPar.cxx, TTherminator/Therminator/ReadPar.h
Although AliRoot is not build against c++17 yet, these exception specifications are obsoleted and totally unncessary. Btw, after these changes AliRoot works with c++17.
=> remove deprecated dynamic exception specifications incompatible to c++17

TPC/TPCcalib/AliTPCDcalibRes.cxx
This makes it safer when we upload the vdrift OCDB during processing.
=> Adding mirror SE for OCDB uploads.

HLT/BASE/AliHLTSystem.cxx, HLT/CMakeLists.txt, HLT/TPCLib/AliHLTTPCAgent.cxx, HLT/TPCLib/AliHLTTPCClusterAccessHLTOUT.cxx, HLT/TPCLib/AliHLTTPCClusterAccessHLTOUT.h, HLT/TPCLib/AliHLTTPCClusterTransformation.cxx, HLT/TPCLib/AliHLTTPCClusterTransformation.h, HLT/TPCLib/AliHLTTPCClusterTransformationComponent.cxx, HLT/TPCLib/AliHLTTPCClusterTransformationComponent.h, HLT/TPCLib/CMakeLists.txt, HLT/VZERO/AliHLTVZEROOnlineCalibComponent.cxx, HLT/VZERO/macros/HLTVZeroCalibTest.C, TPC/TPCrec/AliTPCReconstructor.cxx, TPC/TPCrec/AliTPCReconstructor.h, TPC/TPCrec/AliTPCclusterer.h, TPC/TPCrec/AliTPCtracker.cxx, TPC/TPCrec/AliTPCtracker.h
This requires AliTPCCommon >= v1.4
@dberzano : This will require people to update their alidist. Merging is not urgent. Could you please pull it in whenever it seems suited for you.
@shahor02: The changes to AliTPCTracker are completely inactive if you do not set AliTPCReconstructor::SetUseHLTTracks(), so it will not affect normal reconstruction, but if you want you can have a look and double-check.
=> [WIP] Utilize new features of AliTPCCommon (fast transform, HLT tracks in offline, ...)

EVGEN/AliGenReaderEMD.cxx, EVGEN/AliGenReaderEMD.h, EVGEN/AliGenReadersEMD.cxx, EVGEN/AliGenReadersEMD.h
This commit could be included in the release to run with RELDIS code (EM dissociation events in A-A collisions), some minor changes were included to comply with the outputs provided by Igor for 5.11 TeV (the current version can be used only with inputs calculated for 2.76 TeV since some changes were introduced in between).
Thanks for the help.
Chiara
=> Updating reader for RELDIS events

EMCAL/EMCALbase/AliEMCALCalibBadChannels.cxx, EMCAL/EMCALbase/AliEMCALCalibBadChannels.h, EMCAL/EMCALbase/CMakeLists.txt, EMCAL/EMCALbase/EMCALbaseLinkDef.h
Container in same format as the OADB container (20 2D
histograms with ieta-iphi), however stored in the OCDB
as OCDB object. Needed for the HLT.
=> [EMCAL-405] New OCDB object for bad channel histograms

STEER/STEER/AliGenerator.cxx, STEER/STEER/AliVertexGenFile.cxx, STEER/STEER/AliVertexGenFile.h, STEER/STEER/AliVertexGenerator.h
AliVertexGenFile used to pass the vertex from the underlying bg. event to the signal event being embedded to the bg, must pass also the fTime (smearing of the interaction time due to the finite size of the interaction diamond) used to generate the bg. event. Otherwise there is a ```sigma_VZ/c ``` time smearing between the data signal and bg. event
=> AliVertexGenFile will provide also the time

STEER/STEERBase/AliDataFile.cxx
When looking for data files on CVMFS, ignore any version tag that comes after
an underscore. If version is `vAN-20181021_ROOT6-1`, then it is converted to
`vAN-20181021`: both build number and the `_ROOT6` tag are ignored.
=> Make AliDataFile ignore AliPhysics version tags

STEER/STEERBase/AliPIDResponse.cxx, STEER/STEERBase/AliPIDResponse.h, STEER/STEERBase/AliTRDPIDResponse.cxx
Instead of giving Output for every Call of IdentifiedAsElectron, Information about missing Parameters will now only be shown once
=> Reduction of Output for TRD Parameters

STEER/STEERBase/AliPIDResponse.cxx
If there is not only no Parameters in the TRDPIDResponseObject, but no TRDPIDResponseObject at all, the code crashes. 
Includes an additional if check, if fTRDPIDResponseObject exists
Also removed one AliError, for better understanding of the Code
=> Hotfix: Check if File exists! If no TRD Response exists

STAT/AliFFTsmoother.cxx, STAT/AliFFTsmoother.h, TPC/TPCsim/AliTPCTrackHitsV2.cxx, TPC/TPCsim/AliTPCTrackHitsV2.h
* simplified version of outlier frequency filter
* user defined frequency to replace 
* possible to code in short t code up to 10**8
* needed for magnetic monopole simulation
* coding formula:
````
q*=base*log(1+q/base)
````
* limit case
* q*~q      at q<<base (3000)
* q*~ln(q)  at q>>base
=> ALIROOT-7077+ATO-453 - non liner coding of charge

TPC/TPCsim/AliTPC.cxx
Needed for magnetic monopoles
* void AliTPC::MakeSector
* do electron transport for group of electrons
* for low Q<150 el group size=1 => simulation as always
* for higher Q (monopoles) group size Q/100
* Using clion auto-indentation in affected routine
=> ATO-453 - speedup of the response simulation for high dEdx particles

EVGEN/AliGenExtExec.cxx, EVGEN/AliGenExtExec.h
Hi,
This commit allows generic optional arguments for the generator and should be fully backward-compatible. In the default setting, no functionality was changed.
The idea behind this is to give the configuration (for JEWEL) directly as parameters instead of hard-coded files. The parameters will be passed as a string to the external generator script.
I have another pull request in AliPhysics that will add the corresponding JEWEL generator files, which is tested and worked fine locally.
Best,
Ruediger
=> Add optional parameters for external MC generators

STEER/CDB/AliOCDBtoolkit.cxx, STEER/CDB/AliOCDBtoolkit.h
* /// \param fileName         - OCDB snapshot file name .e.g OCDBsim.root or OCDBrec.root
* /// \param objectName       - OCDB entry name  e.g TPC/Calib/recoParam
* /// \param foutput          - output file name - e.g TPC_Calib_RecoParam.xml
* /// \param dumpMetaData     - switch dump also metadata
* /// \param printOption      - MI, xml, docdb (obejct dump) , pocdb (object print)
Example usage:
````
AliOCDBtoolkit::DumpOCDBFile("/lustre/nyx/alice/users/miranov/NOTESData/alice-tpc-notes/JIRA/ALIROOT-7077/test1211_PbPb_MCTail_2_2/OCDB/OCDBrec.root", "TPC/Calib/RecoParam", "TPC_Calib_RecoParamReco.xml",1,"XML")
````
=> ATO-452, ATO-15 : adding AliOCDBtoolkit::DumpOCDBFile - from snapshot

TTherminator/AliGenTherminator.h
avoid multiple inclusion and multiple definition, problem spotted when loading generator macro's under root6
in any case, these functions should be implicitly inlined
=>  move inlined functions in the header to within the include guards to

HLT/EMCAL/AliHLTEMCALClusterMonitor.cxx
Invariant mass distribution dominated by background, particularly
for most central collisions, energy cut needed to enhance the
signal/background.
=> [EMCAL-33] Apply energy cut on the clusters for invariant mass

EMCAL/EMCALTriggerBase/AliEMCALTriggerOnlineQAPbPb.cxx
For checking the online bits the MC offset needs to be taken into
account, otherwise the patches are not idenfied. Fixing filling
histograms with online patches in the PbPb trigger QA component
on the HLT.
=> [EMCAL-409] Add MC offset for online patches

ZDC/DA/ZDCMAPPINGda.cxx
This change is important since it prevents the wrong handling of TDC data in DA needed for timing calibration object. It would be important to have it running at P2 for Pb-Pb...desperate attempt, but nevertheless if it could be ported we could ask for deployment at P2
=> Fixing a bug in ZDC MAPPING DA related to TDC data streaming

EMCAL/EMCALrec/AliEMCALReconstructor.cxx
Same iterator index "idig" used in loop and other loop inside used to reinitialized the trigger raw sample.
Move an MC related line before the trigger code part.
=> fix iterator index name and lines orderning

ITS/ITSbase/AliITStrackMI.h
With ill-formed covariance matrix once in a while negative chi2 is assigned, leading to FPE afterwards
=> Protection against assigning chi2<0

ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx, ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.h
Bring the esd filter to the level that potentially one could switch to use of outer param when creating the AODs, and also implemented a switch to use mass hypothesis rather than pion mass always.
By default, all settings are like they have been used so far.
=> [EMCAL-406] Track prop to Emcal using outer param. Off by default.

TOF/TOFsim/AliTOFTrigger.cxx
We prefer to remove TOF active mask selection both in data and MC processing to have better control over potential inconsistencies in the TOF active mask stored in DCS and actual active map used in online trigger decisions. We'll apply this mask manually in the offline analysis.
We also shift tof trigger times for LTM=64 and 65 to align them with other LTMs and avoid possible loss of hits in these channels. This approach has been proved to work in raw data analysis.
=> Remove TOF active mask in fired TOF trigger maps

ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx
Median value needs to be propagated to the AODs as well in order to be subtracted from from the raw patches at AOD level.
=> [EMCAL-408] Add Rho value to the AOD calo trigger object

HLT/TPCLib/comp/AliHLTTPCDataCompressionComponent.cxx, HLT/TPCLib/comp/AliHLTTPCDataCompressionComponent.h, HLT/TPCLib/transform/AliHLTTPCFastTransform.cxx
This disables some prototype code for Cluster Compression Studies.
It will be redone in AliTPCCommon for Run 3, but some of the AliRoot classes are relying on the old AliTPCCommon to pass TPC transformation parameters. These parts of the code are no longer used.
=> Disable deprecated features that will not be compatible to new AliTPCCommon

STEER/STEER/AliVertexGenerator.h
Fixes missing transfer of underlying event vertex time to embedded event, see
https://alice.its.cern.ch/jira/browse/ALIROOT-7654?focusedCommentId=222963&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-222963
=> BugFix: base virt. function signature differed from derived one

HLT/TPCLib/AliHLTTPCAgent.cxx
New feature of new AliTPCCommon tag to dump TPC clusters and TRD tracklets in new format for standalone tracking benchmark.
=> Enable AliHLTGPUDumpComponent in agent

EVGEN/AliDecayer.h, PYTHIA6/AliPythia6/AliDecayerPythia.cxx, PYTHIA6/AliPythia6/AliDecayerPythia.h
Decay mode added as extra option and is switched off
for existing targets, so there is no change of behaviour
for the existing settings. Four new targets including "PionicD0"
in the name are added in order to switch on the pionic D0
decay mode.
=> Adding option for decay mode D0->pi0 pi+ pi-

STEER/STEERBase/AliTPCPIDResponse.cxx, STEER/STEERBase/AliTPCPIDResponse.h
Reworked parametrization for dEdX dependence in PbPb to parabel + constant (after minimum), follows the curve much better than before. Inserted every change needed to include this possibility in AliTPCPIDResponse. Nothing changes for the user.
=> Add New parametrization for PbPb multiplicity dependence

PYTHIA6/AliPythia6/AliDecayerPythia.cxx
Using this channel in all Pi0-based configurations
for the Lambda_c decays.
=> Adding option to force Lambda_c into Lambda Pi+ Pi0

HLT/TRD/AliHLTTRDDefinitions.cxx, HLT/TRD/AliHLTTRDDefinitions.h, TRD/TRDbase/AliTRDtrackV1.h
- definition for TRD MC tracklet labels
- friend class declaration was for a class that is not used anymore, does not work with the new templated class
=> Add HLT TRD definition, remove old friend class declaration

ANALYSIS/ANALYSIS/AliAnalysisManager.cxx, ANALYSIS/ANALYSIS/AliAnalysisManager.h
For local analysis (and not only) a static method for creating
a chain would be useful as it would bypass the need of LoadMacro
workarounds in ROOT6
=> AliAnalysisManager : Add CreateChain static method

STEER/STEER/AliSimulation.cxx, STEER/STEER/AliSimulation.h, STEER/STEERBase/AliMCEventHandler.cxx, STEER/STEERBase/AliStack.h
AliSimulation::EmbedInto(path, NSig2Bg, RAWSTATUS) will flag the embedding as being done to raw
data if RAWSTATUS==kTRUE (default is FALSE). In this case the AliMCEventHandler will not try to load the kinematics of the background event as a subsidiary MC Event
=> Option to flag MC2RAW embedding

ITS/ITSbase/AliITStrackV2.cxx, ITS/ITSbase/AliITStrackerMI.cxx
fModule member of ITStrackV2 was not initialized, leading to random
values stored in the ESDtrack::fITSModule array.
When "extra" clusters were recorded, the module ID was not stored according
to the conventions of SetModuleIndexInfo.
=> Fix: avoid non-init members, set extra module info properly.

ANALYSIS/ANALYSISalice/AliEventPoolSparse.cxx, ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx, ANALYSIS/AliAnalysisGoodies.cxx, ANALYSIS/macros/AnalysisTrainFilterMC.C, ANALYSIS/macros/AnalysisTrainNew.C, ANALYSIS/macros/AnalysisTrainNewFilterAOD.C, ANALYSIS/macros/AnalysisTrainNewFilterAODMC.C, ANALYSIS/macros/TaskBuzzer.C, ANALYSIS/macros/runTaskNormalization.C, HMPID/AnalysisTrainHMPID.C, HMPID/HMPIDFindAlignTracks.C, ITS/macrosSDD/ITSQArecoparam.C, ITS/macrosSDD/PlotQASDD.C, ITS/macrosSDD/ReadQASDD.C, ITS/macrosSDD/TrendQASDD.C, ITSMFT/ITS/FT2/MakeAODInputChain.C, ITSMFT/ITS/v0/FastVsSlowSim.C, PHOS/macros/pi0Calib/AnaPi0Select.C, STEER/STEER/AliQAManager.cxx, STEER/macros/CreateTags.C, STEER/macros/CreateXML.C, STEER/macros/MergeTags.C, T0/T0calib/raw2treeGrid_collection.C, TOF/TOFCalibPass0.C, cmake/FindROOT.cmake, cmake/PARfiles/Makefile.in, test/QA/rawqa.C
This pull request introduces changes in AliRoot in such a way that access to the GRID is done through abstract classes instead of using specific implementations. These changes are needed in order to support both GRID plugins and their corresponding classes (TAlien and TJalien). Modifications in this pull request have been discussed in Computing Board (link).
The corresponding AliPhysics pull request is here: https://github.com/alisw/AliPhysics/pull/8186
The changes are split into the following 5 steps:
Edit 1: Formatting, and fixed the commit hashes.
Edit 2: Added commit hash for changes in the macros.
=> Replacing TAlien specific classes with abstract TGrid classes

EVGEN/AliDecayer.h, PYTHIA6/AliPythia6/AliDecayerPythia.cxx
Modification to "forced" Lambda_c ->pK0 option in AliDecayerPythia to force the decays of the K0 daughter in the correct channel (K0 -> K0S -> pi+pi-), to be used for simulation of training signal samples for ML analyses.
As the modified option affects all kaons in the sample we add it as a separate option (kLcpK0SBDTsig) complementary to the original option (kLcpK0S). Corresponding custom generator will be added by pull request to AliDPG shortly.
=> Add modified version of forced Lc->pK0 decay to AliDecayerPythia

AD/ADsim/AliADv1.cxx, AD/ADsim/AliADv1.h
If the regular expression "year=YYYY" is found in title of constructor, then the year is used to decide whether to construct the ADA PMT shielding or not.
if the regex is not found, or the constructor without name-title is used, the ADA PMT shielding is constructed by default. 
In the later case you can still use the method  EnablePmtShieldingADA(const Bool_t flag) to alter this behavior.
=> Parse title in AD constructor, extract year and decide if construct PM shield geometry

AD/ADsim/AliADv1.cxx
Print info in ParseYear() to check if the expression "year=YYYY" was found in title of ADv1 constructor.
=> Print info in ParseYear()

HLT/BASE/util/AliHLTZMQhelpers.h, HLT/BASE/util/CMakeLists.txt, HLT/BASE/util/ZMQESDserver.cxx, HLT/BASE/util/ZMQESDserver.md, HLT/BASE/util/o2header.py, HLT/ZMQ/AliZMQhelpers.cxx, HLT/ZMQ/AliZMQhelpers.h
Adds tool (standalone binary, ZMQESDserver) to read ESDs and send the extracted columnar data via ZMQ in O2 data format. Meant to inject AOD like data into O2.
Will probably need some further development regarding the precise format of the data. Otherwise works fine.
=> Add prototype of ZMQESDserver

STEER/STEER/AliLHCDipValT.h
on gcc version >=7, the snprintf call caused a format-truncation warning. By default, -Werror is used, so the warning prevented compilation.
=> remove cause for format-truncation warning

STEER/STEERBase/AliStack.cxx, THijing/AliGenHijing.cxx
This is needed for HIJING, e.g. when particle 3124 is the first (and
its PDG is unknown), then the track is not added, and we should
account for this.
=> Fix behaviour when 1st generated particle has unknown PDG (R. Shahoyan)

STEER/AOD/AliAODHandler.cxx, STEER/STEERBase/AliMCEvent.cxx, STEER/STEERBase/AliMCEvent.h
In case of embedding AliMCEvent::GenEventHeader() will return AliGenCocktailEventHeader 
(downcasted to AliGenEventHeader) containing the headers of both embedded and background events. 
In order to correspond to primary tracks ordering and make work methods like GetGenerator(itrack), 
the headers of the embedded event are added first, followed by the BKG event headers (e.g. Hijing).
=> With embedding MCEvent::GenEventHeader combines all headers

EVE/EveBase/AliEveESDTracks.cxx, MUON/MUONcalib/AliMUONPedestal.cxx, STEER/AOD/AliAODEvent.h, STEER/ESD/AliCascadeVertexer.cxx, STEER/ESD/AliESDpid.cxx, STEER/STEERBase/AliMixedEvent.h, STEER/STEERBase/AliTPCPIDResponse.cxx
These commits fix minor compiler warnings:
- Hidden-methods for `AliVEvent`: `GetVZEROData` & `GetMultiplicity`
- Member-initialization order in `AliTPCPIDResponse`
- Improper '%' in formatting strings
- Unused variables in `AliCascadeVertexer`
Much of the changes is removal of trailing whitespace & indentation alignment
=> Fix compiler warnings & indentation inconsistencies

cmake/FindZeroMQ.cmake
ZeroMQ autodetection can be programmatically disabled by passing as argument
`-DDISABLE_ZEROMQ=ON`
=> Add ability to disable ZeroMQ

ANALYSIS/ANALYSIS/ANALYSISLinkDef.h, ANALYSIS/ANALYSIS/AliAnalysisDataContainer.cxx, ANALYSIS/ANALYSIS/AliAnalysisDataContainer.h, ANALYSIS/ANALYSIS/AliAnalysisManager.cxx, ANALYSIS/ANALYSIS/AliAnalysisTask.h, ANALYSIS/ANALYSIS/AliDirList.cxx, ANALYSIS/ANALYSIS/AliDirList.h, ANALYSIS/ANALYSIS/CMakeLists.txt
This PR introduces a special container AliDirList that allows writing its content into a folder and reading content from a folder in a lazy manner. This container is useful for handling large outputs of analysis tasks during the grid merging phase and after, when running the Terminate method. To use, simply replace the output type of a task from TList/TObjArray to AliDirList.
The output content of a task having a AliDirList output will be placed in a folder named the same as the data container. Note that the AddTask macro for such a task needs to be changed to create a container of type AliDirList instread of the usual TList/TObjArray. During merging, the memory footprint will be reduced to the size of the largest object being merged, instread of the size of the full list. During the …
=> AliDirList

cmake/FindROOT.cmake
This used to be possible but was broken when AliEn-ROOT-Legacy was extracted from ROOT. When AliEn is missing, just print a warning instead of throwin a fatal error.
=> Fix: allow compiling AliRoot without AliEn

STEER/CDB/AliCDBManager.cxx
With the new alien-root-legacy one has to check if the TAlien class
is available instead of querying root-config (anyway it was bad design).
=> Remove broken root-config query

ANALYSIS/ANALYSISalice/AliESDtrackCuts.cxx, ANALYSIS/ANALYSISalice/AliESDtrackCuts.h
Added the possibility to cut on the covariance matrix relative pt resolution in a pt dependent way
=> AliESDtrackCuts: added pt dependent cov matrix cut

ANALYSIS/ANALYSIS/AliAnalysisTaskCfg.cxx
This fix allows reading longer lines from the train configuration files in the LEGO test (10000 characters maximum instead of 1024)
=> Increased line size when parsing MLTrainConfig files.

HLT/TRD/CMakeLists.txt
Was simply forgotten to take into account when we merged AliTPCCommon, and the old code didn't break anything but just disabled some HLT TRD components.
=> Fix missing adaption to merging of AliGPU

STEER/STEERBase/AliExternalTrackParam.cxx
relevant only in some marginal cases of B=0 data, does not affect productions
=> fix treatment of B=0 track extrapolation X estimates

STEER/AOD/AliAODcascade.cxx, STEER/AOD/AliAODcascade.h
This commit is necessary to make full use of AODs for the cascade analysis in Pb-Pb, which is badly needed to avoid excessive CPU usage by LEGO trains. The change is essentially the addition of an extra data member to AliAODcascade that stores the bachelor+baryon CosPA such that the analyser can select / reject based on that variable at the AOD level. To be tested. Please check this code for correctness, indeed. Thank you!
=> Added bach-baryon cospa to AliAODcascade for nanoAODs

TPC/TPCsim/AliTPCv0.cxx, TPC/TPCsim/AliTPCv2.cxx, TPC/TPCsim/AliTPCv4.cxx
corrected for zero section for outplug, it's necessary for root6.
=> Corrected for zero-length section

EVGEN/AliGenParam.cxx
This fixes the missing decay chain problem affecting ALIROOT-7708
cc @miweberSMI @amorsch
=> Fix variable initialisation in AliGenParam

EMCAL/EMCALbase/AliEMCALTriggerSTUDCSConfig.cxx, EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx
Now set based on OCDB patch value, not firmware version.
Old behavior for Run 1.
=> Corrects the setting of the patch size for L1 Jet Trigger.

ITS/ITSsim/AliITSv11GeometrySDD.cxx, ITS/ITSsim/AliITSv11GeometrySDD.h, ITS/ITSsim/AliITSv11GeometrySPD.cxx, ITS/ITSsim/AliITSv11GeometrySupport.cxx
Some details in the ITS geometry descriptions were improved to check the discrepancies in material budget between data and MonteCarlo. Namely:
- the copper wire running above all SDD ladders was removed
- the material inside SPD cooling pipes was changed from Liquid Freon to Gaseous Freon
- the so-called Omega Shape inside the SPD Thermal Shield was reimplemented (it was part of a complex CompositeShape, now it is a standalone volume)
=> Improvements to ITS geometry to check material budget discrepancies

PYTHIA6/AliPythia6/AliDecayerPythia.cxx
Changed eta prime decayer config to include also a pi+pi-eta decay, in addition to the gamma gamma decay, with a 50:50 branching ratio.
=> Updated deacyer configs for Eta Prime MC generator

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx, PYTHIA6/AliPythia6/AliGenPythiaPlus.h
This PR allows to use in PYTHIA8 the selection of generated events based on the generated multiplicity, essentially by replicating the features that we have for PYTHIA6.
It was added for upcoming MC productions in PWG_HF (@cterrevo) and PWG_MM (Valentina Zaccolo).
@amorsch, do you think it is OK?
I did some first basic tests and it works as expected.
We may add new features in a next commit.
Best regards, Francesco
=> Add possibility to trigger on generated multiplicity in PYTHIA8

PYTHIA6/AliPythia6/AliGenPythia.cxx
This modification allows to trigger on particles with negative PDG code also for HF.
With the previous code, the trigger particle PDG code was checked with the absolute value also in the HF related event selections.
As a consequence, in HF productions only particles were selected as trigger particles.
With this fix one can select particles or antiparticles as triggers.
=> Fix to allow to trigger on antiparticles also for HF signals

ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx, ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.h
This change is meant to add one extra Float_t to each AliAODcascade during ESD->AOD filtering automatically. This additional variable, which is the cosine of pointing angle value for the V0 comprised of the baryon + bachelor of any given cascade candidate, is crucial for rejecting an unwanted background structure in high-multiplicity environments. More details can be found in this [analysis note](https://alice-notes.web.cern.ch/node/588).
=> Change ESD->AOD filter to add BachBaryon CosPA automatically

STEER/ESD/AliESDUtils.cxx, STEER/ESD/AliESDUtils.h, STEER/ESD/AliVertexerTracks.cxx, STEER/ESD/AliVertexerTracks.h
Now AliESDUtils::RefitESDVertexTracks allows to store newly found vertices to
externally provided TClonesArray, w/o modifying original ESDEvent
Example:
````
TFile fesd("AliESDs.root");
TTree* esdTree = (TTree*)fesd.Get("esdTree");
AliESDEvent ev;
ev.ReadFromTree(esdTree);
TClonesArray arr("AliESDVertex"); // destination
esdTree->GetEntry(52)
ev.ConnectTracks();
AliESDUtils::RefitESDVertexTracks(&ev,6,0, &arr); // run in MultiVertexer mode with default settings
arr.Print(); // 1st entry will correspond to primary vertex (even if invalid), the rest is pile-up ordered in multipicity
arr.Clear("C");
````
=> Optionally put reprocessed vertices to external array

ANALYSIS/ANALYSIS/AliAnalysisDataContainer.cxx, ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx, STEER/CDB/AliCDBManager.cxx, cmake/FindROOT.cmake
This pull request is required for JAliEn integration. It decouples the AliRoot analysis plugin from the legacy AliEn ROOT Grid plugin by using the interfaces that are defined in ROOT and are common for both Grid plugins.
For this purpose some new interfaces are defined in the Alice-Grid-Utils package, namely:
The biggest change in this pull request is how collections are created. We no longer call `alien_find` standalone tool, but use the `gGrid->Command()` interface and build the collections in memory. The `TAliceCollection::AddFast()` method is used here exclusively for performance reasons. Use `TGridCollection` instead of `TAliceCollection` wherever possible.
=> AliAnalysisAlien improvements related to using the generic grid plugin interface

EMCAL/EMCALsim/AliEMCALTriggerTRU.cxx
Corrects TriggerTRU code so that masking by STU actually prevents the TRU from contributing to L1 Triggers.
=> Makes TriggerTRU not contribute to L1 triggers if disabled by STU

STEER/STEERBase/AliMCEvent.cxx
Gen.headers with "particles_suppressed" in the title will not be accounted for in the AssignGeneratorIndex.
=> Skip AssignGeneratorIndex for header with particles_suppressed in the title

STEER/STEERBase/AliDataFile.cxx
This commit affects only builds that have multiple words in their name, such as "_NEXT_ALIEN" suffix.
=> Improve parsing the version in AliDataFile

TPC/TPCcalib/AliTPCDcalibRes.cxx, TPC/TPCcalib/AliTPCDcalibRes.h
- fix in median calculation
- add fY2XBins* arrays to destructor
- fix GetDY2X method: before the results were not matching for the case of uniform and variable binnings. But I think this is not really an issue, since as far as I can see this function is not used
=> Small fixes in AliTPCDcalibRes

ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx
This is a proposed hotfix for a bug introduced after switching to the TGrid API for creating the Grid collections in the analysis plugin.
=> Fix a bug in AliAnalysisAlien::CreateDataset

ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx, ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.h, STEER/AOD/AODLinkDef.h, STEER/AOD/AliAODEvent.cxx, STEER/AOD/AliAODEvent.h, STEER/AOD/AliAODkink.cxx, STEER/AOD/AliAODkink.h, STEER/AOD/CMakeLists.txt
Now apart from the Kink AliAODVertex also the AliAODkink object is stored, containing the
kink-specific info like kinematics of prongs at the kink point.
All mothers are stored (including those which did not get any filter bit).
=> Ensure consistent storage of Kinks in the AOD (P.Ganoti + RS)

STAT/AliMathBase.cxx
This otherwise triggers an error on modern compilers.
=> Add missing format string

ANALYSIS/ANALYSIS/AliAnalysisManager.cxx
On of the changes in fix 3756604e497e65ba327a7e7b2d8f69db7b91ac09 (intended to make AliAnalysisManager compatible
both with root5.. and root6-18-04, was in fact crashing analysis with all root versions. Reverting it.
=> Fix: restore AliAnalysisManager::Notify kTrueNotify actions

ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx, STEER/AOD/AliAODHeader.cxx, STEER/ESD/AliESDHeader.cxx, STEER/ESD/AliESDHeader.h, STEER/STEER/AliReconstruction.cxx, STEER/STEER/AliReconstruction.h
Run TPC and ITS pileup taggers from AliESDUtils in the reconstruction and fill AliESDHeader.
In the AOD filtering, either transfer pile-up info from AliESDHeader to AliAODHeader or run the taggers
directly in the filtering.
=> Custom pile-up info in ESD and AOD

ITS/ITSsim/AliITSv11GeometrySPD.cxx
The SPD cooling pipe material was changed from Inox to Phynox (as it should be), in order to check whether this correction improves the material budget comparison between data and MC.
=> Change SPD cooling pipes material from Inox to Phynox

STEER/ESD/AliESDEvent.cxx
This is where we spend 80% of the cost when iterating on an ESD collection.
=> Prefer Clear over Delete for `AliESDTRDTracklet`s

STEER/ESD/AliESDEvent.cxx
This is now 10% of running over ESDs.
=> Clear V0s rather than deleting them

ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx
This pull request reverts most of the changes in AliAnalysisAlien::CreateDataset to the state from v5-09-50 and applies minimal changes to make it JAliEn compatible.
See this diff that compares the code in this pull request to the code from v5-09-50:
https://stikked.web.cern.ch/stikked/view/3fa5b503
=> CreateDataset - minimal jalien compatible fix

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx, PYTHIA6/AliPythia6/AliPythiaBase.h, PYTHIA8/AliPythia8/AliDecayerPythia8.cxx, PYTHIA8/AliPythia8/AliDecayerPythia8.h, PYTHIA8/AliPythia8/AliPythia8.cxx, PYTHIA8/AliPythia8/AliPythia8.h, PYTHIA8/AliPythia8/AliTPythia8.cxx, PYTHIA8/pythia8.C
- AliPythia8 has a factory method that returns a AliDecayerPythia8 object
(implementing a method in the base class AliPythiaBase)
- this method is called by AliGenPythiaPlus to set fDecayer consistently
- modifications to the decay table can be performed via AliGenPythiaPlus ::SetForceDecay
+
some updates in pythia8.C to work with root6
=> Correct use of decayer in AliGenPythiaPlus

TEvtGen/TEvtGen/AliGenEvtGen.cxx
This fix add the specific AliGenEvtGen header to preserve index generation assignment. 
This follows the discussion here https://github.com/alisw/AliRoot/pull/1033
and it is needed for the production corresponding to the JIRA ticket
https://alice.its.cern.ch/jira/browse/ALIROOT-8237
=> add AliGenEvtGen header to preserve index generator assignment

EMCAL/EMCALsim/AliEMCALTriggerTRU.cxx
After the event is done the L0 time has to be set
to 0, otherwise it is not re-evaluated for the next
event (check for L0 time != 0)
=> Reset L0 time

STEER/STEER/AliReconstruction.cxx
Returned false should be treated as a failure, while opposite was done.
@pzhristov thanks for spotting this. Fortunately, in the productions we use ``rec.SetStopOnError(kFALSE)``, so the bug did not affect any MC.
=> Fix in treatment of return value of RunCustomPileUpFinders

STEER/STEERBase/AliStack.cxx
If the PDG is not known to the TParticlePDG then the particle is not added to the stack, nevertheless
the ntr (position of the added particle on the stack) was not set to negative value. This was signalling
to the generator which called PushTrack that the particle is added to the Stack, leading to the wrong
count of primaries in the generator header. In case the stack was empty at this moment, the following
call of KeepTrack(ntr) would lead to segm.violation, since ntr initial value is 0.
Now, the ntr is >=0 only if the particle was actually added to the stack.
ping: @ffionda @miweberSMI
=> Fix: Stack::PushTrack must assign ntr<0 when rejecting particle

ANALYSIS/ANALYSIS/AliAnalysisManager.cxx
The line was commented by mistake in the previous set of modifications and this led to problems. In fact it is enough to return kTRUE, which indicates everything is OK, but the remaining part of the Notify() is omitted.
=> Return kTRUE since kFALSE indicates to Root v6-18-04 real problems

TPC/TPCrec/AliTPCseed.cxx, TPC/TPCrec/AliTPCtracker.cxx
* Non observed clusters are used in the calculation assuming there is a signal  below threshold.
* Missing cluster is defined, in case there is signal before and after +-2 rows
* Number of  non observed rows, (signal below threshold) are used in truncated mean.
* Threshold and baseline is not well defined, as baseline  fluctuates. Mean  of the lowest obsereved NCL Q are  used to estimate lower signal.
```    
Int_t iclN=TMath::Nint((ncl + nclBelowThr*(1-factor))*(up-low));
Int_t icl0=TMath::Nint((ncl + nclBelowThr*(1-factor))*low+ nclBelowThr*factor);
...
dEdxF=TMath::Mean(iclN,&ampWithBelow[icl0]);
```   
- if factor ==1  -> missing clusters are ignored (not good idea -biasing results)
- ifactor ==0  -> missing clusters are ignored (not good idea -biasing results)
=> PWGPP-571: Bug fix in implementation of the missing cluster correction factor 

TPC/TPCbase/AliTPCRecoParam.cxx, TPC/TPCbase/AliTPCRecoParam.h, TPC/TPCrec/AliTPCtracker.cxx
in the pass1 not used - default -kFALSE
=> PWGPP-570 - missing switch - calculate crosstalk for ion tail only if specified

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx
Dear @amorsch ,
with Pythia8 the HF selection on the decay particles was not working (causing in an infinite loop).
It seems to me it was due to a fortran/c++ mismatch in the counting (from 0 or from 1).
The fix in this commit solves the issue: from local simulations I could get proper selection on the decay particles.
Cheers, Francesco
=> Fix index to have the CutOnChild selection working with Pythia8

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx, PYTHIA6/AliPythia6/AliGenPythiaPlus.h
HI,
this modification implements a feature that allows us to fill the stack only with particles originating from c/b quark hadronization. This feature was present in PYTHIA6 and it used in Pb-Pb D2H simulations to inject only charm (beauty) signals with PYTHIA on top of an underlying event, without injecting the "full" pp event.
The implementation is taken from AliGenPythia, with some modification to deal with the different array index (starting from 0 or from 1) in C++ and fortran.
Best, Francesco
=> Implement kHeavyFlavor as option for SetSTackFillOpt

ITS/ITSsim/AliITSv11GeometrySSD.cxx
The attached commit improves some details in the SSD material budget (for simulation), discussed here:
https://alice.its.cern.ch/jira/browse/PWGPP-527
=> Fixes in SSD material budget

GRP/MakeGRPRecoParam.C, STEER/ESD/AliESDv0.cxx, STEER/ESD/AliV0HypSel.cxx, STEER/ESD/AliV0HypSel.h
Needed for correct treatment of the hypertriton mass evaluation.
=> M<0 in AliV0HypSel will be interpreted as q=2 particle

PYTHIA8/AliPythia8/AliPythia8.cxx
From the checks discussed in ALIROOT-8371, it emerged that the SoftQCD:nonDiffactive setting provides a better description for the pt spectra of D mesons and the underlying event multiplicity.
Based on these checks, we change the configuration in the method AliPythia8::ConfgHeavyFlavor
=> Change to SoftQCD the process for HF generation

PYTHIA6/AliPythia6/AliGenPythia.cxx, PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx, PYTHIA6/AliPythia6/AliPythia.cxx, PYTHIA6/AliPythia6/AliPythia6.cxx, PYTHIA6/AliPythia6/PythiaProcesses.h, PYTHIA8/AliPythia8/AliPythia8.cxx
This feature allows to select generated events containing a charm or a beauty quark.
This allows to create samples enriched of HF with the c and b proportions given by PYTHIA, which could be practical for some studies (e.g. HF-lepton pairs).
=> Add HF selection case with c and b proportions as in Pythia

CMakeLists.txt
Root5 fails to generate a dictionary requiring ZMQ (v4.2 in my case)
ping to @ktf @mkrzewic
=> Ignore ZMQ when Aliroot is built with root5

STEER/ESD/AliTrackerBase.cxx, STEER/ESD/AliTrackerBase.h, STEER/STEER/AliReconstruction.cxx, TPC/TPCbase/AliTPCTransform.cxx, TPC/TPCbase/AliTPCTransform.h, TPC/TPCcalib/AliTPCcalibAlignInterpolation.cxx, TPC/TPCcalib/AliTPCcalibBase.cxx, TPC/TPCcalib/AliTPCcalibBase.h, TPC/TPCcalib/AliTPCcalibCalib.cxx, TPC/TPCcalib/AliTPCcalibGainMult.cxx, TPC/TPCcalib/AliTPCcalibTimeGain.cxx, TPC/TPCrec/AliTPCclusterer.cxx, TPC/TPCrec/AliTPCtracker.cxx
See discussion at https://alice.its.cern.ch/jira/browse/ALIROOT-8260?focusedCommentId=242160&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-242160
for details.
@miranov25 please cross-check, I've tested it on a few 10 events of 1 LHC18q chunk, and I see that depending on the BC the cluster time in the ``AliTPCTransform->Transform(...)`` gets shifted by 0, 0.25 or 0.75, as we want.
=> Account for BC dependent ALTRO/LHC clocks shift

ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx
With a local installation (on a mac) of the master the merging via JDL of an analysis outputs fails. The locally created Stage_1.xml fails. As I understand the  new alien_find command does not redirect the output to the standard output and thus redirection of it to a file ends up with an empty file.
=> Fix remaining usage of alien_find

STAT/TStatToolkit.cxx, STAT/TStatToolkit.h
This function replace previously used TStatToolkit::MakeDistortionMapFast
Options specified like in Python version - using map-dictionary
* option to sore histograms
* option to store cumulative
* ... more options - statistic export  to be added ...
=> PWGPP-571, PWGPP-529 -TStatToolkit::MakePDFMap()

TPC/TPCrec/AliTPCclusterer.cxx, TPC/TPCrec/AliTPCtracker.cxx
Previous patch was working for clusters produced in the reconstruction, but was failing
when clusters were extracted beforehand
=> Missing settings for altro clock fix

TPC/TPCrec/AliTPCclusterer.cxx, TPC/TPCrec/AliTPCtracker.cxx
Previous patch was working for clusters produced in the reconstruction, but was failing
when clusters were extracted beforehand
=> Missing settings for altro clock fix (#1106)

PYTHIA6/AliPythia6/AliGenPythia.cxx, PYTHIA6/AliPythia6/AliGenPythia.h, PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx, PYTHIA6/AliPythia6/AliGenPythiaPlus.h
Option to avoid 2 cycles in MC productions like until now, one for EMCal and another one for DCal+PHOS for gamma-jet or jet-jet triggered on gamma over calorimeter acceptance.
With these changes, it is possible to do the OR on the acceptance of the 3 calorimeters so that one MC cycle can be requested, and for better event weight scaling between calorimeters.
=> Add option to trigger particles over any of the central barrel calos: PHOS or EMCal or DCal

THijing/AliGenHijing.cxx
Dear all,
changes from commit 54fa17c75c556883618719a9dc90acac38a5d6f3 should be included in the next released version since the name of the file containing the model for spectator production was missing the file extension (.root).
Despite the 83 declared changes (indentation and left spaces that the editor automatically removes), the only change is the one described above. In fact, the output of git diff -w is the following:
diff --git a/THijing/AliGenHijing.cxx b/THijing/AliGenHijing.cxx
index e91f23e7f8..8ae0564f6f 100644
--- a/THijing/AliGenHijing.cxx
+++ b/THijing/AliGenHijing.cxx
@@ -241,7 +241,7 @@ void AliGenHijing::Init()
if(fDataFragmentation){
//TFile *file = TFile::Open("$ALICE_ROOT/ZDC/fragmSpecDataDriven.root","READ"); //old 2.76 TeV data
-      TFile *file = …
=> Fixing a typo: .root file extension missing in THijing/AliGenHijing.cxx

STAT/TStatToolkit.cxx
* Default: if case option not specified - fits performed in full range
* if option specified fit is performed in range parameterized by LTM estimator
* example option:  options["LTMFitRange"]="0.6:5:1";
* Range center: LTM 0.6 used
* Range:  (LTM0.6 -6 LTM sigma-1, LTM0.6 +6 LTM sigma+1 ) range
=> PWGPP-529 -TStatToolkit::MakePDFMap()- adding new fit option LTMFitRange

CMakeLists.txt
Move rpath settings (for macOS) early enough in CMakeLists.txt to actually take effect for the core libraries and, thus, allowing library loading without relying on LD_LIBRARY_PATH.
@ktf: This block of settings had been moved **after** the inclusion of the core libraries (1db85f2d) and, thus, never took effect for them. This commit restores the intended behaviour to consistently apply these settings  to all libraries.
=> Move (back) rpath settings

PYTHIA8/AliPythia8/AliDecayerPythia8.cxx
Since AliDecayerPythia8 is correctly called from AliPythia8 the decay of pions was switched off.
With this change the pi0 decays are ON again.
=> switch ON pi0 decay in pythia8 decayer

TPC/macros/MakeTPCRecoParam_Run2Dist.C, TPC/macros/MakeTPCRecoParam_Run2DistMC.C
patch obtained from lambda OCDB as described in the ALIROOT-8420
=> ALIROOT-8420- set lambda OCDB as used first time for the LHC18q,r

TPC/TPCbase/AliTPCChebCorr.h
Needed for MC for 2018 PbPb, see https://alice.its.cern.ch/jira/secure/EditComment!default.jspa?id=56262&commentId=245179.
=> Protection agains Distortion RMS paramet. < 0

STEER/STEERBase/AliSysInfo.cxx, STEER/STEERBase/AliSysInfo.h
```
static void dumpBranchSize(FILE *pFile,  TBranch * branch, const char *dumpName, Float_t &totBytes, Float_t &zipBytes, Float_t zipBytesNorm);
static void dumpTreeSize(TTree * tree, const char *dumpName, const char * outName=0);
static void printTreeTable(const char *inputLog, const char *mask,  Int_t nrows, Int_t sortCol=7, Bool_t isJIRA=1, Bool_t verbose=1);
````
```
for (Int_t i=0;i<3; i++){
TFile * f = TFile::Open(fnames[i]);
TTree * tree = (TTree*)f->Get(tnames[i]);
AliSysInfo::dumpTreeSize(tree, tnames[i],"dump.list");
AliSysInfo::printTreeTable("dump.list",tnames[i],nrows,7,1);
}
````
|branch|sel.fsize|zip.self size|size|zipsize|compression|fraction|
| ------------- | ------------- |--|--|--|--|--|
|V0s.base|1729879|1081357|1729879|1081357|0.63|1.0000| …
=> PWGPP-584   recursive TTree, TBranch  dump and formatted printing/sorting

THijing/AliGenHijing.cxx
The crashes are due to a numerical instabilities in the elastic scattering routine at specific settings of the center of mass energy. In these cases for some nucleons E < |pz|. This is checked by HIJING and the program stops.
No significant effects from elastic scattering on physics expected at LHC energies.
With 
hijing->SetNoElas(kFALSE);   
one can switch elastic scattering on.
=> Elastic scattering between N-N pairs switched off to avoid frequent crashes

EMCAL/macros/TestSimuReco/Config.C, MUON/macros/g4Config.C, macros/g4Config.C, test/genkine/simG4/Config.C, test/vmctest/gun/g4Config.C, test/vmctest/gun/g4Config2.C, test/vmctest/lego/g4Config.C, test/vmctest/ppbench/g4Config.C, test/vmctest/production/Config.C
This change makes possible to run Geant4 simulation (sequential) with Geant4 libraries
built with multi-threading enabled
=> Updated Geant4 Config.C macros:

EMCAL/EMCALsim/AliEMCALTriggerTRU.cxx
[EMCAL 510] The TRU firmware version was not saved properly and should not
be used for determine which L0 version to use. Decision is now made based
on the L0 Sel variable, via AliEMCALTriggerTRUDCSConfig::GetSegmentation().
This corrects issue where simulations used L0v0 instead of L0v1
=> [EMCAL 510] Fix TRU L0 version selection

STEER/STEERBase/AliStack.cxx
Should solve 
https://alice.its.cern.ch/jira/browse/ALIROOT-8233
AliGenHijing uses the AliStack::PushTrack(Int_t done, Int_t parent, Int_t pdg, const Float_t *pmo
method of AliStack
This method calculates the energy from the momentum and the particle mass.
The calculation was single precision and has been changed to double precision now.
=> PushTrack(..., Float* pmom ...): calculate energy in double precision

STAT/AliTreePlayer.cxx, STAT/AliTreePlayer.h
* before only "recreate mode" supported
* change to next pad in canvas - used in TTree::Draw()
*  Example  - query draw histogram fulfilling criteria to sequence of pads
* visualizing histogram where fits failed "!T0_isOK"
````
tree->Draw("histCM.Draw(\"colz\"):histCM.GetXaxis()->SetRangeUser(130,170)","!T0_isOK&&abs(peakPosition-150)<20&&AliTreePlayer::nextPad()","goffpara",100,0);
````
=> ATO-493 - MakeCacheTree (file mode option), AliTreePlayer::NextPad

ITS/ITSsim/AliITSsimulationSDD.cxx, TOF/TOFsim/AliTOFv6T0.cxx, data/falice.cuts, test/genkine/commonConfig.C, test/genkine/simF/Config.C
ITS/ITSsim/AliITSsimulationSDD.cxx: protect against negative drift velocity
TOF/TOFsim/AliTOFv6T0.cxx: initialization of data members
data/falice.cuts: special (lower) cuts for Fluka
test/genkine/commonConfig.C: use the special Fluka cuts, possibility to
set Fluka-specific ionisation model in TPC
test/genkine/simF/Config.C: use Fluka-specific ionisation model in TPC
=> Changes for Fluka

EVGEN/AliGenCocktail.cxx, EVGEN/AliGenPileup.cxx
This modification is needed to have the proper production time for signals injected with embedding in case of simulations with pileup (see ALIROOT-8525)
=> Set generation time in cocktail header 

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx
Hi,
This modification is needed for HF productions with PYTHIA8 anchored to Pb-Pb.
It allows to select events at the generation level based on the presence of a given hadron species via SetTriggerParticle also for the cases kPyCharm and kPyBeauty, which are used in the Pb-Pb simulations (see ALIROOT-8502)
Cheers, Francesco
=> Possibility to select trigger particle for kPyCharm and kPyBeauty

EVGEN/AliDecayer.h, PYTHIA8/AliPythia8/AliDecayerPythia8.cxx, PYTHIA8/AliPythia8/AliDecayerPythia8.h
Add option to force Xic0 -> Xi- e+ nu_e decay instead of Xic0 -> Xi- pi+ decay, needed for D2H MC productions
=> Add option for semileptonic decay of Xic0

PYTHIA8/AliPythia8/AliDecayerPythia8.cxx
@chiarazampolli in this PR https://github.com/alisw/AliRoot/pull/1213 I forgot to add the Xic decay channel, which I found out not to be in the pythia8 decay table. I added it with this PR, together with the Omegac decay which was also missing. Thanks!
=> Add decay channels of Xic and Omegac not present in pythia8 decay table

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx
This commit implements a feature that is needed for HF productions in Pb-Pb, see ALIROOT-8502
=> Apply selection on heavy-quark rapidity for kPyCharm and kPyBeauty

EVGEN/AliDecayer.h, PYTHIA8/AliPythia8/AliDecayerPythia8.cxx, PYTHIA8/AliPythia8/AliDecayerPythia8.h
This option is added to increase the statistics of Ds->phi+pi decays in MC productions, see ALIROOT-8502
=> Option to swicth off Ds->K*K decays

EVGEN/AliDecayer.h, PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx, PYTHIA8/AliPythia8/AliDecayerPythia8.cxx, PYTHIA8/AliPythia8/AliDecayerPythia8.h
This is to backport to v5-09-54 two modifications needed for the HF productions anchored to Pb-Pb pass3:
- Apply selection on heavy-quark rapidity for kPyCharm and kPyBeauty
- Option to switch off Ds->K*K decays
=> Backportings for HF productions

STEER/CDB/AliCDBGrid.cxx
This way, both legacy and new AliEn will work.
=> Changing options and pattern for searching OCDB files

EMCAL/EMCALsim/AliEMCALTriggerSTU.cxx
Corrects lack of median background subtraction on the GA Patch. The factor of 64 should be correct because the factor ends being (2*2) / (8*8), and the GA patches are 2x2 FastORs and the background patches are 8x8 FastORs.
=> Corrects lack of median background subtraction on the GA Patch

ANALYSIS/ANALYSIS/AliAnalysisManager.cxx, ANALYSIS/ANALYSIS/AliAnalysisManager.h, ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx
This PR adds a new persistent data member to the analysis manager, accessible via: GetNMCevents(). This is filled in the lego train by the grid handler, and made available in both testing and grid running.
=> Added number of MC events in analysis manager.

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx, PYTHIA6/AliPythia6/AliGenPythiaPlus.h
This commit adds a feature that will be useful for future HF productions, see e.g. the case in ALIROOT-8281.
The modification adds the possibility to select the rapidity and pt of trigger particles, which was there in AliGenPythia (PYTHIA6), but not in AliGenPythiaPlus.
=> Possibility to select pt and y for trigger particles

STEER/STEERBase/AliPDG.cxx
Using 2018 values summarised in https://physics.nist.gov/cuu/pdf/wall_2018.pdf
This is particularly important for Tritons and Helium-3, that were off my a measurable amount
=> Update nuclei masses with the latest CODATA release

ANALYSIS/ANALYSISalice/AliAnalysisTaskMCParticleFilter.cxx, EVGEN/AliGenReaderHepMC.cxx, STEER/STEERBase/AliGenHepMCEventHeader.cxx, STEER/STEERBase/AliGenHepMCEventHeader.h, TEvtGen/THepMCParser/THepMCParser.cxx, TEvtGen/THepMCParser/THepMCParser.h
Adding fields for cross section, pthard and ntrials to hepmc event header
Fields are mainly of relevance for pp generators (Herwig,
SHERPA, ...)
Propagate cross section, number of trials and pt-hard from
HepMC header to AliAODMCHeader
Including a few indentation fix exporting tab to space
=> Back porting commits in the HepMC header [ALIROOT-8579]

STEER/AOD/AliAODCaloCells.cxx, STEER/ESD/AliESDCaloCells.cxx
- this bug fix is needed for skimming data sets, otherwise part of the information is lost and the skimmed AODs aren't useful any longer
=> Bug fix in copy constructor for AliAOD/ESDCaloCells

EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx, EMCAL/EMCALsim/AliEMCALTriggerElectronics.h
Adds a rescaling of the digits in MC so trigger signal energies match total deposited energy, as done in data.
Necessary for simulated trigger thresholds to be accurate.
=> Adds a rescaling of the EMCAl trigger digits in MC

STEER/STEERBase/AliTPCPIDResponse.cxx, STEER/STEERBase/AliTPCPIDResponse.h
Generic TF1 functional representation should be (optionaly) used to describe TPC dEdx properties in AliTPCPIDResponse
TF1 can represent  arbitrary number of variables and parameters.
`Double_t TF1::EvalPar(const Double_t* x, const Double_t* params = 0)`
* https://alice.its.cern.ch/jira/browse/ATO-525
* https://alice.its.cern.ch/jira/browse/ATO-525?focusedCommentId=258929&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-258929
=> Usage of TF1 for Ndimensioal AliTPCPIDResponse error parameterization - https://alice.its.cern.ch/jira/browse/ATO-525

EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx
Fixes an error where new L0 patch digits would be created with the wrong fastOR id.
This led to an apparent trigger inefficiency when multiple digits in the same location overwrote each other.
=> EMCal Trigger Digit overwrite fix

STEER/STEERBase/AliTPCPIDResponse.cxx
* Parameter MIP/dEdx was 50 times overestimated   - bbAleph was already normalized to the MIP
* Resolution from TF1 was relative in the AliTPCPIDRsponse supposed to be absolute
=> ATO-525  bug fixes: Parameter MIP/dEdx was 50 times overestimated

EMCAL/EMCALbase/CMakeLists.txt, EMCAL/EMCALbase/TestsAliEMCALTriggerSTUDCSConfig.cxx, EMCAL/EMCALbase/TestsAliEMCALTriggerTRUDCSConfig.cxx
- Adding environment and CMAKE_INSTALL_PREFIX
in test definition
- Adapt reference for stream operators to latest
implementation
=> Fixes for EMCAL unit tests

EVGEN/AliDecayer.h, PYTHIA6/AliPythia6/AliDecayerPythia.cxx, PYTHIA8/AliPythia8/AliDecayerPythia8.cxx
Adds option to AliDecayerPythia and AliDecayerPythia8 to force Lambda_c to decay in the Lambda pion channel (3122 211), for use in dedicated MC productions.
=> Add kLcLpi forced decay option to AliDecayer

ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx, STEER/AOD/AliAODInputHandler.cxx, STEER/ESD/AliESDInputHandler.cxx, STEER/STEERBase/AliInputEventHandler.cxx, STEER/STEERBase/AliInputEventHandler.h
This PR addresses ALIROOT-8652. The open status for friend files can be read directly from the chain, after TChain::GetEntries gets called in AliAnalysisManager::Init. This will reduce the number of file open requests in the analysis using friend files.
=> Avoid opening friend files in analysis, done anyway by TChain::GetEntries

ANALYSIS/ANALYSISalice/AliAnalysisTaskPIDqa.cxx
@chiarazampolli this is a brute-force protection: depending on the options, the `countSpecies` can be as small as 3, while the https://github.com/shahor02/AliRoot/blob/9d935c6602778cdbf833c95d00eea23f50f47cc2/ANALYSIS/ANALYSISalice/AliAnalysisTaskPIDqa.cxx#L1514 is called with kSPECIES=5, overflowing the `likelihoods`.
This bug dates back to 2016, strange that it fired only now. The logics should be checked by the authors (Yvonne? did not find hew on the git)
=> Fix: add protection against too small likelihoods container

EMCAL/EMCALbase/AliEMCALSimParam.cxx, EMCAL/EMCALbase/AliEMCALSimParam.h, EMCAL/EMCALbase/CMakeLists.txt, EMCAL/EMCALbase/TestsAliEMCALTriggerSTUDCSConfig.cxx, EMCAL/EMCALbase/TestsAliEMCALTriggerTRUDCSConfig.cxx, EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx, EMCAL/EMCALsim/AliEMCALTriggerElectronics.h, EMCAL/EMCALsim/AliEMCALTriggerSTU.cxx, EMCAL/EMCALsim/CMakeLists.txt, PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx, PYTHIA6/AliPythia6/AliGenPythiaPlus.h, PYTHIA6/AliPythia6/AliPythia6.cxx, PYTHIA6/AliPythia6/AliPythia6.h, PYTHIA6/AliPythia6/AliPythiaBase.h, PYTHIA8/AliPythia8/AliPythia8.cxx, PYTHIA8/AliPythia8/AliPythia8.h
* Adding ApplyUserTrigger to AliGenPythiaPlus.cxx
https://github.com/alisw/AliRoot/commit/cb4b148eff3de8ba2e563a6ca4827985acdee2e0#diff-6b966b6d0aa9f7582026d951afaecbe3ed80074d087b3f7140884f7deeac848f
* Corrects lack of median background subtraction on the GA Patch
https://github.com/alisw/AliRoot/commit/bc968e6347bcc8afb14cdad03ed04f6ff98a8bad#diff-8d4f87477168201a3bd96e6814ab0e0afe3dead85b882cf21105e9f220a2c97d
* Restore option to generate weighted events in AliGenPythiaPlus and add setting for AliPythia8
https://github.com/alisw/AliRoot/commit/a98c7f7bd8c9a9ff850d8684b26c37eda7d58c56#diff-6b966b6d0aa9f7582026d951afaecbe3ed80074d087b3f7140884f7deeac848f
* [ALIROOT-8649] Restore porting the event weight to the pythia header
https://github.com/alisw/AliRoot/commit/80c212d58b667e42dc37f7fa1 …
=> EMCal trigger fix and  PYTHIA weights recovery  V5 09 54 patches

EMCAL/EMCALbase/AliEMCALSimParam.cxx, EMCAL/EMCALbase/AliEMCALSimParam.h, EMCAL/EMCALbase/CMakeLists.txt, EMCAL/EMCALbase/TestsAliEMCALTriggerSTUDCSConfig.cxx, EMCAL/EMCALbase/TestsAliEMCALTriggerTRUDCSConfig.cxx, EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx, EMCAL/EMCALsim/AliEMCALTriggerElectronics.h, EMCAL/EMCALsim/AliEMCALTriggerSTU.cxx, EMCAL/EMCALsim/CMakeLists.txt, PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx, PYTHIA6/AliPythia6/AliGenPythiaPlus.h, PYTHIA6/AliPythia6/AliPythia6.cxx, PYTHIA6/AliPythia6/AliPythia6.h, PYTHIA6/AliPythia6/AliPythiaBase.h, PYTHIA8/AliPythia8/AliPythia8.cxx, PYTHIA8/AliPythia8/AliPythia8.h
* Adding ApplyUserTrigger to AliGenPythiaPlus.cxx
https://github.com/alisw/AliRoot/commit/cb4b148eff3de8ba2e563a6ca4827985acdee2e0#diff-6b966b6d0aa9f7582026d951afaecbe3ed80074d087b3f7140884f7deeac848f
* Corrects lack of median background subtraction on the GA Patch
https://github.com/alisw/AliRoot/commit/bc968e6347bcc8afb14cdad03ed04f6ff98a8bad#diff-8d4f87477168201a3bd96e6814ab0e0afe3dead85b882cf21105e9f220a2c97d
* Restore option to generate weighted events in AliGenPythiaPlus and add setting for AliPythia8
https://github.com/alisw/AliRoot/commit/a98c7f7bd8c9a9ff850d8684b26c37eda7d58c56#diff-6b966b6d0aa9f7582026d951afaecbe3ed80074d087b3f7140884f7deeac848f
* [ALIROOT-8649] Restore porting the event weight to the pythia header
https://github.com/alisw/AliRoot/commit/80c212d58b667e42dc37f7fa1 …
=> EMCal trigger fix and PYTHIA weights recovery to V5 09 55 patches

EMCAL/EMCALbase/AliEMCALSimParam.cxx, EMCAL/EMCALbase/AliEMCALSimParam.h, EMCAL/EMCALbase/CMakeLists.txt, EMCAL/EMCALbase/TestsAliEMCALTriggerSTUDCSConfig.cxx, EMCAL/EMCALbase/TestsAliEMCALTriggerTRUDCSConfig.cxx, EMCAL/EMCALsim/AliEMCALTriggerElectronics.cxx, EMCAL/EMCALsim/AliEMCALTriggerElectronics.h, EMCAL/EMCALsim/CMakeLists.txt, PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx, PYTHIA6/AliPythia6/AliGenPythiaPlus.h, PYTHIA6/AliPythia6/AliPythia6.cxx, PYTHIA6/AliPythia6/AliPythia6.h, PYTHIA6/AliPythia6/AliPythiaBase.h, PYTHIA8/AliPythia8/AliPythia8.cxx, PYTHIA8/AliPythia8/AliPythia8.h
* Restore option to generate weighted events in AliGenPythiaPlus and add setting for AliPythia8
https://github.com/alisw/AliRoot/commit/a98c7f7bd8c9a9ff850d8684b26c37eda7d58c56#diff-6b966b6d0aa9f7582026d951afaecbe3ed80074d087b3f7140884f7deeac848f
* [ALIROOT-8649] Restore porting the event weight to the pythia header
https://github.com/alisw/AliRoot/commit/80c212d58b667e42dc37f7fa137ac38c56e66485#diff-6b966b6d0aa9f7582026d951afaecbe3ed80074d087b3f7140884f7deeac848f
* Adds a rescaling of the digits in MC so trigger signal energies match total deposited energy, as done in data
https://github.com/alisw/AliRoot/commit/471256c6415ece265f350b8671e667c88f2552a5#diff-8d4f87477168201a3bd96e6814ab0e0afe3dead85b882cf21105e9f220a2c97d
* Fixes an error where new L0 patch digits would be created with …
=> EMCal trigger fix and PYTHIA weights recovery to V5 09 56 patches

STEER/STEERBase/AliPIDResponse.cxx
Add correct use of "fUseTPCPileupCorrection" flag to TPCPIDResponse::GetExpectedSignal call for Monte Carlo when running with TuneOnData.
Removes shift in mean of TPC distribution observed in LHC18qr MC with new splines.
=> Fix application of TPC pileup correction for MC

FIT/FITbase/AliFITHits.cxx
Problem occurs in fluka but not in g3; Origin of problem not clear.
=> Protect for wrong array size. 

CMakeLists.txt
on cmake 3.20.5 there are problems if doxygen is already found. Just invalidate the already detected doxygen executable.
solution from https://gitlab.kitware.com/cmake/cmake/-/issues/18708
=> cmake:: fix doxygen finding on f34

STEER/AOD/AliAODv0.cxx
I spotted a leak in AliAODv0, which was causing a memory increase in the tests for conversions of HF candidates from ESD to AO2D.
In the constructor of AliAODv0 (which inherits from AliAODRecoDecay) we have:
AliAODv0::AliAODv0(AliAODVertex* rAODVertex, Double_t rDcaV0Daughters, Double_t rDcaV0ToPrimVertex,
const Double_t *rMomPos, const Double_t *rMomNeg, Double_t *rDcaDaughterToPrimVertex) :
AliAODRecoDecay(rAODVertex,2,0,rDcaDaughterToPrimVertex),
fDcaV0ToPrimVertex(rDcaV0ToPrimVertex),
fOnFlyStatus(kFALSE)
{
[...]
fDCA = new Double_t[fNDCA];
[...]
fPx = new Double_t[GetNProngs()];
fPy = new Double_t[GetNProngs()];
fPz = new Double_t[GetNProngs()];
[...]
}
The leak is caused by the fact that the constructor that is invoked for AliAODRecoDecay already creates fPx, fPy and fPz: …
=> Fix memory leak in AliAODv0 constructor

ITS/ITSsim/AliITSv11.cxx, ITS/ITSsim/AliITSv11.h, ITS/ITSsim/AliITSv11GeometrySDD.cxx, ITS/ITSsim/AliITSv11GeometrySPD.cxx, ITS/ITSsim/AliITSv11GeometrySSD.cxx, macros/Config_ITSdens.C
This commit introduces the possibility of varying the density of some materials used in the implementation of the SPD and SDD detectors, in order to perform material budget studies. By default no change takes places, but at run time the user has the possibility to multiply the density of some chosen materials by a scale factor.
=> Rescale ITS material density for budget studies

PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx, PYTHIA6/AliPythia6/AliGenPythiaPlus.h
This PR is needed for simulations in which one wants to select particles in the muon spectrometer acceptance.
It introduces the possibility to specify a pseudorapity itnerval for the trigger particle which is not symmetric around 0.
This feature is requested for upcoming muon productions.
=> Possibility to select trigger particle in asymmetric eta range

STEER/STEER/AliMC.cxx, STEER/STEERBase/AliPDG.cxx
The masses of the hyper hydrogen4 and the hyper helium4 need to be corrected since in the old implementation only the lambda separation energy of 2MeV/c2 was substracted from the sum of the constituents. This is incorrect since also the binding energy of the remaining nucleus (triton and he3 respectively) needs to be taken into account. Furthermore there is the existing of an excited state for both particles (see A. Gal, E.V. Hungerford and D.J. Millener, „Strangeness in nuclear physics“, Rev. Mod. Phys. 88 (2016) 3, 035004, arXiv:1605.00557 [nucl-th]) which is implemented now with the correct mass after the (very short lived) EM transition to the ground state.
=> Fix for hypernuclei masses

STEER/STEER/AliMC.cxx
, which means that the particle made it outside the
defined geometry, ie gGeoManager->IsOutside() == kTRUE
=> protection against -1 index

GPU/TPCFastTransformation/CMakeLists.txt
@davidrohr I had to do this fix on Ubuntu 18.04 to avoid undefined references when linking the executables.
=> Spline1DHelper, Spline2DHelper, SymMatrixSolver are needed by AliGPU

STARLIGHT/AliStarLight/AliDecayerSLEvtGen.h, STARLIGHT/starlight/include/nucleus.h, STARLIGHT/starlight/src/nucleus.cpp
No major changes were made, previously the STARlight generator was not compatible with ROOT6. Errors were solved by renaming the variables "_Z" and "_A" in nucleus.h without using underscores and commenting out a constant "kconv" in AliDecayerSLEvtGen.h
=> Adapting STARlight to ROOT6

ITS/ITSbase/AliITStrackerMI.cxx, test/gun/runtest.sh, test/vmctest/gun/runtest.sh
Since moving to `o2` defaults, the Linux CI check has been failing in AliRoot-guntest with a floating point exception. Peter tracked this down to a value `> 1.0` being passed to `asin` and provided this fix.
Written-by: Peter Hristov (@pzhristov)
=> Fix floating point exception in Linux guntest

STEER/STEERBase/AliMCEvent.cxx, STEER/STEERBase/AliVHeader.h
This modification to AliMCEvent::GetPrimaryVertex allows one to retrieve the generated vertex position for the trigger collision in case of AODs of MC productions with generated pileup.
This method was already returning the position of the trigger event for ESDs.
This is due to the fact that the vertex position of the trigger event is properly set in the "highest level" header of the cocktail  generator and it is thus correctly retrieved in AliMCEvent::GetPrimaryVertex.
However, this does not hold in the case of AODs, for which the "highest level" cocktail header is not made available in AliAODMCHeader (and therefore in AliMCEvent), due to the different structure of the event headers of the cocktail generator it was returning (0,0,0).
Nevertheless, the manipulations done in …
=> Get the generated vertex position of trigger event in case of pileup

HMPID/HMPIDsim/AliHMPIDv1.cxx, HMPID/HMPIDsim/AliHMPIDv2.cxx, HMPID/HMPIDsim/AliHMPIDv3.cxx, HMPID/HMPIDsim/AliHMPIDvG4.cxx, ITSMFT/ITS/v0/AliITSupgrade.cxx, PHOS/AliPHOSDebug.cxx, PHOS/PHOSsim/AliPHOSv1.cxx, PHOS/PHOSsim/AliPHOSvImpacts.cxx, PMD/PMDsim/AliPMDv0.cxx, PMD/PMDsim/AliPMDv1.cxx, PMD/PMDsim/AliPMDv2008.cxx, STEER/STEER/AliMC.cxx, T0/AliT0v2.cxx, ZDC/ZDCsim/AliZDCv3.cxx
- AliMC: Added protection in 'AddTrackReference' call against undefined track id (<0)
- Initialized arrays (if not done) passed to 'TVirtualMC::Gmtod' and 'Gdtom' calls as output parameters
=> Fixing problems observed in production:

EVGEN/AliDecayer.h, PYTHIA6/AliPythia6/AliGenPythiaPlus.cxx, PYTHIA8/AliPythia8/AliDecayerPythia8.cxx, PYTHIA8/AliPythia8/AliDecayerPythia8.h
This PR implements forced decay for D-meson resonances and resolves issues with their decay product track transport.
It is in response to the discussion documented here: https://alice.its.cern.ch/jira/browse/ALIROOT-8847.
=> Forcing Ds-reso decay and fixing track transport

STEER/STEER/AliMC.cxx
Suggested by @mpuccio , Sourav.
`f2(1270)` is missing due to the conflict of the previous force decay mode/
=> Updaet f0 f1 particle decay mode via AliMC

PYTHIA8/AliPythia8/AliDecayerPythia8.cxx, PYTHIA8/AliPythia8/AliDecayerPythia8.h, PYTHIA8/AliPythia8/AliPythia8.h
This is to allow for setting decay of longlived particles in pythia8 (fast sim).
It is currently not allowed because of a setting in AliDecayerPythia8 (default is still no decay for those particles)
=> allowing pythia8 decay longlived part for fast sim

PYTHIA8/pythia8243/src/FJcore.cc
It turns out that c++20 restricts the usage of forward
declarations of objects used in templates, particularly
std::vector. In this case functions defined inside the
class make use of an incomplete class - thanks to the
forward declaration -  when accessing functions of the
vector. The solutiion  in this case - since we have a
circular dependency here - is to move ALL function
definitions of ClosestPair2D  out of the class declaration
and after Point, so they always see a complete object.
=> Fixes for c++20

EVGEN/AliGenSexaquarkReaction.cxx
two bug fixes:
- default call of SetPhiRange is now in correct units (degrees instead of radians)
- momentum distributions for Fermi motion are now flat
=> Bugfix: AliGenSexaquarkReaction

ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx
Add a `-f` argument to the `find` commands that are used to produce collections. The new argument makes `find` return a full set of metadata about the files, generating XML files with the same content as the ones produced by the central services.
=> Tune `find` commands that generate XML collections
